### ISSUE TITLE
monitor out-of-date requirements

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#10]
When we start having actual Python package requirements, we should use something like requires.io to monitor the versions and ensure we don't get out-of-date.

For example, on a personal repo of mine:
https://requires.io/github/infinitewarp/trekipsum/requirements/?branch=master

**Comment by infinitewarp** [comment]
Also consider looking at https://pyup.io/

**Comment by ilyavw** [comment]
Turns out there are tons of potential solutions for this, who'd have known! Some of the other ones I'm looking at are https://snyk.io/ and https://dependabot.com/

**Comment by ilyavw** [comment]
Spent some more time testing snyk and dependabot today. Unfortunately it doesn't seem snyk will look at anything other than `requirements.txt`, even when you try to manually specify a path in the gui it'll reject it. Dependabot seems to search for all requirements files, but this is not configurable. It'll also not post changelogs and won't have an initial meta-pr at the beginning.

So while those two were worth investigating, pyup.io seems to be a clear winner with how it works.
