### ISSUE TITLE
`openapi.json` incorrectly defines `user_id` type as `string`, not `integer`

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1021]
## Summary

As mentioned in Slack [here](https://ansible.slack.com/archives/C8VGAPJNN/p1632750637494900), our generated `openapi.json` incorrecly defines `CloudAccount.user_id` type as `string`, but the actual results from the API appear to be `integer`. This is causing problems with IQE which has recently started using a client generator that strictly enforces expected response types.

https://github.com/cloudigrade/cloudigrade/blob/ee7959a1a69ac971b4cbc096f035cd5e1080814f/openapi.json#L850

Example API output (truncated):

```
            "created_at": "2021-09-27T07:20:08.401622Z",
            "is_enabled": true,
            "name": "aws-account-439727791560",
            "platform_application_id": 62728,
            "platform_application_is_paused": false,
            "platform_authentication_id": 59300,
            "platform_source_id": 70637,
            "updated_at": "2021-09-27T07:20:08.404328Z",
            "user_id": 6074
        }
```

## Steps to Reproduce

- Create a valid cloud account.
- Request the cloud account's user_id from the API. For example:
  ```sh
  ❯ http :8000/api/cloudigrade/v2/accounts/ "X-RH-IDENTITY:${X_RH_IDENTITY}" | jq '.data[0] | {user_id}'
  {
    "user_id": 1
  }
  ```
- Compare the type in the response to the type defined in `openapi.json`

## Expected Result

- Type is the same.

## Actual Result

- Actual response type is integer, but `openapi.json` declares string.

## Additional context

- `user_id` in this case is a foreign key to `User.id` from `CloudAccount`.
- In postgresql, `public.api_cloudaccount.user_id` is `integer`.
- We do not explicitly define a custom schema for this object.
- So, there's likely a bug in DRF's automatic schema generation.
- @paraggit has temporarily patched around this problem directly in IQE, but we should not rely on that patch any longer than required.
- When we fix this, please confirm with @paraggit that the temporary patch is removed.

**Comment by infinitewarp** [comment]
If this is a bug in DRF itself (@abellotti said it looks like like *all* foreign keys are treated as strings), we should consider fixing it upstream and submitting a PR to DRF itself.

**Comment by paraggit** [comment]
@abellotti I am removing the earlier workaround used in iqe_cloudmeter plugin, Now generating new openapi client with theses changes. I will run some tests with new client and verify this issue.

**Comment by infinitewarp** [comment]
@paraggit are those tests with the updated client still in progress?

**Comment by paraggit** [comment]
@infinitewarp I will wait for next round of iteration of vortex regression suite then i will close this issue.

**Comment by paraggit** [comment]
Regression results looks good hence moving this issue to close state.
