### ISSUE TITLE
Automate promotions from stage to production

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#1023]
## Summary

As a Red Hat Engineer I want to Release Early, Release Often. As part of that, I want changes that have merged to master, that get automatically deployed to stage, to be verified by an IQE smoke test, and be automatically promoted to production.

## Acceptance Criteria

- [ ] Verify the stage smoke test successfully runs and tests the stage deployment of Cloudigrade
- [ ] Verify that success leads to successful automatic promotion of the stage hash, to production.

## Assumptions and Questions

- This is mostly @katherine-black following up on conversations since we're the(?) first team to do this?

**Comment by abellotti** [comment]
This was probably already discussed somewhere, but one concern I have on the above is: does an IQE smoke test result sufficient to trigger the stage->prod promotion, or do we want a QE person to give a final blessing (verifying what was fixed in a PR was actually fixed, the smoke test may or may not have tested the new path yet) and click a button somewhere to trigger the promotion.  I tend to lean toward the latter myself, but that's just me.

**Comment by infinitewarp** [comment]
Here's a different thought: maybe we should have the PR checks run the full IQE tests (~2.5 hours) and have stage run only smoke (~20 minutes). This would improve confidence that we are not introducing regressions.

But are there timeout/max time limitations? This may require some experimentation.

**Comment by katherine-black** [comment]
Slack Convo -- https://coreos.slack.com/archives/C023YSA47A4/p1632502727340300

**Comment by infinitewarp** [comment]
We had a successful automatic promotion today. The commit it made:

```
commit 56ce89c842cf47724025bb908e23b653af6c76b9
Author: App SRE bot <sd-app-sre+gitlab@redhat.com>
Date:   Mon Nov 15 07:10:21 2021 +0000

    auto promote 677cc56781dc7a3a733dcc6727db24638d974486 in data/services/insights/cloudigrade/cicd/deploy-clowder.yml
```

and checking a current pod in prod to verify that it actually deployed as expected:

```
>>> settings.CLOUDIGRADE_VERSION
'677cc56'
```

Do we want to wait for a few more successful deployments before calling this "done"? Are there any other specific requirements we should verify?

**Comment by katherine-black** [comment]
Honestly, I feel like if it works, it works. Our part of this is done, and if anything breaks, we can raise new issues there. Does that sound reasonable @infinitewarp ?

**Comment by infinitewarp** [comment]
I like the sound of that. Thanks for the sanity-check, @katherine-black!

☑️
