### ISSUE TITLE
Enable Sentry tracing with custom filter

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1025]
## Summary

As a cloudigrade sysop, I want more information about requests going through the API so that I can diagnose unexpected issues. Sentry has has an option to enable stack tracing through requests, and we want to enable this feature if we can limit its use to specific APIs.

We tried enabling this feature when it was first introduced, but we quickly disabled it because we exhausted our quota thanks to the many internal health checks to our pods via HTTP. We believe we can now filter the requests that get traced and reported to Sentry. The filter we implement should specifically exclude the path(s) to our health checks.

## Acceptance Criteria

- [x] Verify we have tracing data in Sentry
- [x] Verify we do not have tracing data for the health checks

## Assumptions and Questions

- We acknowledge that the internal platform supported Sentry is going away and being replaced with another tool (maybe [GlitchTip](https://glitchtip.com/)). As long as we continue using the public sentry.io, we're okay with using its features.
- The platform's choice to switch internal monitoring services should not affect this work. 
- The possible future integration with Jaeger should not affect this work.
- How do I implement a filter?
  - This is an exercise for the reader. 🙂 Please link to any docs you find on this issue.
  - https://docs.sentry.io/platforms/python/configuration/filtering/
- How do we test this?
  - Consider making another DSN with its own credentials that we can use briefly in an ephemeral environment. If we create this, please remember to delete it when you're done testing.
- Important note: we are allowed 100K transactions per month on our current Sentry billing plan.

**Comment by katherine-black** [comment]
Looks good, thank you.
