### ISSUE TITLE
Set up initial "internal" queue

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#106]
As a Doppler developer, I want my own queue so that I can build services that send messages via a queue without depending on an externally managed service (á la Amazon SQS).

## Acceptance Criteria 

- [x] Verify that a queue is running in a locally Dockerized container
  - [x] Verify that you can put a message
  - [x] Verify that you can pop/read a message
- [x] Verify that documentation has been updated to include setup notes and suggested library usage
- [x] Verify that the `Makefile` has been updated to automatically set up/tear down the queue

## Tech assumptions

- Evaluate RabbitMQ, Redis, Red Hat AMQ, etc.
  - Support for queues _and_ subscriptions.
  - Availability of Django support.
  - Ease of setup.
  - Ease up use as a developer.
  - General popularity (see StackOverflow? GitHub stars and forks?)
  - We don't really care as much about high performance at this point as much as ease of use.
- Take a look at how Celery works.

**Comment by adberglund** [comment]
Spent some time reviewing three options RabbitMQ, Redis, and Red Hat JBoss AMQ. 

 - JBoss AMQ has the features we need, and if there is a strong future push to use internal products we can make this happen. Currently there is documented support only through Python 2.7 and we are running Python 3.6. It would probably work, but it's not officially supported for our project. 
 - Redis would work, but it's not _really_ message broker out of the box, you have to force it to do this.
 - RabbitMQ is a message broker, and features what we need with simple setup.

**Comment by adberglund** [comment]
To test RabbitMQ I am using two scripts to add a message and receive a message from the queue. These are taken directly from the excellent RabbitMQ tutuorials [RabbitMQ - Getting started with RabbitMQ](https://www.rabbitmq.com/getstarted.html).
