### ISSUE TITLE
Sonarqube in PR checks

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1061]
## Summary

As a cloudigrade maintainer, I want Sonarqube periodically testing my code with my PR checks so I am alerted to vulnerabilities.

See https://docs.google.com/document/d/10HismV2f6JABkfzUOb3aCIAYSqy17TxJwN4ivKjoaHk/edit#heading=h.x4sgywyw1dq4

## Acceptance Criteria

- [ ] Verify PR check triggers Sonarqube
- [ ] Verify results are visible (where? as a typical PR check? document this here)

## Assumptions and Questions

- How long does the typical Sonarqube check take to complete?
- Do we require a Sonarqube positive result? Or leave it optional?
  - If the sonar check runs separately from our existing ci.ext check, make sonar optional for now.
- Does this mean our already sad slow PR check is going to get even sadder slower?
  -  Please document notes here as you investigate and develop.
- If the process documented in the above Google Doc is not actually working, please ask Chris Hambridge for guidance. If things are really bad, we'll stop work and block this issue.

**Comment by abellotti** [comment]
Investigation:
- SonarQube takes around 3-5 minutes to run, but it is dependent on the number and size of the source files being scanned.
- So far fleet management, cost management and compliance and enabled SonarQube, so we won't be the guinea pig.
- Because the SonarQube corporate server is internal, the pr-check will wire this via ci.int and not ci.ext
- ci.int can run in parallel to ci.ext, so hopefully we won't get hit with the additional 3-5 minutes.

**Comment by abellotti** [comment]
Progress:
- new [sonarqube.corp.redhat.com](https://sonarqube.corp.redhat.com) project: [console.redhat.com:cloudigrade](https://sonarqube.corp.redhat.com/dashboard?id=console.redhat.com%3Acloudigrade) 
- new cloudigrade vault location for ci-cd: insights-cicd/cloudigrade/ MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/28734

**Comment by abellotti** [comment]
App-SRE MR merged and Cloudigrade PR successfully running the SonarQube security scan via ci.int:
![image](https://user-images.githubusercontent.com/5797328/143105082-89f40679-91d5-4dae-92bb-35c7a3d887a7.png)

**Comment by abellotti** [comment]
SonarQube scan success:
![image](https://user-images.githubusercontent.com/5797328/143106431-9e9cb5ab-16ce-48b1-af19-6e46ad98ac60.png)

**Comment by paraggit** [comment]
SonarQube scan has implemented with pr_check workflow.  Find the below link for the run status. 
https://sonarqube.corp.redhat.com/dashboard?id=console.redhat.com%3Acloudigrade

Moving this issue to close state.
