### ISSUE TITLE
More dedicated queues for Celery tasks

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1063]
## Summary

As a cloudigrade sysop, I want to more clearly understand which tasks are piling up in the queues when we see a large number so that I can better diagnose and resolve the misbehaving task.

We recently experienced an incident that spawned 100,000+ messages on the default Celery queue. Unfortunately, there are several tasks that use the default queue, and this made troubleshooting difficult. We should update our configuration so that all current Celery tasks use their own respective queue.

## Acceptance Criteria

- [x] Verify via code review that all tasks have configured queues
- [x] Verify that cloudigrade still functions normally
- [x] Verify via an actual deployment that the new queues exist in AWS SQS

## Assumptions and Questions

- When we deploy this to stage and prod, we should check the old Celery queue for any unread messages and requeue them to their new queues. How do we do this? One-off manual script run?
- The original issue that caused 100,000+ messages to be in queue has been resolved independently and is part of this issue. That was caused by our deployment having too few workers and being unable to process enough messages quickly. That was resolved by adding more workers.

**Comment by abellotti** [comment]
**Cloudigrade Celery Tasks:**

____

- api/clouds/aws/tasks/__init__.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.clouds.aws.tasks.attach_volumes_to_cluster                       | n | n |
| api.clouds.aws.tasks.create_volume                                   | n | n |
| api.clouds.aws.tasks.enqueue_ready_volume                            | n | n |
| api.clouds.aws.tasks.run_inspection_cluster                          | n | n |
| api.clouds.aws.tasks.scale_down_cluster                              | n | n |
| api.clouds.aws.tasks.scale_up_inspection_cluster                     | n | n |
| api.clouds.aws.tasks.verify_verify_tasks                             | n | n |

____

- api/clouds/aws/tasks/cloudtrail.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.clouds.aws.tasks.analyze_log                                     | y | n |

____

- api/clouds/aws/tasks/imageprep.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.clouds.aws.tasks.copy_ami_snapshot                               | y | n |
| api.clouds.aws.tasks.copy_ami_to_customer_account                    | y | n |
| api.clouds.aws.tasks.delete_snapshot                                 | y | n |
| api.clouds.aws.tasks.remove_snapshot_ownership                       | y | n |

____

- api/clouds/aws/tasks/inspection.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.clouds.aws.tasks.launch_inspection_instance                      | y | n |

____

- api/clouds/aws/tasks/maintenance.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.clouds.aws.tasks.repopulate_ec2_instance_mapping                 | y | n |

____

- api/clouds/aws/tasks/onboarding.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.clouds.aws.tasks.configure_customer_aws_and_create_cloud_account | n | n |
| api.clouds.aws.tasks.initial_aws_describe_instances                  | n | n |

____

- api/clouds/aws/tasks/verification.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.clouds.aws.tasks.ensure_all_verify_tasks_are_valid               | n | n |
| api.clouds.aws.tasks.verify_account_permissions                      | n | n |

____

- api/clouds/azure/tasks/maintenance.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.clouds.azure.tasks.repopulate_azure_instance_mapping             | n | n |

____

- api/tasks/calculation.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.tasks.calculate_max_concurrent_usage_task                        | n | n |
| api.tasks.fix_problematic_runs                                       | n | n |
| api.tasks.recalculate_concurrent_usage_for_all_users                 | n | n |
| api.tasks.recalculate_concurrent_usage_for_user_id                   | n | n |
| api.tasks.recalculate_concurrent_usage_for_user_id_on_date           | n | n |
| api.tasks.recalculate_runs_for_all_cloud_accounts                    | n | n |
| api.tasks.recalculate_runs_for_cloud_account_id                      | n | n |

____

- api/tasks/inspection.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.tasks.inspect_pending_images                                     | n | n |
| api.tasks.persist_inspection_cluster_results_task                    | n | n |

____

- api/tasks/maintenance.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.tasks.delete_cloud_account                                       | n | n |
| api.tasks.delete_inactive_users                                      | n | n |
| api.tasks.delete_orphaned_cloud_accounts                             | n | n |
| api.tasks.enable_account                                             | n | n |

____

- api/tasks/sources.py

| Task | In Route | In Worker |
| ---- | :------: | :-------: |
| api.tasks.create_from_sources_kafka_message                          | n | n |
| api.tasks.delete_from_sources_kafka_message                          | n | n |
| api.tasks.notify_application_availability_task                       | n | n |
| api.tasks.pause_from_sources_kafka_message                           | n | n |
| api.tasks.unpause_from_sources_kafka_message                         | n | n |
| api.tasks.update_from_sources_kafka_message                          | n | n |

____

**Comment by abellotti** [comment]
A follow up PR could be crafted to delete the tasks marked as deprecated if seen as unpopulated. These include:

- attach_volumes_to_cluster
- create_volume
- enqueue_ready_volume
- run_inspection_cluster
- scale_down_cluster
- scale_up_inspection_cluster
- verify_verify_tasks

**Comment by abellotti** [comment]
All new queues from https://github.com/cloudigrade/cloudigrade/pull/1085 added to both stage and prod. Both stage- and prod- celery queues are empty (so far). we'll keep and eye on them.

**Comment by infinitewarp** [comment]
Looking good so far. Thanks!
