### ISSUE TITLE
Use KEDA for autoscaling pods

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1066]
Yes, this is actually blocked. Timeline of "progress" waiting to see it unblocked:

- 2022-08-03: [SDE-1543](https://issues.redhat.com/browse/SDE-1543) "SAG review scheduled for August 23, 2022, we'll update the outcome by then. https://issues.redhat.com/browse/SAGA-48"
- 2022-04-11: [OCPNODE-708](https://issues.redhat.com/browse/OCPNODE-708) Target Version changed from OpenShift 4.11 to 4.12 
- 2022-04-04: “This will not be done by feature-freeze on Apr 22… Depending on how we make progress…around [OpenShift] 4.11 GA timeframe.”
- 2022-03-28: “This is pending SAG approval, holding until the presentation has been completed.” [SDE-1543](https://issues.redhat.com/browse/SDE-1543).
- 2022-02-23: see also [OCPNODE-708](https://issues.redhat.com/browse/OCPNODE-708).
- 2022-01-24: see also [SDE-1543](https://issues.redhat.com/browse/SDE-1543).
- 2022-01-17: [RHCLOUD-17105](https://issues.redhat.com/browse/RHCLOUD-17105) was closed as “done” but it’s not actually done. See [RHCLOUD-16910](https://issues.redhat.com/browse/RHCLOUD-16910) instead.
- 2022-01-11: as of 2022-01-10 this is still blocked on discussions between platform and SRE.
- 2021-12-15: as of 2021-12-13 this is still blocked on discussions between platform and SRE. See also https://issues.redhat.com/browse/RHCLOUD-16910
- 2021-12-08: see https://github.com/cloudigrade/cloudigrade/issues/1066#issuecomment-988946486
- 2021-11-30: on the subscription reporting program call, Kevin Howell said, "App SRE is blocking KEDA in the higher environments". What's the state of that? Also what's the state of testing and documentation? See also https://ansible.slack.com/archives/C8VGAPJNN/p1638291583117800 

----

## Summary

As a cloudigrade sysop, I want deployments to scale more and fewer pods as needed so that I don't have to monitor use and manually update replica counts. Switch from standard HPA definition to new KEDA-based autoscaling definition.

## Acceptance Criteria

- [ ] Verify autoscaling actually works with reasonable values for cloudigrade-api, cloudigrade-worker, and postigrade.

## Assumptions and Questions

- See https://github.com/RedHatInsights/clowder/pull/471 for implementation details
- We want to drop any of our old configs for the HPAs and effectively convert the mins and maxes from HPA to KEDA-speak.
- We do not want to investigate alternate metrics or adjust the numbers with this issue. We just want to get it working. We may revise the metrics and numbers in a future issue if needed.
- Assume that KEDA works. If the expected YAML is not working, we go back to platform and make them fix it.

**Comment by katherine-black** [comment]
Blocked per https://ansible.slack.com/archives/C8VGAPJNN/p1636564340338800

**Comment by infinitewarp** [comment]
Also blocked on https://coreos.slack.com/archives/C023YSA47A4/p1638292027110300

According to Kyle Lape and Pete Savage,
> Keda is currently blocked by appsre
and 
> my understanding is they want us to look at hpa but if we still want keda, we will have to basically onboard the operator

Also blocked on https://issues.redhat.com/browse/RHCLOUD-17105
