### ISSUE TITLE
Azure Reinvestigation?

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#1068]
Placeholder spike for @katherine-black to go off for a week and gather/create as many notebooks for Azure interactions relevant to us. Why? Because three years ago we copy pasted our aws architecture for azure, long before we had any good understanding of what our data models and interactions would look like. We should revisit some more high level interactions and try to get a good idea of what kind of data is even available to us in the first place from a typical azure customer.

**Comment by katherine-black** [comment]
Here is the summary of our earlier discussion during refinement:

### Option One, more traditional, is AzCopy. https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10

AzCopy is a powerful binary provided by Azure that allows us to read and write azure blob storage devices. It also allows us to read and write that data to other places, like local fs, or AWS S3, or GCS.

ex1 clone a disk
```
# create our disk
az disk create -n DISKNAME -g GROUP -l LOCATION --os-type Linux --for-upload --upload-size-bytes 8589935104 --sku standard_lrs
--for-upload indicates to create an empty disk that will have data written to it still. Note we need to provide accurate size.
# grant access to our disk
az disk grant-access -n DISKNAME -g GROUP --access-level Write --duration-in-seconds 86400
# grant access to customer disk 
az disk grant-access -n CUSTOMER_DISKNAME -g CUSTOMER_GROUP --access-level Read --duration-in-seconds 86400
```
grant-access commands will provide two urls, after that we azcopy copy url1 url2 --blob-type PageBlob
That would move it from Azure to Azure. Instead of having a second sas url, we can always have it be local fs, s3 (in case we want to do something horrible like copy out customer images, make them into images in aws, and then use those newly created aws ami to inspect through existing houndigrade aws flow, but I would never suggest something that terrible).

The catch? Well... the disk can NOT be attached to a vm when this happens. We COULD make a snapshot of the running disk, and then create a disk from said snapshot, then finally, said disk could be given read access to and copied to our subscription or elsewhere we want to do the inspection. This is a lot of steps, some of them still taking place in the customers subscription, but is by far the most straightforward way to retrieve customer data for inspection purposes.

### So Option Two? 

Since Azure does not appear to do any of its own inspection on a disk for the sake of its metadata gathering, instead it seems entirely reliant on its agent which is able to gather rudimentary data. 

The agent does some rudimentary data scraping as it runs, for example, a basic check to see distribution info:
https://github.com/Azure/azure-linux-extensions/blob/1769f67c679450090e5d184e9e2abd2956d9352d/Utils/distroutils.py#L13-L39

So thats interesting, can we use it? extend it? Well... 
https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/agent-linux

Important part:
VM Extension
Inject component authored by Microsoft and Partners into Linux VM (IaaS) to enable software and configuration automation
VM Extension reference implementation on https://github.com/Azure/azure-linux-extensions

So the potential here is _very_ high, all the inspections that houndigrade does can simply be part of a cloudigrade extension for the linux agent. Activity monitoring, presence on all* azure linux vms, etc...

**Comment by infinitewarp** [comment]
See also discussion recording from today's backlog refinement: https://bluejeans.com/s/Dh0yiAIFJ3Q

**Comment by infinitewarp** [comment]
Thank you for sharing your research notes! I have renewed optimism about our future Azure integration. 🙂
