### ISSUE TITLE
Keep the not-enabled CloudAccount if initial permissions verification fails

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1075]
Stop! Maybe this is a bad idea!

Update 2021-12-15: Last week on 2021-12-08 we discussed possible solutions with the sources-api dev team. The conclusion to that discussion was that the source-api would implement new changes to better track the initial state of a source/application and would also track a counter for sequential number of failed attempts to verify/validate. As a result of that work, cloudigrade may not need to do anything special for the initial onboarding of a source. sources-api would resend the create message as they see fit.

Update 2021-11-24: What if instead sources-api reconsiders and changes its flow around new applications/sources/etc. specifically to be different from established known-working sources? Is there a way for sources-api to handle initial rejection differently? We should explain to them that on our side, if the initial permissions fail, we do not create our entities because we are afraid of getting lots of bogus sources that will never be valid. Think DoS attacks. Can sources-api do something about this? Or do we need to accept that we may have to deal with bogus ARNs/etc forever? @gtanzillo is going to start a conversation with the sources-api maintainer about this. 

[GT] Update: 2021-12-02 - Discussed the above with Drew and he indicated that this may be a good time to consider changes to the onboarding flow to accommodate this case. He will further discuss with Sources eng and follow up with us.

----

Comments from 2021-11-17:

We probably don't want to just create disabled accounts and retry forever (or even with exponential backoff for a while) because a malicious user could use that to make us pound AWS with lots of bogus ARN requests. Maybe it's actually correct for us to try once and give up on a new source/account. If so, then how does the customer recover? We may simply need to improve messaging to ask the customer to recreate their source.

Warning about how we change the message to the user!

We need to make it very clear that they should only delete and recreate the source if they are encountering this issue during their initial source creation. If they had a working source at some time, but maybe someone broke the policy, we don't want them deleting and losing their tracked data.

Alternately, maybe we can try to determine if this is a "first time setup" situation and report a different error code that specifically mentions recreating the source.

@paraggit mentioned on 2021-11-17 that the IQE tests if they see the GC3* error will attempt to delete and recreate the source up to three times. He *is* actually seeing the 3 times be hit on occasion, and that makes @infinitewarp think that something very strange is happening in AWS. Meanwhile, source-api is adding some delays to the kafka notification process in the hopes that they won't "thundering herd" us when change occur. Before resuming investigation on this issue, check those things I just mentioned here!

-----

## Summary

As a cloudigrade user, I want cloudigrade to automatically recover and enable my cloud account if the initial permissions verification fails. If the permission issue was an intermittent AWS problem or the customer fixes the malform role or policy, we should keep the not-enabled cloud account so that our periodic verification task may later discover that it's healthy and re-enable itself.

Currently, when handling creation via sources/kafka, we put the whole account creation and verification process into one transaction. If verification fails, the transaction rolls back, and we lose the whole CloudAccount object. Therefore we have no periodic verification of it. Unless the customer deletes and recreates the sources objects, we may never know to check access for their ARN.

The key change here would be to separate the act of CloudAccount creation from its subsequent enable/verify.

This description is based on a _brief_ code review by @infinitewarp as he was investigating [this conversation](https://ansible.slack.com/archives/C8VGAPJNN/p1637069776464300). We should verify the above assumptions about our code's behavior as we proceed here.

## Acceptance Criteria

- [ ] Verify that cloudigrade keeps retrying its permission check after initially failing and may eventually re-enable
    a. Misconfigure AWS role or policy
    b. create a source with its ARN
    c. observe cloudigrade report the `GC3002` or `GC3003` to sources
        - At this point in the _old code_, cloudigrade should have tried to create but rolled back. The cloud account would not exist. Check this!! In the new code, the cloud account _should exist_ but not be enabled.
    d. fix the AWS role or policy (but don't touch sources-api)
    e. wait for cloudigrade's to check the permissions again
    f. verify that the original account/source is properly enabled in sources-api

## Assumptions and Questions

- Current workaround is to destroy and recreate the objects from the sources side.
- @infinitewarp believes that the current "put all of creation and verification in one transaction" is a leftover artifact from previous architecture design iterations and that we should be safe to split these operations now.

**Comment by infinitewarp** [comment]
@syncrou and @lindgrenj6 do you have an issue in JIRA (or elsewhere?) for tracking the work on sources-api?

We're closing the issue on cloudigrade's side with the expectation that work is being tracked elsewhere.

**Comment by lindgrenj6** [comment]
@infinitewarp we have an epic here: https://issues.redhat.com/browse/RHCLOUD-17325

No stories in there yet, but they will be coming soon :tm:
