### ISSUE TITLE
Upgrade RDS PostgreSQL to latest stable minor version

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1130]
## Summary

As a cloudigrade sysop, I want to follow SRE's version guidance defined in [RDS OS Upgrades - June 2022](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/aws/maintenance/rds-upgrades-june-2022.md) so that our deployments are running fully-supported psql and OS versions.

- See also [this CoreOS Slack thread](https://coreos.slack.com/archives/CCRND57FW/p1646153169840509).
- See also [Upgrade Minor Version for PostgreSQL RDS Instance](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/aws/sop/postgresql-rds-instance-minor-version-upgrade.md)

## Acceptance Criteria

- [ ] Verify stage and prod running the latest supported minor version of PSQL.
- [ ] Verify OS upgrades have run.

## Assumptions and Questions

- When do we take downtime for the PSQL and OS upgrades?
  - During business hours US central time. We probably don't need to worry about customer impact.
  - We expect the downtime period to be very short since we expect no data migrations.
- Maybe jump from PSQL 11 to 12? Ephemeral deployments currently use 12, but we use 11 in stage and prod.
  - Not yet.
- Or even newer? 13 and 14?
  - Not yet.
- Does SRE have any docs for major PSQL version upgrades?
- For now, let's just upgrade to an SRE-compliant minor version. Future issue (https://github.com/cloudigrade/cloudigrade/issues/1131) will upgrade major version.

**Comment by katherine-black** [comment]
https://ansible.slack.com/archives/C8VGAPJNN/p1647973600355629

**Comment by infinitewarp** [comment]
For future reference: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/35900

**Comment by infinitewarp** [comment]
I have manually connected to both our stage and prod databases using `psql` (my local client version is 14.1) and verified that they're using the latest minor version as specified in the aforementioned app-interface changes.

```
psql (14.1, server 11.15)
Type "help" for help.

postgres=> show server_version;
 server_version
----------------
 11.15
(1 row)

postgres=> select version();
                                                 version
----------------------------------------------------------------------------------------------------------
 PostgreSQL 11.15 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit
(1 row)
```

It looks good. Thanks @katherine-black ! 🎉
