### ISSUE TITLE
Upgrade RDS PostgreSQL to latest stable major (and minor) version

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1131]
## Summary

As a cloudigrade sysop, I want to use the latest stable major version of PSQL and for that same version to be used in all our environments.

https://github.com/cloudigrade/cloudigrade/issues/1130 upgraded to the latest minor version, but we are uncertain about the path forward for major version upgrades.

## Acceptance Criteria

- [ ] Verify stage, prod, and ephemeral deployments are all using a modern stable (and same) version of PSQL.
- [ ] Verify we have documented or found and linked to AppSRE's documentation for performing major version PSQL upgrades.

## Assumptions and Questions

- When do we take downtime for the PSQL and OS upgrades?
  - During business hours US central time. We probably don't need to worry about customer impact.
  - We expect the downtime period to be very short since we expect no data migrations.
  - @infinitewarp did a trial run by loading a recent prod DB dump into an empty database on localhost. It took 10 seconds.
- See also https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/README.md#approved-rds-versions for SRE-supported versions.
- AWS appears to support major upgrades but may require manual steps. Does SRE handle those steps? How? Where documented?
  - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion
  - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html
  - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Upgrading.html

**Comment by katherine-black** [comment]
Upgrading a major version is as easy as upgrading a minor version if `allow_major_version_upgrade: true` is set.

**Comment by infinitewarp** [comment]
For future reference, since 14 isn't available for ephemeral yet, additional change need to happen here:
- https://gitlab.cee.redhat.com/insights-platform/postgresql-rds/ to get v14 images at https://quay.io/repository/cloudservices/postgresql-rds
- https://github.com/RedHatInsights/clowder/blob/master/controllers/cloud.redhat.com/providers/database/provider.go#L37 to make those new images available for use

**Comment by katherine-black** [comment]
https://issues.redhat.com/browse/RHCLOUD-18611

**Comment by infinitewarp** [comment]
update stage to 13.6: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/36084

**Comment by katherine-black** [comment]
Update prod to 13.6: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/36276

Due to be deployed Thursday between 1700 and 1800 UTC.

**Comment by infinitewarp** [comment]
confirmed stage:
```
❯ psql
psql (14.1, server 13.6)
Type "help" for help.

postgres=> show server_version;
 server_version
----------------
 13.6
(1 row)

postgres=> select version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 13.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit
(1 row)

postgres=>
```

and prod:
```
❯ psql
psql (14.1, server 11.15)
Type "help" for help.

postgres=> show server_version;
 server_version
----------------
 13.6
(1 row)

postgres=> select version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 13.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit
(1 row)

postgres=>
```

Thanks! 🎉
