### ISSUE TITLE
Research: More vulnerability scanning (CodeQL?)

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1138]
## Summary

As a cloudigrade developer, I want my code thoroughly checked for vulnerabilities and risks to minimize bugs and security issues.

Can we and should we enable CodeQL vulnerability scanning? Or other tools via GitHub automation? See:

- https://codeql.github.com/docs/codeql-overview/about-codeql/
- https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql
- https://github.com/cloudigrade/cloudigrade/actions/new?category=security

Let's take some time to investigate our options, [verify SonarQube is well-configured](https://github.com/cloudigrade/cloudigrade/issues/1140), and answer the following questions before integrating:

- Are there more things we can enable SonarQube to check that we are not already checking?
  - See also for reference the original integration issue: https://github.com/cloudigrade/cloudigrade/issues/1061
- What is the feature gap between SonarQube and CodeQL?
- Are there enough additional benefits to CodeQL (or other readily-available GitHub integrations) over SonarQube to warrant the extra integration?
- What is the level of effort to enable CodeQL in a valuable way?

Time box: 3 days

After discussion, we may create another issue to actually track additional implementation.

**Comment by infinitewarp** [comment]
Prototype PR here: https://github.com/cloudigrade/cloudigrade/pull/1311

**Comment by infinitewarp** [comment]
To answer the questions in the issue description:

> Are there more things we can enable SonarQube to check that we are not already checking?

As far as I can tell, no, it appears that there are no additional options we can configure. There appears to be a tighter MR integration for projects hosted in gitlab.cee.redhat.com, but that doesn't apply to us.

> What is the feature gap between SonarQube and CodeQL?

SonarQube and CodeQL both try to identify potential vulnerabilities based on specific coding antipatterns. CodeQL integrates very nicely with GitHub and provides quick and immediate feedback on PRs, and CodeQL populates the GitHub security page with useful information about issues it has identified. SonarQube doesn't do these things, and it requires us to actively check the SQ server for results whenever we might remember.

SonarQube also allows us to enable specific rule sets or even define new rules. Defining a new rule is a moderately complex exercise, but it's well documented, open source, and available to try whenever we want.

> Are there enough additional benefits to CodeQL (or other readily-available GitHub integrations) over SonarQube to warrant the extra integration?

I believe so, yes. CodeQL is open source and regularly receives contributions to update their rules. CodeQL is updated automatically by GitHub or Microsoft. SonarQube is more of a black box from our perspective, and we don't know or control if or when its rules are updated.

> What is the level of effort to enable CodeQL in a valuable way?

Minimal! The work is done as of https://github.com/cloudigrade/cloudigrade/pull/1311 and https://github.com/cloudigrade/cloudigrade/pull/1377, it identified several minor issues with our code, and I already fixed those issues in https://github.com/cloudigrade/cloudigrade/pull/1378.

**Comment by abellotti** [comment]
Thanks @infinitewarp for digging in and answering those questions, and CodeQL FTW: https://github.com/cloudigrade/cloudigrade/security/code-scanning

Closing this issue.
