### ISSUE TITLE
`api.tasks.delete_cloud_account` OOMs for account with lots of activity

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1156]
## Summary

When cleaning up lots of synthetic data in stage, I recently encountered an account that could not be deleted using the internal HTTP API because the worker executing the `delete_cloud_account` task for that request was being killed. It appeared to be killed due to OOM due to the large amount of related data.

As a workaround, I connected directly to the stage database and manually deleted many of its related rows. I called the internal HTTP API to delete the account, and the task completed normally.

First, I thought the problem was too many events:

```
postgres=> begin ;
BEGIN
postgres=*> delete from api_awsinstanceevent ae using api_instanceevent e, api_instance i, django_content_type ct where ae.id = e.object_id and e.instance_id = i.id and i.cloud_account_id = 25449 and e.content_type_id = ct.id and ct.app_label = 'api' and ct.model = 'awsinstanceevent';
DELETE 597040
postgres=*> delete from api_instanceevent e using api_instance i where e.instance_id = i.id and i.cloud_account_id = 25449;
DELETE 597040
postgres=*> commit ;
COMMIT
```

The internal HTTP API delete still failed, and I then realized that the problem may be too may instances and runs:

```
postgres=> begin ;
BEGIN
postgres=*> -- delete usage
postgres=*> delete from api_concurrentusage_potentially_related_runs cr using api_concurrentusage u, api_cloudaccount a where cr.concurrentusage_id = u.id and u.user_id = a.user_id and a.id = 25449;
DELETE 324364
postgres=*> delete from api_concurrentusage u using api_cloudaccount a where u.user_id = a.user_id and a.id = 25449;
DELETE 39
postgres=*> delete from api_run r using api_instance i where r.instance_id = i.id and i.cloud_account_id = 25449;
DELETE 298587
postgres=*> -- delete images
postgres=*> delete from api_awsmachineimage ami using api_machineimage mi, api_instance i, django_content_type ct where ami.id = mi.object_id and mi.id = i.machine_image_id and i.cloud_account_id = 25449 and mi.content_type_id = ct.id and ct.app_label = 'api' and ct.model = 'awsmachineimage';
DELETE 1000
postgres=*> delete from api_machineimage mi using api_instance i where mi.id = i.machine_image_id and i.cloud_account_id = 25449;
DELETE 1000
postgres=*> -- delete instances
postgres=*> delete from api_awsinstance ai using api_instance i, django_content_type ct where ai.id = i.object_id and i.cloud_account_id = 25449 and i.content_type_id = ct.id and ct.app_label = 'api' and ct.model = 'awsinstance';
DELETE 30000
postgres=*> delete from api_instance i where i.cloud_account_id = 25449;
DELETE 30000
postgres=*> commit ;
COMMIT
```

## Steps to Reproduce

I believe this data originated when I made the following synthetic data request:

```
http \
    --proxy="https:http://squid.corp.redhat.com:3128" \
    --cert=cloudigrade-turnpike-stage.crt --cert-key=cloudigrade-turnpike-stage.key \
    post https://mtls.internal.cloud.stage.redhat.com/api/cloudigrade/internal/api/cloudigrade/v1/syntheticdatarequests/ \
    cloud_type=aws since_days_ago=30 instance_count=30000 \
    run_count_per_instance_mean=10 image_count=1000 image_rhel_chance=0.8
```

- Wait and periodically ask the API until `is_ready` changes from `false` to `true`.
- Use the internal HTTP API to delete the related account.
```
http \
    --proxy="https:http://squid.corp.redhat.com:3128" \
    --cert=cloudigrade-turnpike-stage.crt --cert-key=cloudigrade-turnpike-stage.key \
    delete https://mtls.internal.cloud.stage.redhat.com/api/cloudigrade/internal/api/cloudigrade/v1/accounts/25449/
```
- Wait and periodically check the account API to see if it has been deleted.

## Expected Result

- Account is deleted within a reasonable time.

## Actual Result

- Account was not deleted, and Celery worker logs indicated a kill probably due to OOM.
- Sentry does not know about the OOM because the process killed by the OOM-killer would be the thing notifying Sentry, and now it's dead too soon.

## Additional context

- This may be difficult to reproduce exactly in different environments due to variability in memory pressure. You may need to request even more instances or runs to make the delete worker crash.
- @infinitewarp thinks the problem here is how we are trying to identify which images need to be deleted since we have to look up the relationship between images and the instances being deleted and then also identify which of those images have *no other instances* using them from other cloud accounts. We should consider moving the image-deletion logic into some other process.

**Comment by katherine-black** [comment]
Tagging #1054, as this is sorta related.

**Comment by infinitewarp** [comment]
Since the aforementioned PR merged and deployed, I just make a series of calls to the internal API in stage to delete the straggling cloud accounts. The new code appears to have worked well and quickly, there were no signs of OOMs in the pod logs, the tasks all appear to have completed, and spot-checking a few individual API requests looks good too.

**Comment by paraggit** [comment]
Regression tests on stage environment are all clean with these changes.  ACK to close this issue.
