### ISSUE TITLE
Investigate (and use?) lower TTL for Celery message results

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1158]
## Summary

As a cloudigrade sysop, I want Redis keys to have a reasonable TTL so that we don't waste or exhaust our memory.

See https://ansible.slack.com/archives/C8VGAPJNN/p1649448232796599

It looks like redis by default sets no TTL (see https://redis.io/commands/expire/); so, something in Celery or Kombu probably is setting its own value here. At last check, the Celery docs did not indicate the option to set a TTL when using the Redis broker. This might mean we need to contribute to those projects to expose something?

## Acceptance Criteria

- [ ] Verify

## Assumptions and Questions

-

**Comment by abellotti** [comment]
Not sure TTL is supported for Redis: https://docs.celeryq.dev/projects/kombu/en/stable/reference/kombu.transport.redis.html
