### ISSUE TITLE
Capture houndigrade instance logs

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#1159]
## Summary

As a cloudigrade sysop, I want to have houndigrade stdout/stderr available to me. 

## Acceptance Criteria

- [ ] Verify that we get stdout/stderr output either in cloudwatch or some s3 bucket
  - [ ] And it has a reasonable lifecycle policy. 

## Assumptions and Questions

- Let's consider 90 days for retention/lifecycle/etc.

**Comment by katherine-black** [comment]
Also maybe put the ami name in the inspection json.

**Comment by katherine-black** [comment]
Hey Parag, for this story you should check for a CloudWatch log group created for the ephemeral environment that'll have two log streams in it, one ending in -system and one ending in -inspection.

**Comment by paraggit** [comment]
I have verified that  log stream  ending with '-system' and '-inspection' has created for each ami that has inspected 
 by houndigrade. Following command output is showing that the  log stream has created  successfully, On this observation i am marking this issue as verified and closing this card.
```console 
%> aws logs describe-log-streams --log-group-name houndigrade-ephemeral-ephemeral-79eu2c --query 'logStreams[].logStreamName' --profile smoke
[
    "ami-001bd1d0ff96bf847-inspection",
    "ami-001bd1d0ff96bf847-system",
    "ami-063356dbaf529e4cf-inspection",
    "ami-063356dbaf529e4cf-system"
]
