### ISSUE TITLE
Azure: get list of instances upon cloud account creation

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1205]
## Summary

As a cloudigrade user, I want cloudigrade to know about the instances I am then-currently running in Azure at the time when I register my Azure source (cloud account). 

This is analogous to the "initial describe" we do for AWS accounts. We want to:

- call Azure for the customer's subscription ID
- retrieve a list of currently-running instances
- and store some basic information about those instances.

We think that we should be able to get the "VM size" (e.g. "type" which includes CPU count, memory, etc.) at this time. We should also record a "power on" event for the instance to indicate that we know it is running.

## Acceptance Criteria

- [ ] Verify that for an Azure subscription that has a running instance, cloudigrade learns about and records that instance when the source is defined.
  - [ ] Verify that the recorded instance objects have expected "VM size" (type).
  - [ ] Verify that a new "power on" AzureInstanceEvent (or equivalent) is also created at the time of discovery.
- [ ] Verify an IQE test exists that creates an Azure instance during setup, and verifies that the instance is recorded in cloudigrade after creating the source.

## Assumptions and Questions

- Since we are only getting information at source creation, this means any new Azure instances are running forever! This is okay because a future issue will refine the data and start recording "power off" events. It's also okay because we don't expect actual customers to be engaged yet.
- When we record these instances, we may not know enough information to store a `MachineImage` object. How do we deal with this?
  - According to our current model code, it *should be* okay to create an Instance object with null/none MachineImage attribute. Let's assume this is okay, and use this for now.
- We assume for now that nothing "counts" as RHEL, etc. Treat these as generic unknown uninspected instances/images.
- Since the Lighthouse source flow is already kind of hard to get to, let's assume that that's a good enough gate to this feature. We don't need another specific feature flag for this. We may reevaluate later if actual users start finding it or expressing interest.

**Comment by abellotti** [comment]
Tested with both RHEL and Windows 10 classic VM's as well as RHEL Scale Set VMs:

From the api_machineimage table:

```
Name                |Value    
____________________|_____
id                  |716 
created_at          |2022-09-06 19:12:45.729 -0400
updated_at          |2022-09-06 19:12:45.729 -0400
object_id           |19 
inspection_json     |{"image_reference": {"additional_properties": {}, "id": null, "publisher": "RedHat", "offer": "RHEL", "sku": "82gen2", "version": "latest", "exact_version": "8.2.2022031402", "shared_gallery_image_id": null, "community_gallery_image_id": null}}|
is_encrypted        |false
status              |pending
openshift_detected  |false 
name                |82gen2
content_type_id     |32 
rhel_detected_by_tag|false
architecture        |x64
```

```
Name                |Value
____________________|_____
id                  |717
created_at          |2022-09-08 17:54:31.947 -0400
updated_at          |2022-09-08 17:54:31.947 -0400
object_id           |20 
inspection_json     |{"image_reference": {"additional_properties": {}, "id": null, "publisher": "MicrosoftWindowsDesktop", "offer": "Windows-10", "sku": "win10-21h2-pro-g2", "version": "latest", "exact_version": "19044.1889.220805", "shared_gallery_image_id": null, "community_gallery_image_id": null}}
is_encrypted        |false
status              |pending
openshift_detected  |false
name                |win10-21h2-pro-g2
content_type_id     |32
rhel_detected_by_tag|false
architecture        |x64
```

And vm sizes stashed as part of the api_azureinstanceevents:

```
id|created_at                   |updated_at                   |instance_type  |
--+-----------------------------+-----------------------------+---------------+
10|2022-09-06 19:12:45.755 -0400|2022-09-06 19:12:45.756 -0400|Standard_B1ls  |
11|2022-09-06 19:12:45.772 -0400|2022-09-06 19:12:45.772 -0400|Standard_D2s_v3|
12|2022-09-06 19:12:45.784 -0400|2022-09-06 19:12:45.784 -0400|Standard_D2s_v3|
13|2022-09-08 17:54:31.974 -0400|2022-09-08 17:54:31.974 -0400|Standard_B1s   |
```
