### ISSUE TITLE
Monitor, report, and alert on SQS queue sizes

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1214]
## Summary

As a cloudigrade sysop, I want prometheus and friends to know our SQS queue sizes so that we can monitor and alert on abnormal counts. Even though our Celery task queues have moved to Redis/ElastiCache, we still have (and will continue to have for the foreseeable future) SQS queues for CloudTrail (`*-cloudigrade-cloudtrail-s3`) and houndigrade (`*-cloudigrade-inspections-s3`).

We started an issue for this effort many months ago in https://github.com/cloudigrade/cloudigrade/issues/1062, but we closed the issue when we moved the task queues to Redis/ElastiCache, presumably forgetting that we still had some SQS queues that could cause trouble.

Why are we doing this now? Last week we accidentally discovered that our `*-cloudigrade-cloudtrail-s3` was growing faster than we were reading it, and we had to scramble to address. We should have been notified sooner.

What's the change to cloudigrade? We would add custom entry to the metrics endpoint that simply states the current estimated visible message count for each queue. Consider using an AWS API like this to get `ApproximateNumberOfMessages`:
```
❯ AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_PROFILE=cloudmeter_production aws sqs get-queue-attributes --queue-url https://sqs.us-east-1.amazonaws.com/xxxxxxxxxxxx/xxxxxxxxxxxx --attribute-names All
{
    "Attributes": {
        "QueueArn": "arn:aws:sqs:us-east-1:xxxxxxxxxxxx:xxxxxxxxxxxx",
        "ApproximateNumberOfMessages": "11840",
        "ApproximateNumberOfMessagesNotVisible": "357",
        "ApproximateNumberOfMessagesDelayed": "0",
        "CreatedTimestamp": "1533663435",
        "LastModifiedTimestamp": "1574058975",
        "VisibilityTimeout": "1800",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "DelaySeconds": "0",
        "ReceiveMessageWaitTimeSeconds": "0"
    }
}
```

What's the change to app-interface? We would add new PromQL expressions and alerts to make noise upon counts and rates of change.

## Acceptance Criteria

- [x] Verify the current estimated visible message count for each of our queues is captured and reported to platform Prometheus
- [x] Verify these metrics are visible on our custom Grafana dashboard
  - Stage: https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage
  - Prod: https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod

- [x] Verify an alert fires when the message count hits an appropriate rate or count

## Assumptions and Questions

- We probably want this added to cloudigrade-api's metrics endpoint.
- How often do we ask Amazon for the queue sizes? How do we store those numbers?
  - 15 minute interval as an async task
  - store the results in cache, which means we should do https://github.com/cloudigrade/cloudigrade/issues/1221 first
- How long does `aws sqs get-queue-attributes` take?
  - very rough quick testing suggests this is consistently less than 1 second
- What should be the threshold for firing an alert? Consider starting with these, and adjust as needed:
  - 100 count for `*-cloudigrade-cloudtrail-s3`
  - 10 count for `*-cloudigrade-inspections-s3`
  - ??? for rates of change
- Should we rely solely on the app-interface alert mechanism? Should we also log an error so Sentry notices and makes noise?
  - Brad thinks strongly we should leverage Sentry.
  - Alberto suggests we have some env vars to configure the counts that would result in Sentry alerts.
- What queues do we need to monitor?
  - `{CLOUDIGRADE_ENVIRONMENT}-cloudigrade-cloudtrail-s3` for CloudTrail S3 message arrivals
  - `{CLOUDIGRADE_ENVIRONMENT}-cloudigrade-inspections-s3` for houndigrade results
  - DLQs for those? Yes, let's also monitor these… but let's discuss the desired counts later.

**Comment by infinitewarp** [comment]
New SOPs and Prometheus alerts are here: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44862
> add cloudigrade prometheus alerts and SOPs to check queue lengths

**Comment by infinitewarp** [comment]
I have updated https://github.com/cloudigrade/cloudigrade/wiki/Monitoring#testing-sreapp-interface-alerts with some information about testing SRE/app-interface promql alerts based on my latest experience.

**Comment by abellotti** [comment]
Verification:

- I can query the individual queues, i.e.:

```
https://prometheus.crcp01ue1.devshift.net/graph?g0.expr=cloudigrade_celery_queue_length%7Bnamespace%3D%22cloudigrade-prod%22%2C%20queue_name%3D%22recalculate_concurrent_usage_for_user_id_on_date%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h
```

or the whole lot:

```
https://prometheus.crcp01ue1.devshift.net/graph?g0.expr=cloudigrade_celery_queue_length%7Bnamespace%3D%22cloudigrade-prod%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h
```

These are the new cloudigrade_ metrics names coming from the api.
