### ISSUE TITLE
Document architectural overview

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#122]
As a non-developer, I want to understand the architecture around Doppler so that I can explain the tool's field impact.

## Acceptance Criteria 

- [ ] Verify documentation exists for the overall architecture.
- [ ] Verify documentation includes *general* definition of actors, services, APIs, queues

## Tech assumptions

- This may initially be written by a "core" developer, but this should also be written with the aide of and polished by a better marketing-ish wordsmith. Maybe talk to Dan. :)
- This could be prepared entirely in text, and Dan could turn it into an external visual document with lines and boxes and pictures.
- At a high level, people care about what this "brings to the table" and how this may affect the behavior of other RH teams. In what sense is this going to open up our field teams? Non-Doppler people want to know specifically *what* Doppler will tell them and *how* Doppler tells it so they can know how to make better deals with customers.

**Comment by adberglund** [comment]
Is this a duplicate of #146 ?

**Comment by infinitewarp** [comment]
Yeah, I remember when we wrote up that one, we thought another one existed but couldn't find it at the time. It looks like we were right. Closing!
