### ISSUE TITLE
Resolve current firing DVO issues

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1236]
## Summary

As a cloudigrade sysop, I want no issues to be firing from DVO so that SRE is happy with our deployments.

This is kind of a catch-all and maybe should be split into multiple issues, but since everything here should be handled with various YAML configurations for app-interface and OpenShift, maybe this is more convenient.

- [CLOUDMETER-10](https://issues.redhat.com/browse/CLOUDMETER-10) deployment_validation_operator_latest_tag crcs02ue1
- [CLOUDMETER-11](https://issues.redhat.com/browse/CLOUDMETER-11) deployment_validation_operator_default_service_account crcp01ue1
- [CLOUDMETER-12](https://issues.redhat.com/browse/CLOUDMETER-12) deployment_validation_operator_unset_memory_requirements crcp01ue1
- [CLOUDMETER-14](https://issues.redhat.com/browse/CLOUDMETER-14) deployment_validation_operator_unset_cpu_requirements crcp01ue1
- [CLOUDMETER-15](https://issues.redhat.com/browse/CLOUDMETER-15) deployment_validation_operator_latest_tag crcp01ue1

See also:
- [prod grafana dashboard](https://grafana.app-sre.devshift.net/d/dashdotdb/dash-db?orgId=1&var-datasource=dashdotdb-rds&var-cluster=crcp01ue1&var-namespace=cloudigrade-prod)
- [stage grafana dashboard](https://grafana.app-sre.devshift.net/d/dashdotdb/dash-db?orgId=1&var-datasource=dashdotdb-rds&var-cluster=crcs02ue1&var-namespace=cloudigrade-stage)

## Acceptance Criteria

- [ ] Verify all of the aforementioned alerts are resolved
  - [ ] Answer inline the questions below…

## Assumptions and Questions

- This really means we need to have a conversation with SRE, understand what's going on, and update YAML accordingly.
- Is this a problem with Clowder?
- How often do the DVO checks run? How often are the Grafana dashboards updated?
- https://github.com/cloudigrade/cloudigrade/issues/1232 covers:
  - [CLOUDMETER-9](https://issues.redhat.com/browse/CLOUDMETER-9) deployment_validation_operator_minimum_three_replicas crcs02ue1
  - [CLOUDMETER-13](https://issues.redhat.com/browse/CLOUDMETER-13) deployment_validation_operator_minimum_three_replicas crcp01ue1

**Comment by infinitewarp** [comment]
See also: https://issues.redhat.com/browse/APPSRE-3836?focusedCommentId=20721900&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20721900

**Comment by infinitewarp** [comment]
I've been working through these with Jean-Francois as part of SRE onboarding (https://github.com/cloudigrade/cloudigrade/issues/905 and [APPSRE-3836](https://issues.redhat.com/browse/APPSRE-3836)), and I think we've resolved all but the three-replica DVO alert which we want to handle differently via https://github.com/cloudigrade/cloudigrade/issues/1232 and [RHCLOUD-20060](https://issues.redhat.com/browse/RHCLOUD-20060).

These issues are now resolved and closed:

[CLOUDMETER-10](https://issues.redhat.com/browse/CLOUDMETER-10) deployment_validation_operator_latest_tag crcs02ue1
[CLOUDMETER-11](https://issues.redhat.com/browse/CLOUDMETER-11) deployment_validation_operator_default_service_account crcp01ue1
[CLOUDMETER-12](https://issues.redhat.com/browse/CLOUDMETER-12) deployment_validation_operator_unset_memory_requirements crcp01ue1
[CLOUDMETER-14](https://issues.redhat.com/browse/CLOUDMETER-14) deployment_validation_operator_unset_cpu_requirements crcp01ue1
[CLOUDMETER-15](https://issues.redhat.com/browse/CLOUDMETER-15) deployment_validation_operator_latest_tag crcp01ue1

At the time of this comment, the Grafana dashboards still indicate problems for these and more, but I don't know if, how, or how often that dashboard's data is updated. Maybe it's not accurate and shouldn't be the metric for success here? Let's wait another day or two to see if it changes on a longer schedule.

**Comment by infinitewarp** [comment]
A few hours later, the dashboard data has updated. Now I see only `minimum_three_replicas` failures in prod, and that's what we expect! 🎉 

To answer the questions in the issue description:

- Is this a problem with Clowder?
  - Partly, yes. The `minimum_three_replicas` failures will be handled via https://github.com/cloudigrade/cloudigrade/issues/1232 and [RHCLOUD-20060](https://issues.redhat.com/browse/RHCLOUD-20060).
  - There were several other issues unrelated to Clowder:
    - A CronJob for floorist still existed despite us removing all floorist references months ago. Jean-Francois manually removed that job in OpenShift.
    - Our cloudigrade-metrics deployment was unexpectedly using the "latest" deployment tag. We fixed this in https://github.com/cloudigrade/cloudigrade/pull/1261
    - Several years-old jobs were left behind by SRE's SQL tool. Jean-Francois deleted those jobs ([app-interface/-/merge_requests/44380](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44380)) and opened an issue to update DVO to ignore these SRE SQL jobs in the future ([APPSRE-6091](https://issues.redhat.com/browse/APPSRE-6091)).
- How often do the DVO checks run?
  - Every few hours
- How often are the Grafana dashboards updated?
  - The main panel in this dashboard uses SQL queries. The DVO checks write their results to a database. So, the dashboard represents the latest state as soon as the DVO checks run.

**Comment by abellotti** [comment]
looks good, I also verified the DVO dashboard, and the only ones left are the minimal three which is being handled via https://github.com/cloudigrade/cloudigrade/issues/1232. closing this issue.
