### ISSUE TITLE
Internal API to keep persistent users

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1267]
## Summary

As a cloudigrade developer and sysop, I want to have *some* users remain persistent and be ignored by the usual cleanup processes so that I can more easily make internal and in-development API requests.

Let's add a "permanent" flag to the user model and allow changing its value via an internal API. We already have an internal API that lists users; we could extend its functionality to allow put/post/patch to update the user.

Let's also allow creation and deletion via the same internal user API, but only allow a delete request to complete if the user has no cloud accounts.

## Acceptance Criteria

- [x] Verify the internal user API allows us to create a user
- [x] Verify the internal user API allows us to delete a user if the user has no cloud accounts
- [x] Verify the internal user API does not allow us to delete a user if the user has cloud accounts (400 Bad Request with appropriate message)
- [x] Verify the internal user API allows us to set/unset user permanence
- [x] Verify that when permanent is true, the user object still exists and is usable for API requests after its cloud accounts are deleted
- [x] Verify that when permanent is false, the user object is deleted like it normally has been

## Assumptions and Questions

- This could be a boolean flag on our new user model.
- This would need to be excluded from at least two places: 1) when we auto-delete users upon deleting accounts, and 2) the scheduled job that deletes any "orphaned" users.

**Comment by abellotti** [comment]
With #1295 the following are actual examples via HTTPie:

- Creating a new user with an account_number and org_id

```
$ localhost:8000/internal/api/cloudigrade/v1/users/ account_number=10001 org_id=20001
```

```
HTTP/1.1 201 Created
Allow: GET, POST, HEAD, OPTIONS
Content-Length: 181
Content-Type: application/json
Date: Thu, 04 Aug 2022 14:15:31 GMT
Referrer-Policy: same-origin
Server: WSGIServer/0.2 CPython/3.9.7
X-CLOUDIGRADE-REQUEST-ID: e02afb4e-21d1-4d48-9416-e04b4b44bba8
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "account_number": "10001",
    "date_joined": "2022-08-04T14:15:31.376080Z",
    "id": 15,
    "is_permanent": false,
    "org_id": "20001",
    "username": "10001",
    "uuid": "bd3554cf-8af8-4c97-8334-272094bd1bb2"
}
```

- Updating that user to have the permanent flag set:

```
$ http PUT localhost:8000/internal/api/cloudigrade/v1/users/15/ is_permanent=True
```

```
HTTP/1.1 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Length: 180
Content-Type: application/json
Date: Thu, 04 Aug 2022 14:16:42 GMT
Referrer-Policy: same-origin
Server: WSGIServer/0.2 CPython/3.9.7
X-CLOUDIGRADE-REQUEST-ID: 1bcfd0e1-c590-465d-a8b3-a76d48b422c1
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "account_number": "10001",
    "date_joined": "2022-08-04T14:15:31.376080Z",
    "id": 15,
    "is_permanent": true,
    "org_id": "20001",
    "username": "10001",
    "uuid": "bd3554cf-8af8-4c97-8334-272094bd1bb2"
}
```

- And finally, deleting that user:

```
$ http DELETE localhost:8000/internal/api/cloudigrade/v1/users/15/
```

```
HTTP/1.1 202 Accepted
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Length: 0
Date: Thu, 04 Aug 2022 14:18:31 GMT
Referrer-Policy: same-origin
Server: WSGIServer/0.2 CPython/3.9.7
X-CLOUDIGRADE-REQUEST-ID: 0e0c96fa-2a19-4221-a146-0bc55bea46ea
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
```

```
$ http localhost:8000/internal/api/cloudigrade/v1/users/15/ 
```

```
HTTP/1.1 404 Not Found
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Length: 23
Content-Type: application/json
Date: Thu, 04 Aug 2022 14:19:06 GMT
Referrer-Policy: same-origin
Server: WSGIServer/0.2 CPython/3.9.7
X-CLOUDIGRADE-REQUEST-ID: 6c922689-4bf1-480f-80f5-9d2da4da2d1f
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "detail": "Not found."
}
```

**Comment by infinitewarp** [comment]
Looks good! I also verified that the periodic job `api.tasks.delete_inactive_users` skips `is_permanent` users, but it would be nice to update the original query to ignore them so the logged counts are more meaningful.

```
❯ http localhost:8000/internal/api/cloudigrade/v1/users/3/
HTTP/1.1 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Connection: close
Content-Length: 179
Content-Type: application/json
Date: Thu, 11 Aug 2022 15:53:53 GMT
Referrer-Policy: same-origin
Server: gunicorn
X-CLOUDIGRADE-REQUEST-ID: 91e01941-6ef1-420d-953c-18a920057939
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "account_number": "10001",
    "date_joined": "2022-08-11T15:50:32.861669Z",
    "id": 3,
    "is_permanent": true,
    "org_id": "20001",
    "username": "10001",
    "uuid": "aa4910fc-eb26-4152-bc7f-8eb8559356a2"
}
```

```
>>> from api.tasks import delete_inactive_users
>>> from django.test import override_settings
>>> with override_settings(DELETE_INACTIVE_USERS_MIN_AGE=0):
...     delete_inactive_users()
...
2022-08-11 15:54:34,014 | INFO | 745 | maintenance.py:delete_inactive_users:66 | requestid:None | Found 2 not-superuser Users joined before 2022-08-11 15:54:34.010740+00:00.
2022-08-11 15:54:34,112 | INFO | 745 | maintenance.py:delete_inactive_users:79 | requestid:None | Successfully deleted 0 of 2 users.
```
