### ISSUE TITLE
Review and update SRE alerts

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1302]
## Summary

As an SRE on-call sysop, I want to be alerted to production problems in cloudigrade so that I can resolve it or escalate to the devs and minimize the customer impact.

Now that cloudigrade is officially onboarded with SRE (see https://github.com/cloudigrade/cloudigrade/issues/905#issuecomment-1209795686), we should update the alerts we defined in app-interface to use severity `critical` if we want them to alert the on-call CRC handler via PagerDuty.

- ~stage alerts are defined in [cloudigrade-stage/cloudigrade.prometheusrules.yaml](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/insights-stage/cloudigrade-stage/cloudigrade.prometheusrules.yaml)~
- prod alerts are defined in [cloudigrade-prod/cloudigrade.prometheusrules.yaml](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/insights-prod/cloudigrade-prod/cloudigrade.prometheusrules.yaml)

Their corresponding tests will also need to be updated:

- ~stage alert tests are defined in [cloudigrade-stage/cloudigrade.prometheusrules-test.yaml](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/insights-stage/cloudigrade-stage/cloudigrade.prometheusrules-test.yaml)~
- prod alert tests are defined in [cloudigrade-prod/cloudigrade.prometheusrules-test.yaml](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/insights-prod/cloudigrade-prod/cloudigrade.prometheusrules-test.yaml)

## Acceptance Criteria

- [x] Verify all prod alerts have been updated from `severity: warning` to `severity: critical`
- [x] Find and document an answer to "where do `severity: warning` results go"

## Assumptions and Questions

- Should we do this before or after https://github.com/cloudigrade/cloudigrade/issues/1230?
- Can we see if/where the non-critical alerts are being raised?
  - We currently have all our alerts set with `severity: warning` which does not alert PagerDuty. However, we would like to see what `severity: warning` actually does. Are the checks running? Are the results written anywhere? Where can we see those results?
  - In the future, as we are building new alerts, we could start them at `severity: warning`, monitor the results for a while, adjust numbers appropriately, and then update to `severity: critical`.
- Do we actually want to alert PagerDuty for problems in stage?
  - Probably not because stage is only important to us, not customers.
- How can we verify that setting `severity: critical` works?
  - We don't. We just trust SRE's tooling. @infinitewarp asked about this long ago, and the answer was that we could not directly test this.

**Comment by infinitewarp** [comment]
This work is blocked until I get an answer from SRE to my questions here: https://coreos.slack.com/archives/CCRND57FW/p1661363472151219

**Comment by infinitewarp** [comment]
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/50184 does the following:
* fixes a few typos in old tests
* update all of our `warning` alerts to `high`
* adds several new "extended" alerts (and tests) with `critical` to alert pagerduty if they've been failing for a whole hour (versus existing alerts going to Slack after only 5 minutes)
* slightly updates working on a few of our SOP docs to clarify that things have been failing for an extended period of time

This is a slight change from the original issue definition above, but I think this is better overall. We don't need to (and probably shouldn't) go straight to pagerduty for most of our alerts, or _at all_ for some of them that they can do nothing about. The new "extended" alerts focus only on unexpected pod counts because those are issues likely caused by deeper infra problems that SRE would have to investigate anyway.

The answer to this question:

> where do severity: warning results go

is effectively _nowhere_. The alerting behaviors are defined in `alertmanager-instance-crc-custom.secret.yaml` and `alertmanager-instance.secret.yaml` in multiple places. The yaml in these file define pattern matches against the service, app team, environment, and severity. I believe there is currently nothing defined for `warning` when they occur in `stage` and `prod` envs for `cloudigrade`. We _could_ add handling if we were interested, but I don't think that's necessary now.

**Comment by infinitewarp** [comment]
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/50184 merged a few hours ago, and I think that's the last of the changes on this issue for now.

**Comment by abellotti** [comment]
Verified: no more warnings in https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/insights-prod/cloudigrade-prod/cloudigrade.prometheusrules.yaml

Also, https://github.com/cloudigrade/cloudigrade/issues/1302#issuecomment-1287415025 answers the question of where warnings go.  

This issue is good to go, so I'm closing it.
