### ISSUE TITLE
Resolve remaining DVO errors for IQE smoke pod in stage

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1318]
## Summary

As a cloudigrade sysop, I was DVO validation to ignore specific errors related to IQE tests because I want to be aware of when actual new errors occur. Currently, the IQE smoke test pod in stage triggers DVO `deployment_validation_operator_no_liveness_probe` and `deployment_validation_operator_no_readiness_probe`, but the pod is short-lived and may not need probes. We want to annotate the pod/deployment/job somehow to ignore these errors.

See also https://github.com/cloudigrade/cloudigrade/issues/1236 and https://github.com/cloudigrade/cloudigrade/issues/1232#issuecomment-1219535311 and this discussion in Slack: https://coreos.slack.com/archives/C023YSA47A4/p1659996991032009

## Acceptance Criteria

- [x] Verify [the stage DVO grafana board](https://grafana.app-sre.devshift.net/d/dashdotdb/dash-db?orgId=1&var-datasource=dashdotdb-rds&var-cluster=crcs02ue1&var-namespace=cloudigrade-stage) no longer complains about the IQE smoke test pod

## Assumptions and Questions

- @abellotti looked into this briefly after the aforementioned [RHCLOUD-21026](https://issues.redhat.com/browse/RHCLOUD-21026) closed, but it looked like more work was required.
- https://github.com/RedHatInsights/clowder/pull/691 merged on 2022-09-07, but on 2022-09-22 Pete said [it's not in prod](https://coreos.slack.com/archives/C023YSA47A4/p1663868627770009?thread_ts=1659996991.032009&cid=C023YSA47A4).

**Comment by abellotti** [comment]
Interesting the following seem ok now:

- https://grafana.app-sre.devshift.net/d/dashdotdb/dash-db?orgId=1&var-datasource=dashdotdb-stage-rds&var-cluster=crcs01ue1&var-namespace=cloudigrade-stage
- https://grafana.app-sre.devshift.net/d/dashdotdb/dash-db?orgId=1&var-datasource=dashdotdb-rds&var-cluster=crcp01ue1&var-namespace=cloudigrade-prod

**Comment by infinitewarp** [comment]
Unfortunately, [Tyler confirmed in Slack](https://coreos.slack.com/archives/CCRND57FW/p1664400863866869?thread_ts=1664396467.230659&cid=CCRND57FW) that the correct dashboard to check is this one:
- https://grafana.app-sre.devshift.net/d/dashdotdb/dash-db?orgId=1&var-datasource=dashdotdb-rds&var-cluster=crcs02ue1&var-namespace=cloudigrade-stage

which still shows the IQE pod failures.

**Comment by abellotti** [comment]
🎉 

![image](https://user-images.githubusercontent.com/5797328/193372408-4a74b838-7e66-4bce-9a9c-debfa6c0ae32.png)

The investigations/discussions leading up to the above:
- https://ansible.slack.com/archives/C8VGAPJNN/p1664566165361559
- https://coreos.slack.com/archives/CCRND57FW/p1664567906020989

**Comment by infinitewarp** [comment]
Looking great! Thanks!
