### ISSUE TITLE
Update SonarQube integration to use Java 11 container

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1324]
## Summary

As a cloudigrade developer, I want sonarqube to keep working with my PR checks, but changes are required from our platform. Per a recent email:

> TLDR; If you are using app-interface to run SonarQube scans using the corporate instance you need to make a change before September 1st. The following pull request provides the example changes you need to make: https://github.com/RedHatInsights/marketplace-processor/pull/106.

## Acceptance Criteria

- [ ] Verify SonarQube PR checks are still running following this change

## Assumptions and Questions

-

**Comment by abellotti** [comment]
from the ci.int build output:

```
11:55:25 JAVA_HOME=/usr/lib/jvm/java-11
11:55:25 openjdk version "11.0.16" 2022-07-19 LTS
11:55:25 OpenJDK Runtime Environment (Red_Hat-11.0.16.0.8-1.el7_9) (build 11.0.16+8-LTS)
11:55:25 OpenJDK 64-Bit Server VM (Red_Hat-11.0.16.0.8-1.el7_9) (build 11.0.16+8-LTS, mixed mode, sharing)
```

and:

```
11:55:59 INFO: ANALYSIS SUCCESSFUL, you can browse https://sonarqube.corp.redhat.com/dashboard?id=console.redhat.com%3Acloudigrade&branch=1205-initial-azure-vm-discovery
11:55:59 INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
11:55:59 INFO: More about the report processing at https://sonarqube.corp.redhat.com/api/ce/task?id=AYLvd3MjFhdZ1RC3xs9w
11:55:59 INFO: Analysis total time: 27.502 s
11:55:59 INFO: ------------------------------------------------------------------------
11:55:59 INFO: EXECUTION SUCCESS
```

and the dashboard still being updated:

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/5797328/187485064-59e1d8fc-8bfd-4288-9e47-2cb507f5215c.png">

This is good, thanks @infinitewarp for updating this 👍
