### ISSUE TITLE
Azure sources are not completing to "Available"

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1329]
## Summary

As an Azure user (in stage), I want my source to be "available" so that I know it's working and related services can proceed.

When cloudigrade gets the creation messages from sources, cloudigrade's process to enable the CloudAccount should reach out to Azure to verify we have access to the customer's subscription ID, and upon success, cloudigrade should send a message to sources to acknowledge that the source is available. Alternatively, if cloudigrade does not have access to the customer's Azure subscription ID, cloudigrade should send an "unavailable" message (with an error message) to sources. Something in this sequence appears to be failing because sources continues to show the "Unknown" status.

See this (unfortunately somewhat meandering) Slack thread that spawned this issue: https://coreos.slack.com/archives/C0246P60U8H/p1659099577038539

## Steps to Reproduce

What we're trying to do here is create an "Azure" source type "RHEL management" application type relationship for cloudigrade.

If we were to do this through the web UI:

1. go to https://console.stage.redhat.com/settings/sources
1. click "Add source"
1. choose Azure, next
1. enter a unique memorable name
1. choose RHEL management", next
1. ???

We used to be able to do this completely through the UI, but this no longer appears to be possible.

TODO document how we may be able to do this via the sources HTTP API.

## Expected Result

- After a minute or so, the source's status shows "Available" or "Unavailable" with an appropriate error.

## Actual Result

- The source's status remains "Unknown".

## Additional context

- If this all seems to work in an ephemeral deployment, **check the stage configs and vault**.
- We would like to understand better the relationship between cloudigrade, sources, and teamnado.
  - @infinitewarp thinks it goes like this:
    - customer creates source objects
    - sources notifies kafka about object creation
    - cloudigrade receives create message
    - cloudigrade does handshakes
    - cloudigrade sends message to sources with appropriate status
    - sources updates its object
    - sources emits message to kafka regarding the update
    - teamnado service receives update message and does something????
    - how and why???
- The UI in stage has changed recently for creating sources. For testing and verifying this issue, we must exclusively use the sources API for creating the various objects.
- The problem here is not that the UI is weird. The problem is that once the sources objects are created, cloudigrade seems never to send back an available/unavailable message to sources.
- So, we suspect something has gone wrong in one of these steps:
  - sources-api not sending message to cloudigrade
  - cloudigrade not correctly handling that message
  - cloudigrade async task not running
  - cloudigrade failing unexpectedly when talking to Azure
  - cloudigrade failing unexpectedly when trying to check that it can see the customer's subscription
  - cloudigrade failing to send the message to sources
  - sources-api failing to handle cloudigrade's message

**Comment by infinitewarp** [comment]
We also discussed whether or not this is a good opportunity and time to write new IQE integration tests for Azure source creation, but since the UI is clearly not ready for this, let's think about this but **not require** the tests for this specific issue.

**Comment by abellotti** [comment]
Script to do the source creation, update your sources auth as needed.

```
export SOURCE_NAME="<<unique_source_name_for_this_lighthouse_registration>>"
export AZURE_MANAGED_TENANT_SUBSCRIPTION="<<subscription for managed tenant>>"

cat - <<!END! | http https://cloud.stage.redhat.com/api/sources/v3.1/bulk_create "x-rh-sources-psk:  <<SOURCES_PSK>>" "x-rh-sources-account-number: <<SOURCES_ACCOUNT_NUMBER>>"
{
  "sources":[
    {
      "name":"${SOURCE_NAME}",
      "source_type_name":"azure"
    }
  ],
  "authentications":[
    {
      "resource_type":"application",
      "resource_name":"cloud-meter",
      "username":"${AZURE_MANAGED_TENANT_SUBSCRIPTION_ID}",
      "authtype":"lighthouse_subscription_id"
    }
  ],
  "applications":[
    {
      "source_name":"${SOURCE_NAME}",
      "application_type_name":"cloud-meter"
    }
   ]
}
!END!

```

**Comment by tdarby** [comment]
For addtional context, teamnado receives the update message within our autoreg listener,  we then enable value added services for the customer that were advertised as part of the source creation - gold images, subscription watch, auto registration trust.

**Comment by abellotti** [comment]
Ok, I've kicked this tire a bit and things seem to work well when all ducks are in order.

In trying to reproduce this, my environment consisted of the `Cloudigrade - Stage` tenant (the service provider) with the `Cloudigrade RH Directory1` tenant as the managed tenant.

First step in the process is to register managed tenant `Cloudigrade RH Directory1` with `Cloudigrade - Stage` via lighthouse.

This is done by hitting the following URL while being logged into the managed tenant `Cloudigrade RH Directory1` on portal.azure.com:


- https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fcloudigrade-stage-azure-offer-cloudigrade-stage.apps.crcs02ue1.urby.p1.openshiftapps.com%2Fapi%2Fcloudigrade%2Fv2%2Fazure-offer-template%2F

After going through the Custom deployment review and create, `Cloudigrade RH Directory` will be registered as a managed tenant (customer) to `Cloudigrade - Stage`, from the Service Providers page on the managed tenant, you can see the properly delegated cloudigrade-stage in addition to cloudigrade-ephemeral where we've been doing the developement.

![image](https://user-images.githubusercontent.com/5797328/190631184-bb27eca6-dfb2-4dac-af34-99ebfe381704.png)


Next step is to create the source on stage for that managed tenant, with `AUTH` reflecting the username:password of the stage account that has a source administrative role:


```
export SOURCE_NAME="lighthouse-rh-dir1"
export AZURE_SUBSCRIPTION_ID_RH_DIR1="c2b810d4-e83c-4df5-a728-f1301dd78561"

cat - <<!END! | http \
    --auth "${AUTH}" \
    --proxy="https:http://squid.corp.redhat.com:3128" \
    POST "https://cloud.stage.redhat.com/api/sources/v3.1/bulk_create"
{
  "sources":[
    {
      "name":"${SOURCE_NAME}",
      "source_type_name":"azure"
    }
  ],
  "authentications":[
    {
      "resource_type":"application",
      "resource_name":"cloud-meter",
      "username":"${AZURE_SUBSCRIPTION_ID_RH_DIR1}",
      "authtype":"lighthouse_subscription_id"
    }
  ],
  "applications":[
    {
      "source_name":"${SOURCE_NAME}",
      "application_type_name":"cloud-meter"
    }
   ]
}
!END!
```

This gave us the following response:

```
{
    "applications": [
        {
            "application_type_id": "3",
            "created_at": "2022-09-15T15:56:18Z",
            "id": "209341",
            "source_id": "238675",
            "updated_at": "2022-09-15T15:56:18Z"
        }
    ],
    "authentications": [
        {
            "authtype": "lighthouse_subscription_id",
            "id": "205365",
            "resource_id": "209341",
            "resource_type": "Application",
            "username": "c2b810d4-e83c-4df5-a728-f1301dd78561"
        }
    ],
    "endpoints": [],
    "sources": [
        {
            "app_creation_workflow": "manual_configuration",
            "availability_status": "in_progress",
            "created_at": "2022-09-15T15:56:18Z",
            "id": "238675",
            "name": "lighthouse-rh-dir1",
            "source_type_id": "3",
            "uid": "174f06d8-1300-45c5-a8f2-3b3b5f2105bd",
            "updated_at": "2022-09-15T15:56:18Z"
        }
    ]
}
```

Where you can see the `availability_status` being `in_progress`

Getting the stage accounts from cloudigrade for that source id 238675

GET https://mtls.internal.cloud.stage.redhat.com/api/cloudigrade/internal/api/cloudigrade/v1/accounts/

```

{
  "meta": {
    "count": 6
  },
  "links": {
    "first": "/internal/api/cloudigrade/v1/accounts/?limit=10&offset=0",
    "next": null,
    "previous": null,
    "last": "/internal/api/cloudigrade/v1/accounts/?limit=10&offset=0"
  },
  "data": [
    ...
    {
      "created_at": "2022-09-15T15:56:22.162223Z",
      "updated_at": "2022-09-15T15:56:22.165870Z",
      "user_id": 6575,
      "content_object": {
        "azure_cloud_account_id": 1549,
        "subscription_id": "c2b810d4-e83c-4df5-a728-f1301dd78561",
        "created_at": "2022-09-15T15:56:22.156860Z",
        "updated_at": "2022-09-15T15:56:22.156882Z"
      },
      "cloud_type": "azure",
      "is_enabled": true,
      "platform_authentication_id": 205365,
      "platform_application_id": 209341,
      "platform_application_is_paused": false,
      "platform_source_id": 238675
    }
  ]
}
```

Fetching that source from stage again shows the completed handshake, so cloudigrade verifying the managed tenant subscription is valid for cloudigrade-stage  (what the lighthouse registration would establish), then sending the platform.sources.status kafka message, with the resource_type of `Application` and application_id of `209341` for the above example and availability_status as `available`.

GET /api/sources/v3.1/sources/238675

```
{
    "data": [
        {
            "app_creation_workflow": "manual_configuration",
            "availability_status": "available",
            "created_at": "2022-09-15T15:56:18Z",
            "id": "238675",
            "last_available_at": "2022-09-15T15:56:22Z",
            "last_checked_at": "2022-09-15T15:56:22Z",
            "name": "lighthouse-rh-dir1",
            "source_type_id": "3",
            "uid": "174f06d8-1300-45c5-a8f2-3b3b5f2105bd",
            "updated_at": "2022-09-15T15:56:22Z"
        }
    ],
    "links": {
        "first": "/api/sources/v3.1/sources?limit=100&offset=0",
        "last": "/api/sources/v3.1/sources?limit=100&offset=100"
    },
    "meta": {
        "count": 1,
        "limit": 100,
        "offset": 0
    }
}
```

Now seeing the `availability_status` as `available`

**Comment by abellotti** [comment]
Short of general Kafka issues which would result in more severe system problems I suspect the issue at hand is that the lighthouse registration may not have successfully completed.

For reference see: https://github.com/cloudigrade/cloudigrade/issues/1243

specifically https://github.com/cloudigrade/cloudigrade/issues/1243#issuecomment-1211229663, after a successful lighthouse registration, an easy way to verify all ducks are in order is to use the Azure CLI and show that both ManagedService definition and assignment are defined.

First do an az login and set your account to the managed tenant, i.e. `Cloudigrade RH Directory1` in the above case:

```
$ az account list --output table
$ az account set --subscription "<<subscription_id_of_managed_tenant>>"
```

Then run the following commands and verify as the the linked issue comment:

```
$ az managedservices definition list
$ az managedservices assignment list
```

**Comment by abellotti** [comment]
Hi @tdarby with all ducks in order, the source gets properly updated to `available`, is your team still seeing the issue ?   Maybe some of the write ups above can shed some light (especially pertaining to lighthouse registration), Thanks.

**Comment by abellotti** [comment]
Probably affected by the Sources UI bug mentioned here: https://issues.redhat.com/browse/RHCLOUD-21337

**Comment by infinitewarp** [comment]
…and see also this recent Slack discussion where we discovered that it's likely the aforementioned sources UI bug: https://coreos.slack.com/archives/C0246P60U8H/p1663859125991459

**Comment by infinitewarp** [comment]
Since it looks like there are no changes for us and our part of the equation is working as expected, I'm closing this issue!

**Comment by tdarby** [comment]
Thanks for the follow up Alberto. Unfortunately, the UI has been reverted,
and we've been trying to get it reinstated
<https://github.com/RedHatInsights/sources-ui/pull/954> so that we can test
this out.  We'll reach out when we know more

-Tramaine
