### ISSUE TITLE
List/retrieve instances via REST

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#133]
As an end user, I want to get my instances via REST so that I can see them in my web browser client.

## Acceptance Criteria 

- [x] Verify you can retrieve a single instance by id via http
- [x] Verify you can list all instances via http
- [x] Verify the list of instances is paginated
- [x] Verify user can only access instances that belong to accounts tied to that user ("who this user is" is based on the auth header)
- [x] Verify super user can view *all* instances.
- [x] Verify super user can filter instances to particular users. (e.g. query string param to indicate something like `user_id=foo`)
- [x] Verify you *cannot* create, edit, or delete an instance via http (post/put/patch/delete)
- [x] Verify endpoint is `/api/v1/instance/{id}`

## Assumptions and Questions

- Assumes we have implemented the user-account relationship (#161)
- This story doesn't have an explicit user-facing UI piece because we currently have no UI wireframes defined for viewing/listing events.

**Comment by infinitewarp** [comment]
If you want to create some dummy instance data in your local cloudigrade, you can use `make oc-user` to create a superuser and use its credentials to get into [your local django admin](http://cloudigrade-myproject.127.0.0.1.nip.io/admin/) where you can manually create whatever objects you need.

**Comment by kholdaway** [comment]
Demo --> https://asciinema.org/a/NsXQil5gg2apKsMIhb5Jwo5Y4

**Comment by infinitewarp** [comment]
@kholdaway or @abaiken: would you kindly put your `demo.sh` in a gist and link it here?

**Comment by kholdaway** [comment]
https://gist.github.com/kholdaway/bd27824e3a7c95c5abf2242a66f10987
