### ISSUE TITLE
Add `aws_rds_free_storage_space_average` to Grafana and alerts

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1333]
## Summary

As a cloudigrade sysop, I want to know when cloudigrade's DB is running out of disk space so that I can clean things up or add space before it crashes. The platform already captures `aws_rds_free_storage_space_average` in Prometheus, and we can use that to power a Grafana dashboard and AppSRE alerts.

## Acceptance Criteria

- [x] Verify a panel in our Grafana dashboard shows `aws_rds_free_storage_space_average` data.
- [x] Verify new alerts are configured in app-interface for this metric and out prod database

## Assumptions and Questions

- **This issue assumes that it's possible (and reasonable) to integrate our Grafana instances and alerting configs with prometheus.app-sre-prod-01.devshift.net. If it's revealed that these systems do not normally talk to each other, please regroup with the team to discuss. Maybe we'll just save a link/bookmark somewhere to a saved query.** 
- See also https://github.com/cloudigrade/cloudigrade/wiki/Monitoring
- Stage: https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage
- Prod: https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod
- What kind of alerts?
  - message to us in slack
  - pagerduty when very close to depleted
  - Based on rates? Current remaining? A combination to project when storage will be depleted?
- Where is the data?
  - https://prometheus.app-sre-prod-01.devshift.net/graph
  - `aws_rds_free_storage_space_average{job=~"cloudwatch-exporter.*",dbinstance_identifier="cloudigrade-prod"}`

**Comment by abellotti** [comment]
App-SRE Prometheus:
- Stage:   https://prometheus.app-sre-stage-01.devshift.net/graph?g0.expr=aws_rds_free_storage_space_average%7B%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h
- Prod: https://prometheus.app-sre-prod-01.devshift.net/graph?g0.expr=aws_rds_free_storage_space_average%7B%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h

**Comment by abellotti** [comment]
Related MRs/PRs:
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/49360

**Comment by infinitewarp** [comment]
Looking good! I'm glad to have this new data available. Thanks, Alberto! 🎉
