### ISSUE TITLE
Research: Can we connect to an Azure customer at a broader level?

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1346]
## Summary

Currently, cloudigrade's implementation for talking with an Azure customer's data means using Lighthouse to establish trust into exactly one of their subscriptions in exactly one region.

- Is it possible to gain access at a broader level?
- Can we get access to one subscription in multiple region at once?
  - Currently, when the customer clicks the link to accept our Lighthouse offer, they have an option to choose a region. What effect does this have? Does that limit what regions cloudigrade's service provider can access in the customer's tenant? Can we actually see into all regions even though only one is selected?
- Can we get access to multiple subscriptions at once?
- Can we get access to their entire tenant/directory at once?

## Expected Output

- Hold a meeting and share your research with the team.
- Jupyter Notebook or other Python script to demonstrate.
- Or if it's super easy, go ahead and build a branch on cloudigrade.

## Timebox

- 1 week

**Comment by BrittRH** [comment]
# Issue-1346 Can we connect to an Azure customer at a broader level?

## Research

1. Is it possible to gain access at a broader level?
   1. No, the best access we can get to is at the subscription level where we can see all resources the customer has within that particular subscription. We will need to keep in mind that customers do have the ability to limit our access to resource groups **within** a particular subscription.
2. Can we get access to one subscription in multiple region at once?
   1. (ANSWER) Subscriptions in Azure are regionless. Each subscription can have resources within multiple different regions, but you can always see the various resources within a subscription regardless of what region they are in. 
   2. (QUESTION) Currently, when the customer clicks the link to accept our Lighthouse offer, they have an option to choose a region. What effect does this have? Does that limit what regions cloudigrade's service provider can access in the customer's tenant? Can we actually see into all regions even though only one is selected?
      1. (ANSWER) When accepting our Service Provider offer, the customer is choosing where the resource itself is located. This does not have an impact on what resources cloudigrade can see OR limit the access to subscriptions from the customer perspective. For example, creating the Service Provider offer (ie accepting cloudigrade lighthouse offer) in South Africa North does NOT prevent cloudigrade from seeing ALL resources listed in the Dir 2 directory.
3. Can we get access to multiple subscriptions at once?
   1. (ANSWER)
4. Can we get access to their entire tenant/directory at once?
   1. (ANSWER)

**Comment by infinitewarp** [comment]
Thanks for the summary notes. For better or worse, this confirms our earlier expectations. Since there are no code changes to prototype, I'll just close this issue based on these comments.
