### ISSUE TITLE
Investigate "high metric's cardinality causes prometheus disk pressure for cloudigrade-prod"

### ISSUE THREAD

**Issue by gtanzillo** [cloudigrade/cloudigrade#1349]
## Summary

Prometheus on crcp01ue1 show very high cardinality for metrics in `celery_task_runtime_bucket{namespace="cloudigrade-prod"}`

Please consider reducing cardinality. Specifically, the number of buckets (le) seems to be the default set. Maybe the buckets can be adapted to your needs while reducing them.
The following issue was opened in Jira by someone on the AppSRE team.

https://issues.redhat.com/browse/CLOUDMETER-17
 
Possible solutions:
- Reduce the number of histogram buckets, but that only solves part of this cardinality problem.
- Change how the metrics are exported so that we are not adding extra dimensions for instance, hostname, and pod. (Does this make sense?) This would significantly reduce cardinality.
- Shut down the [cloudigrade-metrics](https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/cloudigrade-prod/deployments/cloudigrade-metrics) deployments if we don't actually need this data.

Whoever picks this up needs to evaluate the above options. Which has the greatest benefit? Please discuss with the team!

## Steps to Reproduce

See details in [jira ticket](https://issues.redhat.com/browse/CLOUDMETER-17)

## Assumptions and Questions

- https://github.com/danihodovic/celery-exporter#metrics has a list of metrics and their types that we are exporting.
  - Is there a way to eliminate some of them?
- Do we even need to export these metrics?
  - We thought we would be using celery-exporter to get queue lengths and other runtime metrics that would be useful for diagnosing problems. Unfortunately, celery-exporter did not have working task counts at the time of integration, and task counts was most important of all metrics for us at the time. At last check, celery-exporter still does not correctly present task counts.
  - Meanwhile, we implemented our own task count export elsewhere and are using that to power the grafana dashboard (https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod scroll down to "Task and message queues").
  - If we do not see a need for the [all of these metrics](https://github.com/danihodovic/celery-exporter#metrics), perhaps we just shut down the deployments and ask SRE to delete the junk data?
- Try building and using the latest version of celery-exporter. Does the latest version even work for us without major changes?

**Comment by abellotti** [comment]
For the celery-exporter that we use, different histogram buckets other than the default can be specified for the celery_task_runtime https://github.com/danihodovic/celery-exporter/blob/master/src/exporter.py#L97 if that's what's biting us.

**Comment by abellotti** [comment]
Built an updated celery-exporter-container, based on ubi-minimal:8.6-941 and picked up the latest 0.4.1 tag  of celery-exporter.

The container security is improved:

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/5797328/194275108-344c2f3c-8091-47dd-89aa-2738dd592d48.png">

compared to the currently deployed one:

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/5797328/194275476-a3e0d061-b12a-4f8c-ad20-033e98f54af0.png">

While the 0.4.1 build of celery-exporter does introduce the `celery_queue_length` that we needed for the grafana dashboard as shown here:

```
# HELP celery_queue_length The number of message in broker queue.
# TYPE celery_queue_length gauge
celery_queue_length{queue_name="create_from_sources_kafka_message"} 0.0
celery_queue_length{queue_name="delete_inactive_users"} 0.0
celery_queue_length{queue_name="repopulate_azure_instance_mapping"} 0.0
celery_queue_length{queue_name="delete_from_sources_kafka_message"} 0.0
celery_queue_length{queue_name="synthesize_instance_events"} 0.0
celery_queue_length{queue_name="delete_cloud_accounts_not_in_sources"} 0.0
celery_queue_length{queue_name="persist_inspection_cluster_results_task"} 0.0
celery_queue_length{queue_name="notify_application_availability_task"} 0.0
celery_queue_length{queue_name="synthesize_user"} 0.0
celery_queue_length{queue_name="synthesize_concurrent_usage"} 0.0
celery_queue_length{queue_name="recalculate_runs_for_instance_id"} 0.0
celery_queue_length{queue_name="synthesize_instances"} 0.0
celery_queue_length{queue_name="delete_orphaned_cloud_accounts"} 0.0
celery_queue_length{queue_name="check_azure_subscription_and_create_cloud_account"} 0.0
celery_queue_length{queue_name="configure_customer_aws_and_create_cloud_account"} 0.0
celery_queue_length{queue_name="repopulate_ec2_instance_mapping"} 0.0
celery_queue_length{queue_name="unpause_from_sources_kafka_message"} 0.0
celery_queue_length{queue_name="migrate_account_numbers_to_org_ids"} 0.0
celery_queue_length{queue_name="check_and_cache_sqs_queues_lengths"} 0.0
celery_queue_length{queue_name="synthesize_cloud_accounts"} 0.0
celery_queue_length{queue_name="initial_azure_vm_discovery"} 0.0
celery_queue_length{queue_name="delete_expired_synthetic_data"} 0.0
celery_queue_length{queue_name="analyze_log"} 0.0
celery_queue_length{queue_name="delete_snapshot"} 0.0
celery_queue_length{queue_name="launch_inspection_instance"} 0.0
celery_queue_length{queue_name="recalculate_concurrent_usage_for_user_id"} 0.0
celery_queue_length{queue_name="synthesize_runs_and_usage"} 0.0
celery_queue_length{queue_name="recalculate_runs_for_cloud_account_id"} 0.0
celery_queue_length{queue_name="celery"} 0.0
celery_queue_length{queue_name="initial_aws_describe_instances"} 0.0
celery_queue_length{queue_name="enable_account"} 0.0
celery_queue_length{queue_name="copy_ami_to_customer_account"} 0.0
celery_queue_length{queue_name="delete_cloud_account"} 0.0
celery_queue_length{queue_name="recalculate_concurrent_usage_for_user_id_on_date"} 0.0
celery_queue_length{queue_name="recalculate_runs_for_all_cloud_accounts"} 0.0
celery_queue_length{queue_name="inspect_pending_images"} 0.0
celery_queue_length{queue_name="recalculate_concurrent_usage_for_all_users"} 0.0
celery_queue_length{queue_name="synthesize_images"} 0.0
celery_queue_length{queue_name="pause_from_sources_kafka_message"} 0.0
celery_queue_length{queue_name="remove_snapshot_ownership"} 0.0
celery_queue_length{queue_name="calculate_max_concurrent_usage"} 0.0
celery_queue_length{queue_name="update_from_sources_kafka_message"} 0.0
celery_queue_length{queue_name="copy_ami_snapshot"} 0.0
celery_queue_length{queue_name="fix_problematic_runs"} 0.0
```

Queueing tasks does not increase that metrics as we do with our internal metrics equivalent of cloudigrade_celery_queue_length.

i.e.

```
from api.clouds.aws.tasks.cloudtrail import analyze_log
[analyze_log.delay() for _ in range(64)]
```

we always get a 0.0:

```
celery_queue_length{queue_name="analyze_log"} 0.0
```

as compared to our own:

```
cloudigrade_celery_queue_length{queue_name="analyze_log"} 46.0
```

**Comment by abellotti** [comment]
Relevant PRs:
- [ ] https://github.com/cloudigrade/cloudigrade/pull/1357

**Comment by infinitewarp** [comment]
I [confirmed in the prod prometheus instance](https://prometheus.crcp01ue1.devshift.net/graph?g0.expr=celery_task_runtime_bucket{namespace%3D%22cloudigrade-prod%22}) that many of our celery metrics stopped being reported yesterday when these changes merged.

![Screenshot 2022-10-07 at 10-28-53 Prometheus Time Series Collection and Processing Server-nq8](https://user-images.githubusercontent.com/1472326/194578216-e106c294-cf05-43b3-a1bd-4ca207923d10.png)

Rest in peace, `celery-exporter`. 🥀
