### ISSUE TITLE
Upgrade RDS to latest minor version

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1350]
## Summary

As a cloudigrade sysop, I want cloudigrade running the latest supported minor version of postgresql so that I have the latest bug, security, and performance fixes.

Why are we doing this? SRE recently deprecated the `auto_minor_version_upgrade` parameter, and it looks like that means we have to apply upgrades manually. See SRE's [Deprecation notice for RDS databases using auto_minor_version_upgrade defaults parameter](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/deprecation/deprecate-rds-auto-minor-version-upgrade.md).

At the time of writing...
```
# production DB
gabi "select version()" | jq -r '.[1][0]'
PostgreSQL 13.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit

# current available 13.x versions in AWS
aws rds describe-db-engine-versions --engine postgres | \
  jq -r '.DBEngineVersions[] | .EngineVersion' | \
  grep '^13\.' | sort -rn
13.7
13.6
13.5
13.4
13.3
```

## Acceptance Criteria

- [x] Verify we have a reminder on the calendar to check on this monthly.
- [x] Verify app-interface has been updated with new version
  - [x] Include a link to the MR(s) in the comments below
- [x] Verify the new version is applied by repeating the `gabi` command above.

## Assumptions and Questions

- How do I upgrade my database without auto_minor_version_upgrade: Please refer to [RDS minor version upgrades doc](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/README.md#rds-minor-version-upgrades)
- [Release calendar for Amazon RDS for PostgreSQL](https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/Welcome.html)
- Let's set a calendar reminder to check version and update if necessary. We can piggy-back on the Gabi reminder. Please link to this issue and/or include the commands to run.

**Comment by abellotti** [comment]
As of today:

```
$ get_db_version.sh stage
PostgreSQL version of stage DB:
PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit
```

```
$ get_db_version.sh prod
PostgreSQL version of prod DB:
PostgreSQL 13.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit
```

```
$ get_rds_versions.sh 13
AWS RDS Minor versions for version 13:
13.7 13.6 13.5 13.4 13.3
```

Looks like we only need to update the minor version for prod.

**Comment by abellotti** [comment]
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/50953

**Comment by abellotti** [comment]
For completion, I've also checked the latest Ephemeral deployment DB for us and got:

```
PostgreSQL 13.7 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
```

**Comment by abellotti** [comment]
Where the configurations are:

- Ephemeral: https://github.com/cloudigrade/cloudigrade/blob/master/deployment/clowdapp.yaml#L20
- Stage: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/cloudigrade/namespaces/stage-cloudigrade-stage.yml#L87
- Prod: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/cloudigrade/namespaces/cloudigrade-prod.yml#L81

For trying out a new PostgreSQL version, the progression would be to try on Ephemeral first, if all stars align well, then Stage, and finally Prod.

**Comment by abellotti** [comment]
As far as Ephemeral, the minor version is fixed, we can only specify the major, see discussion here: https://coreos.slack.com/archives/C022YV4E0NA/p1667420485408689

**Comment by infinitewarp** [comment]
Also, I updated our monthly calendar reminder about gabi to also remind us about RDS versions.

**Comment by abellotti** [comment]
Schedule kicked in:

```
$ get_db_version.sh prod
PostgreSQL version of prod DB:
PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit
```

**Comment by infinitewarp** [comment]
Thanks for the quick check! Looks like this is all done. 👍
