### ISSUE TITLE
Identify RHEL in Azure (crawl phase)

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1382]
## Summary

As a cloudigrade user, I want my Azure RHEL VMs to be identified as RHEL and to contribute to my daily concurrent usage report so that I have accurate reporting. This means cloudigrade needs to identify RHEL, track that information in its models, and use that information to contribute values to the concurrent usage API.

For this issue, "identify RHEL" should be defined as "the VM has a specific tag". We're not doing filesystem inspections yet.

## Acceptance Criteria

- [ ] Verify that an Azure VM with a tag named `cloudigrade-rhel-present` is identified as RHEL in our models for its image.
  - [ ] Verify this VM's activity contributes to the concurrent usage API results.
- [ ] Verify that an Azure VM without a tag named `cloudigrade-rhel-present` is **not** identified as RHEL in our models for its image.
  - [ ] Verify this VM's activity does **not** contribute to the concurrent usage API results.
- [ ] IQE integration tests exist for asserting RHEL detection based on the presence of tags.

## Assumptions and Questions

- For now, we only care about tags or other easily accessed metadata.
  - Should we identify a system as RHEL if Azure's metadata says it is RHEL?
  - Although it's interesting to know, the OS identification alone isn't as useful for us because cloudigrade's core use case focuses on the customer's direct relationship with Red Hat and their subscription use. It's not enough to know the operating system; we also need to know the relationship.
  - So, for this issue and for now, let's ignore Azure's OS identification and rely only on the tag.
- In the image metadata, there is also a flag that indicates if it's from the marketplace. Let's not worry about this for now, but that could be very useful in the next "walk" phase of this implementation.
- Be sure that we remove the production check in `initial_azure_vm_discovery`.
- Future issue will include investigation and next "walk" phase of actual image inspection. Maybe.
- The tag we're looking for is `cloudigrade-rhel-present`.
- As a reminder, a future issue will gather and record more details about the images themselves.

**Comment by abellotti** [comment]
PRs:
- https://github.com/cloudigrade/cloudigrade/pull/1398
- https://github.com/cloudigrade/cloudigrade/pull/1400
