### ISSUE TITLE
Research accessing internals of running AMI

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#14]
As a Cloudigrade user, I want to be able to access the internals of a running AMI so I can figure out if any services I care about are running in it.

AC:
- Verify that an outside actor can see what files exist in an AMI.

**Comment by ilyavw** [comment]
Here are my notes for this issue.

We can grab IAM permissions to get access to user AMIs. The specific permissions would include `ec2:ModifyImageAttribute` which would allow us to set our investigative account as an additional owner. 

That said, there are some potential complications with this, plain EBS backed AMIs are fairly easy. If the EBS backed AMI is encrypted though we'll need the owner to also grant us permissions for the custom CMK used to encrypt the snapshot. Other complication is Instance backed AMIs, where the data is stored in S3. In that case we'll be needing permissions to access the bucket *if* we are trying to copy the AMI. We should still be able to create a volume from that AMI, but it would have to be in the same region. More testing is needed on that front.

`IAM Policy Used`
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeImages",
                "ec2:DescribeInstances",
                "ec2:ModifySnapshotAttribute",
                "ec2:DescribeSnapshotAttribute",
                "ec2:ModifyImageAttribute",
                "ec2:DescribeSnapshots"
            ],
            "Resource": "*"
        }
    ]
}
```

After a volume is created from an AMI all we really have to do is attach it to our inspector instance and perform the inspection. Discarding the snapshot and volume after we're done.
