### ISSUE TITLE
Migrate to new codecov uploader

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1405]
## Summary

As a cloudigrade maintainer, I want my PR checks to continue working with codecov so that I know I'm not introducing an unacceptable amount of untested code. codecov submissions have been failing with increasing frequency lately, and we just discovered that they deprecated the uploader we've been using. We need to update our GitHib workflow to install and call their new upload tool.

See the README for https://github.com/codecov/codecov-python which we have been using:

> :rotating_light::rotating_light: Deprecation Notice :rotating_light::rotating_light:
> This uploader is being deprecated by the Codecov team. We recommend migrating to our [new uploader](https://docs.codecov.com/docs/codecov-uploader) as soon as possible to prevent any lapses in coverage. [The new uploader is open source](https://github.com/codecov/uploader), and we highly encourage submitting Issues and Pull Requests.
> You can visit our [migration guide](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#python-uploader) for help moving to our new uploader, and our blog post to learn more about our [deprecation plan](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/)
> On February 1, 2022 this uploader will be completely deprecated and will no longer be able to upload coverage to Codecov.

## Acceptance Criteria

- [x] Verify codecov runs reliably on our PRs and still reports diff and project threshold values

## Assumptions and Questions

- Since this new uploader appears to require node/npm, we probably want to start installing it into the base image we use for testing to reduce install time and thrash during our PR checks. https://github.com/cloudigrade/build-container

**Comment by abellotti** [comment]
With the github action support in the new codecov uploader, there's no need to build it ourself (npm/node), just using the action directly after coverage run from the tox py39 steps is sufficient. see: https://github.com/cloudigrade/cloudigrade/pull/1406

Also, since we're public, there's no need to define a CODECOV_TOKEN to use the new uploader.

**Comment by abellotti** [comment]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/5797328/202728773-09054574-e0f6-4698-ac20-b2be15b7070e.png">

**Comment by infinitewarp** [comment]
Well, this is done, but Codecov continues to be somewhat flaky with random 404s ([example](https://github.com/cloudigrade/cloudigrade/actions/runs/3516149845/jobs/5892329924#step:6:32)) despite using their official GitHub action. 😞  Perhaps we'll need to look further into those failures or consider moving away from Codecov at a later date, but for now, I'd say the change as defined is done. 

See also https://github.com/codecov/codecov-action/issues/598 for other people suffering random 404s and some suggestions that may or may not actually help us.
