### ISSUE TITLE
Verify our Amazon account number formatting works

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#142]
@blentz brought it to our attention that we may be mishandling Amazon account numbers because they *might* need to be left zero padded as strings when the integer representation has fewer than 12 digits.

This may or may not actually be a bug. We need to verify that the APIs we are accessing through boto will work if we give a decimal/integer account ID with fewer than 12 digits. If it fails and we need to always left zero pad, then the output of this issue is to fix our handling.

See also: http://pastebin.test.redhat.com/567467

**Comment by blentz** [comment]
https://asciinema.org/a/3KxLxLya6EfqKoXPBqnaw4CDw

**Comment by blentz** [comment]
Demo: https://asciinema.org/a/zPL0RLQ7Wfj8kAo4EZgh9DioD
