### ISSUE TITLE
Copy snapshot when log analyzer finds new AMI

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#147]
As an admin, I want cloudigrade to call the Celery task to copy the AMI snapshot (`copy_ami_snapshot`) when cloudigrade's log analyzer finds a new AMI so that we can inspect it.

## Acceptance Criteria 

- [x] Verify that when log analyzer encounters a new AMI, it calls the `copy_ami_snapshot` task.
- [x] Verify that when log analyzer encounters an AMI we already have seen (because it exists in the database), it *does not* call the `copy_ami_snapshot` task.

## Assumptions and Questions

- This builds on top of https://github.com/cloudigrade/cloudigrade/issues/167 which defined the `copy_ami_snapshot` task.
- This assumes that we have exhumed and cleaned up the log analyzer code to behave appropriately. See #148.

**Comment by abaiken** [comment]
I have verified that this is completed from Ilya's [demo](https://asciinema.org/a/TVS3j7pndjqIFvQTJtDLUEGsQ).
