### ISSUE TITLE
Test environment

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#149]
As a quality engineer, I want a test environment so that I can run integration tests.

## Acceptance Criteria 

- [x] Verify we have cloudigrade, postgresql, and rabbitmq running in OpenShift
- [x] Verify that new releases are automatically being deployed to the environment
- [x] Verify that database migrations are automatically running during deployment
- [ ] Verify that after an automatic release is deployed to the test environment, the test suite is triggered to run.
- [x] Verify that project documentation has been update to explain how this works.

## Tech assumptions

- This includes the initial setup of OpenShift with cloudigrade.
- The "how our updates get installed" question is to be experimented and answered here. 
- Remember that we need to deal with templating, secret management, etc. here.
- Ideally whoever is working on this will also teach the group about how things work. Lunch and learn, perhaps?
- Let's try doing proper continuous development and have each commit on master trigger a release to the test environment.
- As we are building this, have continued conversations about including a hook to initiate the actual running of tests.
- Decide whether to reuse or create a new cluster in AWS for houndigrade.

**Comment by aweiteka** [comment]
It would be slick to use OpenShift source-to-image builds for this. Documentation suggests OpenShift supports up to [python 3.5](https://docs.openshift.org/latest/using_images/s2i_images/python.html#s2i-images-python-versions), although I see 3.6 support in the [S2I repo](https://github.com/sclorg/s2i-python-container/tree/master/3.6). This project uses at least one [3.6 feature](https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals).

Definitely worth checking into. +1
