### ISSUE TITLE
Run task to clean up cluster, etc.

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#169]
As a Doppler admin, I want a Celery task to handle cleanup of the cluster, volumes, and snapshots so this can happen asynchronously after inspection completes.

This task should be called *not* by houndigrade *but* by whatever has processed houndigrade's output. Specifically, for this process to start, we also need to change the output from https://github.com/cloudigrade/cloudigrade/issues/92 to call this new task.

## Acceptance Criteria 

- [x] Verify that we have removed our ownership from the originating customer snapshots after we copy their snapshot.
- [x] Verify that our copied snapshots have been deleted (or are in-progress for deletion) after volumes are created
- [x] Verify ECS scale is set to zero after this task runs.
  - [x] Verify that AWS terminates any running instances in the cluster
- [x] Verify that our copied volumes have been deleted

## Tech assumptions

- Within this task are a bunch of "fire and forget" asynchronous commands to AWS. We do not care at this point to ensure that Amazon finishes its own side of the cleanup.
- This should include operations in the following order:
  - Remove ownership from snapshot after we have a working copy of snapshot
  - Delete our snapshot copy after we have a working volume
  - Configure volumes to automatically delete when the cluster scales down
  - set ECS scale to 0
    - AWS should automatically terminate running instances when this happens

**Comment by kholdaway** [comment]
Demo link -> https://drive.google.com/open?id=1z-xmkeqco3tFzmuNwckp_aZn2UM5g70m

**Comment by ilyavw** [comment]
Looks good, thanks! Verified/Closing.
