### ISSUE TITLE
Account API POST failing on AWS API call

### ISSUE THREAD

**Issue by adberglund** [cloudigrade/cloudigrade#173]
Attempting to create an account fails on the ec2 `ModifySnapshotAttribute` API call. It looks like the snapshotid has a naming convention that is now being enforced. 

```
Exception Type: ClientError at /api/v1/account/
Exception Value: An error occurred (InvalidParameterValue) when calling the ModifySnapshotAttribute operation: Value (string) for parameter snapshotId is invalid. Expected: 'snap-...'.
```

**Comment by ilyavw** [comment]
Seems like something is wrong on the AWS side of things, these are the two calls I'm making:
```
response = client.modify_snapshot_attribute(
    Attribute='ProductCodes',
    OperationType='add',
    SnapshotId='snap-0f423c31dd96866b2',
    DryRun=True
)
```
That fails ^

```
response = client.describe_snapshot_attribute(
    Attribute='productCodes',
    SnapshotId='snap-0f423c31dd96866b2',
    DryRun=False
)
```
That doesn't ^

And per the aws docs that makes no sense http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.modify_snapshot_attribute

**Comment by ilyavw** [comment]
@adberglund I've managed a successful request with the following:
```
response = client.modify_snapshot_attribute(
    Attribute='createVolumePermission',
    OperationType='add',
    SnapshotId='snap-0f423c31dd96866b2',
    DryRun=True
)
```

**Comment by infinitewarp** [comment]
@adberglund Want to post a quick demo so we can call this closed?

**Comment by adberglund** [comment]
Sure. https://asciinema.org/a/vwVzFyFpmgMTQg7g8h2r149Rr

**Comment by ilyavw** [comment]
Verified.
