### ISSUE TITLE
Run scheduled task to scale up cluster size

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#176]
As a Doppler admin, I want the cluster size to automatically scale up via a *scheduled* Celery task (like cron) so the cluster becomes available automatically when some volumes are ready.

## Acceptance Criteria 

- [x] Verify that when the cluster size is nonzero, this process exits cleanly with no changes.
- [x] Verify that when the cluster size is zero and there are zero messages, this process exits cleanly with no changes.
- [x] Verify that when the cluster size is zero and there are some messages representing ready volumes, this process dequeues up to the configured limit number of messages and sets the cluster size to 1.
- [x] Verify that when there are *more* messages on the queue than the batch size limit, this process reads and dequeues only up to the configured limit number of messages.

## Tech assumptions

- If the scale is already nonzero, then we must exit because this means the cluster is currently active.
- We do *not* need to retry later in the first acceptance criteria as long as we have not yet dequeued/lost any messages and because the schedule should automatically start again later.
- Because AWS limits the number of volumes we can mount, we need a limit baked into the part of the process. This should be a configuration variable with a reasonable default (32).
- The estimate we have given to this story assumes that _something_ exists within the boto3 library to do what we need (we have not yet verified this).

**Comment by ilyavw** [comment]
This looks like the boto3 api we'll need to use http://boto3.readthedocs.io/en/latest/reference/services/application-autoscaling.html#ApplicationAutoScaling.Client.put_scaling_policy

**Comment by infinitewarp** [comment]
- demo for AC1: https://asciinema.org/a/178750
- demo for AC2: https://asciinema.org/a/178752
- demo for AC3: https://asciinema.org/a/178755

I would ask that the "demo" for AC4 be to review and trust the _thorough_ unit test coverage. 🙂

**Comment by ilyavw** [comment]
> I would ask that the "demo" for AC4 be to review and trust the thorough unit test coverage. 🙂

404 Test Not Found

**Comment by infinitewarp** [comment]
I added another unit test, and I recorded another demo!

- demo for AC4: https://asciinema.org/a/178767

**Comment by ilyavw** [comment]
AC Verified
