### ISSUE TITLE
Ensure working credentials before completing setup

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#21]
As a Doppler admin, I want to ensure that our Doppler AWS account ID actually has access to the  customer's AWS Account ID before confirming user is done with setup.

## Acceptance Criteria

- [x] Verify that if we cannot access the customer's account, we do not save and the user receives an appropriate error message.
- [x] Verify that correctly configured account access allows successful saving.

## Tech assumptions

- We will decide which APIs we want to poke to ensure minimum connectivity using the credentials.
- For now, we only care to verify once synchronously during setup. Maybe later we'll have additional checks to ensure that access hasn't been revoked, but we don't care about that now.

**Comment by kdelee** [comment]
I am on a steep learning curve with all these amazon acronyms. How does this relate to https://github.com/cloudigrade/cloudigrade/issues/22 ? How is it distinct?

**Comment by kdelee** [comment]
Again, like my comments on #22, I think the title of this story sounds more like an acceptance criteria. From what I understand I am getting that the experience that the user will hopefully have is ... "As a user I can save my AWS credentials to Doppler and have them validated at the time of creation"?
