### ISSUE TITLE
Health checks. Have them!

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#213]
As a Doppler admin, I want my services to have health checks so that my container orchestration platform can start/restart/etc them appropriately.

## Acceptance Criteria 

- [x] Verify that we have a documented mechanism to see that **cloudigrade** is running.
  - [x] Kubernetes liveness: defines that the container is alive, but might not yet be ready to serve requests
  - [x] Kubernetes readiness: defines that the container is alive and ready to serve requests

## Assumptions and Questions

-

**Comment by ilyavw** [comment]
Demo?

* [cloudigrade  liveness](https://github.com/cloudigrade/cloudigrade/blob/master/deployment/ocp/cloudigrade.yml#L120)
* [cloudigrade readiness](https://github.com/cloudigrade/cloudigrade/blob/master/deployment/ocp/cloudigrade.yml#L131)
* [NGINX liveness](https://github.com/cloudigrade/cloudigrade/blob/master/deployment/ocp/cloudigrade.yml#L156)
* [NGINX readiness](https://github.com/cloudigrade/cloudigrade/blob/master/deployment/ocp/cloudigrade.yml#L164)

[Django health check page](http://cloudigrade-cloudigrade-test.1b13.insights.openshiftapps.com/healthz/)

**Comment by infinitewarp** [comment]
![](https://media.giphy.com/media/QyrysGo7Hz70I/giphy.gif)
