### ISSUE TITLE
Ensure customer's IAM role/policy has required privileges enabled

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#22]
As a Doppler admin, I want to programmatically access customers accounts so I can retrieve EC2 and CloudTrails data.

## Acceptance Criteria

- [ ] Verify that each required privilege is enabled by testing related API calls upon customer setup
- [ ] Verify that when a required privilege is not enabled, the CLI user sees an appropriate error message and causes account setup/save to abort

## Tech assumptions

- For now, we will provide to the customer a JSON blob (defining an IAM policy) and instructions to manually add an IAM user and role so Doppler can access that customer's AWS account.

**Comment by kdelee** [comment]
Ok, I am a bit confused on what this story is about.

Is the intent to add a feature where CLI users can save customer access credentials (IAM) to Doppler, and upon creation Doppler immediately validates these credentials and ensures that they have the required level of access?

If so, I think the STORY should be "As a Doppler admin, I can save IAM to doppler to access EC2 and CloutTrails data at a later time"
Then "The IAM are automatically validated as having proper access privileges at creation time" is an acceptance criteria.
