### ISSUE TITLE
Save inventory of currently running instances

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#24]
As a Doppler admin, I want to see an inventory of any instances that were already running (see #23) *to be saved to a database* so that I can review them in a report at a later time.

## Acceptance Criteria

- [x] Verify that the list of instances and AMIs that are currently powered on is written to a database with the time of check as the time the instance was powered on.
- [x] Verify that the attributes in #23 are in a DB table
- [x] Verified that "powered on" is the event type
- [x] Verify that effectively `CURRENT_TIMESTAMP` is the event time

## Technical Assumptions

- Since we expect the future service to be a web app, we will go ahead and start this using Django even though effectively this is a "simple" CLI.
- We do not care at this time about deduping, collision checking, updating, etc.
  - This means the app may crash on duplicate row for now.
- This is to define the same "event" table that will later be used in the CloudTrail log scraping and processing output.
- The `InstanceId` from AWS is *effectively* our primary key or at least a sort-of unique index.
- Also include on the table:
  - region ID (which we should have from the initial connection/client)
  - AWS user/account ID, which should be a foreign key back to the user/account table that we created in #18 
- All columns in our tables that are references to AWS-based IDs should be strings.

**Comment by kdelee** [comment]
I appreciate you linking to related issues.

Maybe could add section at bottom of issue template "Depends on ...".

Re: this issue in particular
Please provide more specific acceptable time diff for "... effectively `CURRENT_TIMESTAMP` is the event time"
