### ISSUE TITLE
Celery worker missing from OpenShift environment

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#243]
We missed this in #229 since the initial OpenShift environment PR merged very shortly before that one. We now have most things running in OpenShift, but we do not have a Celery worker running anywhere!

### Steps to reproduce

1. `make oc-up-all`
2. look at what's running in OpenShift

### Expected result

- There should be a container with a Celery worker to process tasks as they arrive.

### Actual result

- There are no containers running Celery workers!

**Comment by ilyavw** [comment]
Looks good!
