### ISSUE TITLE
Specify the openshift url for some make commands with env variable

### ISSUE THREAD

**Issue by kdelee** [cloudigrade/cloudigrade#250]
If a user has previously logged into a different openshift instance with `oc`, even if they have logged out `oc` still tries and talks to the other instance.

I could add an environment variable into the `make oc-login-admin` and `make oc-login-developer` command so if it exists, it is used. i.e. `oc login $OPENSHIFT_URL -u developer -p developer --insecure-skip-tls-verify`, otherwise it is just the same as it has been.

**Comment by kdelee** [comment]
@ilyavw what do you think about this? I can assign myself + make a PR if you think it is a good idea.

**Comment by ilyavw** [comment]
@kdelee I'd recommend using oc context, not many people will have to log into the insights cluster. Check out `oc config --help`.

**Comment by kdelee** [comment]
:+1: Ok closing this then
