### ISSUE TITLE
Research customization of CloudTrails reporting options

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#26]
- Can we limit to only log EC2 power on/off?
- Compare to CloudWatch monitoring on EC2 instances

Time-box to half a day and dump notes here.

**Comment by ilyavw** [comment]
Can we limit to only log EC2 power on/off?
* No, the closest we get is limiting to write only events

Compare to CloudWatch monitoring on EC2 instances
* CloudWatch can be used to either report individually, or to parse cloudtrail logs, either way it doesn't seem to fit our use case very well without adding unnecessary cost.

So far cloudtrail with write only events is our best bet for getting as many relevant events with as little noise as possible. 

One of the nicer things is that we don't explicitly have to give access to our customers to write to a specific S3 bucket, the policy below grants access to the cloudtrail service specifically.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AWSCloudTrailAclCheck20150319",
            "Effect": "Allow",
            "Principal": {
                "Service": "cloudtrail.amazonaws.com"
            },
            "Action": "s3:GetBucketAcl",
            "Resource": "arn:aws:s3:::BUCKET-NAME"
        },
        {
            "Sid": "AWSCloudTrailWrite20150319",
            "Effect": "Allow",
            "Principal": {
                "Service": "cloudtrail.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::BUCKET-NAME/*",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        }
    ]
}
```

Cloudtrail will have separate folders for specific account ids which would allow us to have all customers write to a single bucket for simpler processing.
