### ISSUE TITLE
API to set custom display name for account

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#267]
As a regular user, I want to give my new cloud account a custom name so that I can find and organize my accounts to my liking.

This includes changing the create account API to include an optional display name text field and adding support to _update_ an account via the API to set the optional display name.

## Acceptance Criteria

- [x] Verify that a regular user can save an account _with_ a name during the account creation process.
- [x] Verify that a regular user can save an account _without_ a name during the account creation process.
- [x] Verify that the API allows the user to update that name at any later time.
- [x] Verify that the name is included when listing and retrieving accounts from the API.
- [x] Verify that regular users *cannot* change the name for an account belonging to another user.
- [x] Verify that the API enforces the name attribute be of type string.
- [x] Verify that some reasonable character limit is enforced. ~TBD during development.~ It's 256 characters!
- [x] Verify that we have an issue for tracking the integration tests!

## Assumptions and Questions

- This DOES NOT include building the UI where a user can enter the account name during the account creation process. That will be tracked in a separate story.
- For the initial version, we will not attempt to get the name from the AWS API.
- Does the user enter a name upon account creation? Yes, [see the latest designs.](https://redhat.invisionapp.com/share/UFI078IZVAW) This means we need to update the "create" API as well as add an "update" API for the cloud account.

**Comment by kdelee** [comment]
Would add:

## Acceptance Criteria
- [ ] Verify that regular users can REFRAIN from naming an account by omitting the `name` field from the `POST` to `api/v1/account/` (i.e. at creation).
- [ ] Verify that super users can REFRAIN from naming an account by omitting the `name` field from the `POST` to `api/v1/account/` (i.e. at creation).
- [ ] Always take name in as string/return as string
- [ ] Enforce some character limit -- give sensible error when exceed

**Comment by infinitewarp** [comment]
demo: https://asciinema.org/a/190325

**Comment by dsesami** [comment]
@infinitewarp does the input allow names with whitespaces? (obviously it shouldn't allow _just_ whitespaces, as an extension of that if yes, but i digress)

**Comment by kdelee** [comment]
https://github.com/cloudigrade/integrade/issues/27 is the integrade issue, so I am going to tick off the last verify item.

Danny is going follow up with some more questions about tests at the unit test level, because it is relativley slow to create accounts, we might want to make sure our field validation is robust at the unit test level. @dsesami is on that

**Comment by elyezer** [comment]
Since all AC items are check I think we can just close this.
