### ISSUE TITLE
Read CloudTrails metadata for on/off events

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#27]
As a Doppler admin, I want to know when an EC2 instance is powered on and off so that I can bill customers appropriately.

## Acceptance Criteria 

- [ ] Verify that a CLI user sees the event metadata that CloudTrails delivers regarding instances powering on and off.
- [ ] Verify that a CLI user does *not* see events that had an error state; these should have been discarded.

## Tech assumptions

- CLI arguments include:
  - SQS queue URL
- Event metadata should include:
  - Event type (start/power on, stop/power off)
  - Event time
  - Instance ID
  - Instance size (e.g. micro)
  - AMI ID
  - subnet
- We need to be careful and explicit about checking for errors
  - For example, we may have a "stop instance" event but the action didn't really complete for some reason.
  - We probably want so just check for a value in the `Records[x].errorCode` of the event response.
- We still have very crude or nonexistent error handling.

**Comment by kdelee** [comment]
Have you considered allowing users to create named collections of accounts/s3 buckets? 

If these are long hash type IDs I think this could be pretty annoying to have to specify at the command line over and over. I'd rather specify them once and then be able to refer to them by name.

**Comment by adberglund** [comment]
I have done the bulk of the util work for interacting with SQS and S3 so that this log reader/analyzer can just process logs. I will post a PR for the util work that enables this shortly.
