### ISSUE TITLE
create_volume task keeps retrying despite error state at AWS

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#273]
When one of the operations we fire off to AWS as async produces an error, we should recognize that error, log and/or raise it somehow, and stop the backoff/retry mechanism. I recently experienced an issue where I was changing my AWS customer account's policy to remove permissions, and the async tasks running in the background kept running despite some errors. Specifically, I managed to time things such that cloudigrade successfully started the "copy snapshot" AWS command when I had removed access to it. This resulted in the new snapshot ID being created, but every time you described that new snapshot, AWS reported an error state.

How should we address this issue? In the various async tasks that check AWS objects for completion, we should specifically check for an "error" state and raise an appropriate exception that will stop the task from retrying.

## Steps to Reproduce

1. Not sure yet… will update this later.

## Expected Result

- Task runs once and halts when it encounters the error.

## Actual Result

- Task keeps retrying until it hits the configured stop limit.

**Comment by ilyavw** [comment]
Verified.
