### ISSUE TITLE
Record inspection state for images

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#275]
As a cloudigrade developer or sysadmin, I want images to be updated with a specific state upon creation or inspection so that I can better understand the overall state of image inspection.

As a customer, I want to see the state of an image's inspection process so that I can make informed decisions about my image inventory.

## Background

When we originally built out the image definition, we said that we could *infer* whether or not an image needs inspection based on the presence or absence of the values in the database. However,

- _explicit is better than implicit_ [[*](https://www.python.org/dev/peps/pep-0020/)],
- customers should be informed about how things are progressing through the system,
- and knowing more detailed state may be important when we start using the log analyzer.

For now, we believe that the following states should be sufficient:

- Pending Inspection (set at image discovered)
- Preparing for Inspection (set right _before_ async calling copy snapshot)
- Being Inspected (set at first step of run_inspection_cluster task)
- Inspected (set at the end of process_results task OR when we see "windows")

In the case of AMIs that we have identified as "windows" using the platform flag, we can set those images to the "Inspected" state at the same time we record that they are "windows".

## Acceptance Criteria

- [x] Verify that the `MachineImage` model returned by the API includes a property indicating the image inspection state.
- [x] Verify that the default state for newly-discovered images is "Pending Inspection".
- [x] Verify that the state is set to "Inspected" when an image with the "windows" platform is discovered. (see #87)
- [x] Verify that the state is set to "Preparing for Inspection" when an image starts in the chain of async commands for inspection (immediately before calling `copy_ami_snapshot`).
- [x] Verify that the state is set to "Being Inspected" for each image at the start of running the `run_inspection_cluster` task.
- [x] Verify that the state is set to "Inspected" when an image's inspection results from houndigrade are processed by cloudigrade (in the `persist_inspection_cluster_results_task` task).

## Assumptions and Questions

- We should complete this before #148 (log analyzer).

**Comment by ilyavw** [comment]
Demo is in https://github.com/cloudigrade/cloudigrade/pull/350#issue-195268555

**Comment by kdelee** [comment]
@ilyavw I watched the demo and clicked off the "verfiy" boxes I saw demonstrated.

**Comment by ilyavw** [comment]
@kdelee Great, thank you. At this point I just need some final approvals on my PR so it can be merged and this issue closed.

**Comment by kdelee** [comment]
pr is merged, closing
