### ISSUE TITLE
Save CloudTrails metadata for on/off events

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#28]
As a Doppler admin, I want customer EC2 instance power on/off events stored in my database so that I can easily report on them later.

## Acceptance Criteria 

- [ ] Verify that on/off records are stored in the DB
- [ ] Verify that all of the attributes from #27 are included in the DB models
  - [ ] Event type (start/power on, stop/power off)
  - [ ] Event time
  - [ ] Instance ID
  - [ ] Instance size (e.g. micro)
  - [ ] AMI ID
  - [ ] subnet

## Technical assumptions

- The DB models should already exist per a story completed in the previous sprint. See @infinitewarp if you have questions.

**Comment by kdelee** [comment]
Can you enumerate what all data will be saved in conjunction with this on/off data -- i.e. what is the primary key? How are we going to merge this with other data?

**Comment by adberglund** [comment]
A caveat I've discovered while working on #27

`RunInstances`: Create new instance(s), this has more info
`StartInstances`: Start a stopped pre-existing instance, this just has instance-id
`StopInstances`: Stop a pre-existing instance, this just has instance-id
`TerminateInstances`: Bye forever, instance. Not sure yet what data this has, let's find out.

When we go to save the data, we can either 
a) see if we've seen the instance before in our DB and fill in the info with what we have there, and if not call EC2 describe_instances() or 
b) always call EC2 describe_instances()
