### ISSUE TITLE
Centralize deployment configs

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#285]
## Summary

As a cloudigrade developer, I want my deployment configs to live in a common location so I can run cloudigrade locally without having to clone and run commands in multiple repos.

## Acceptance Criteria

- [x] Verify that when any commit lands on master, the updated template is pushed to our Insights cluster.
- [x] Verify that there exists one place that manages the OpenShift deployment configs. (this will probably be a new repo)
- [x] Verify that relevant `Makefile` targets (anything deployment related) have been removed from the old repos and now live in the new repo.

## Assumptions and Questions

-

**Comment by ilyavw** [comment]
Demo:
* https://travis-ci.org/cloudigrade/shiftigrade/builds/388906969?utm_source=github_status&utm_medium=notification
* https://github.com/cloudigrade/frontigrade/settings/hooks
* https://github.com/cloudigrade/cloudigrade/settings/hooks
* come peek over my shoulder to see the openshift cluster set up

**Comment by infinitewarp** [comment]
Nice work! I watched over the shoulder while Ilya demoed things.
