### ISSUE TITLE
500 when attempt to request password reset link with valid email, 204 when email does not exist

### ISSUE THREAD

**Issue by kdelee** [cloudigrade/cloudigrade#288]
## Summary

Sending `POST` with email of valid user to `auth/password/reset/` received 500 server error instead of expected `204`.

Invalid email (not associated with user account) should get `400`, but instead gets `204`

## Steps to Reproduce
for `500` with valid email
1. Create a user with email `foo@example.com`
2. Get token for user
3. Attempt to get password reset with proper authentication headers using the token and the right email

for `204` with invalid email
1. Make unauthenticated request to `auth/password/reset/` with email not associated with any account on the server. 

## Expected Result

- `204` and email sent to the email when a valid email is specidied
- `400` response when invalid email is specified

## Actual Result

- `500` server error for valid email
- `204` response for invalid email

## Additional context
Running locally in OpenShift from master at  829ec709e52bc153ab4815afd898992c6094ab3b

**Comment by kdelee** [comment]
@infinitewarp 

Recreated again this morning. My set up is this:

1) Pull lastest master branch
2) make oc-up-all
3) make oc-user
4) make oc-user-authenticate & save token
5) `http post http://$CLOUDIGRADE_BASE_URL/api/v1/account/ Authorization:"Token ${CLOUDIGRADE_TOKEN}" resourcetype="AwsAccount" account_arn="arn:aws:iam::518028203513:role/grant_cloudi_to_372779871274"`

**Comment by infinitewarp** [comment]
@kdelee would you include the complete HTTP requests (using httpie, curl, or whatever CLI) you're making against the APIs here?

**Comment by infinitewarp** [comment]
It looks like there are a few issues at play here, and we can probably only fix _some_ of them right now until we define how we want to work with emails in general.

In the case of the 500 error upon attempted password reset, the initial underlying error is:
```
Exception Value: 'Settings' object has no attribute 'PASSWORD_RESET_CONFIRM_URL'
```
However, after setting that missing configuration value, the request still blows up because the password reset functionality attempts to send an email without SMTP being configured, which is something we haven't tried to tackle yet.

**Comment by kdelee** [comment]
@infinitewarp can you give me some guidance about how to get to the logs of cloudigrade et. al. when serving in OpenShift? I've opened up the "logs" and terminal in the openshift console for the pods running but have not had luck yet finding where they are logging. That way I could do some more investigation in the future about the root causes of the problem.
