### ISSUE TITLE
See if AMI has RHEL

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#29]
As a Doppler admin, I want to know if a given AMI belonging to a customer is using RHEL so that I can report RHEL usage.

## Acceptance Criteria 

- [ ] Verify CLI output indicates whether RHEL is installed on the AMI
- [ ] Verify that we clean up any images we had to copy to get this information

## Tech assumptions

- EBS only for now
- Always copy snapshot for now
- Copy to `us-east-1`. Attach to our "inspector" instance.
- Simply check via `cat /etc/redhat-release`

**Comment by kdelee** [comment]
Might want to consider if you can leverage any logic the the quipucords folks have worked on to ascertain the OS of a system. https://github.com/quipucords/quipucords/blob/3723c97abfb31fc8ae017c90a15318df4ae2f1b2/roles/etc_release/tasks/main.yml

**Comment by kdelee** [comment]
I'm not quite understanding this copy behavior that you mention in another issue. Can you provide some more information on that and why you need to do it and what the impacts are?
