### ISSUE TITLE
de-queued ready_volumes message are not ack'd

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#339]
## Summary

When `scale_up_inspection_cluster` runs, it reads messages from the `ready_volumes` queue, but afterwards AWS SQS keeps those messages in a "Messages in Flight" state which means the message was not correctly ack'd. As a result, the message eventually **re-queues** itself (after a configured time in AWS) and will get picked up by a future task. This is bad!

## Steps to Reproduce

1. register a cloud account that has an instance using an unknown non-windows ami
1. wait until `scale_up_inspection_cluster` completes
1. observe the message counts for `ready_volumes` in the SQS web console

## Expected Result

- 0 messages queued and 0 messages in flight

## Actual Result

- non-zero messages in flight

**Comment by infinitewarp** [comment]
We seem to be experiencing the same problem as https://github.com/celery/kombu/issues/746. It looks like https://github.com/celery/kombu/pull/817 would fix it, and when I locally `pip install`ed that branch to experiment, everything SQS-related in cloudigrade seems to start working correctly, but that PR is over six months old and no closer to being merged.

The team has discussed our options, and I'm going to look at "fixing" our issue by dropping Kombu entirely and making straight `boto3` calls. 🤷‍♂️

**Comment by ilyavw** [comment]
I can verify that this bug is resolved.
