### ISSUE TITLE
API to get daily totals over date range

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#355]
## Summary

As a Cloud Meter API client, I want to 1) see the total count of instances that were running a RHEL or OpenShift image for each day and 2) the total elapsed seconds they ran for each day in a given period so that I can build pretty graphs to show to users.

This will power the three line/bar graphs on the dashboard page. See [this mockup](https://redhat.invisionapp.com/share/UFI078IZVAW#/screens/296433286).

Inputs for the API call must include the start date and end date. These are REQUIRED arguments. The API will not restrict the allowed range of days. Leaving this open allows us to find performance issues to optimize in the future.

Input may include OPTIONAL `user_id` argument to facilitate admin/superuser functionality. This should behave like our other APIs. Normal users will not supply this value and already get filtered by presense of session. Superusers will supply this value to impersonate normal users.

Output data is effectively aggregated by day. For each day, output includes:

- Number of instances with a RHEL-tagged image _seen running_ during the day. It doesn't matter if the same instance started and stopped multiple times; we care about the number of distinct instances seen.
- Number of instances with an OpenShift-tagged image _seen running_ during the day. It doesn't matter if the same instance started and stopped multiple times; we care about the number of distinct instances seen.
- Cumulative number of seconds any instances with a RHEL-tagged image ran during the day.
- Cumulative number of seconds any instances with an OpenShift-tagged image ran during the day.

If an instance is backed by an image that has BOTH RHEL and OpenShift tags, it fairly contributes to both categories.

Output should look something like this:

```json
"data": [
  {
    "date": "2018-06-01",
    "rhel_instances": 12,
    "openshift_instances": 12,
    "rhel_runtime_seconds": 6000,
    "openshift_runtime_seconds": 6000
  },
  {
    "date": "2018-06-02",
    "rhel_instances": 12,
    "openshift_instances": 12,
    "rhel_runtime_seconds": 6000,
    "openshift_runtime_seconds": 6000
  },
  {
    "date": "2018-06-03",
    "rhel_instances": 12,
    "openshift_instances": 12,
    "rhel_runtime_seconds": 6000,
    "openshift_runtime_seconds": 6000
  }
]
```

The API should live at: `/api/v1/report/instances/`

## Acceptance Criteria

- For RHEL-tagged and OpenShift-tagged images:
    - Verify an instance that was started on day `x` and stopped on day `x+2`:
        - [ ] contributes once to the instance count for day `x`
        - [ ] contributes once to the instance count for day `x+1`
        - [ ] contributes once to the instance count for day `x+2`
        - [ ] contributes the number of seconds from start time to end of day to the runtime for day `x`
        - [ ] contributes 86400 seconds to the runtime for day `x+1`
        - [ ] contributes the number of seconds from start of day to the end time to the runtime for day `x+2`
    - [ ] Verify an instance that stops and starts multiple times in the same day contributes once to the instance count for that day
- For images that are not tagged as either RHEL or OpenShift:
    - [ ] Verify an instance that starts and stops on a given day _does not_ contribute to the instance count or cumulative run time for either RHEL or OpenShift.
- [ ] Verify that normal User A only sees data from events by instances owned by User A, not User B.
- [ ] Verify that a superuser can apply the `user_id` filter to see data for other users.
- [ ] Verify that an issue for tracking integration tests exists and is referenced here.

## Assumptions and Questions

- We do not care about things like the instance size, subnet, detailed version of RHEL (6, 7, etc.). All we care about is the aggregate counts of instances and the total elapsed times.
- For now, all time is recorded, aggregated, and reported using Zulu/GMT+0.
- The start and end date inputs should be timestamps! e.g. "2018-01-01T00:00:00Z".
- The `end_date` input should exclusive!
    - Inclusive start and exclusive end:
        - "2018-01-01T00:00:00Z to 2018-02-01T00:00:00Z"

**Comment by infinitewarp** [comment]
@cdcabrera will give some suggestions around best data structure for the frontend to consume.

**Comment by dmiller9911** [comment]
I also lean towards using the "data" as the response.  It should be obvious that the data is totaled by date based on API docs or the route path. While the first example that David gave is easier for the UI, the second example he gives will be almost as easy and gives a more complete picture. Most Likely the data and other properties will be needed for labels in tooltips or the legend as well.

**Comment by kdelee** [comment]
I was under the impression we would also get a number for openshift runtime seconds: `"openshift_runtime_seconds": 6000`, is that correct?

**Comment by ironfroggy** [comment]
Are all the dates listed in these data responses UTC?

**Comment by infinitewarp** [comment]
@ironfroggy Yes, we agreed in our in-depth discussion of the dashboard that all datetime values will be UTC/Zulu/+0 for now. We acknowledged that this isn't a perfect fit since customers obviously will operate and want to track their days at different offsets, and we may layer that kind of functionality in in a future post-pilot release.
