### ISSUE TITLE
API to get summary totals per cloud account

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#356]
## Summary

As a Cloud Meter API client, I want to see a list of my cloud accounts ("ARNs") with each having 1) total number of found images, 2) total number of found instances, 3) total number of instances identified as using a RHEL image, 4) total number of instances identified as using an OpenShift image, all of which are filtered to a defined date range.

This will power the rows in the lower half of the dashboard page. See [this mockup](https://redhat.invisionapp.com/share/UFI078IZVAW#/screens/296433286).

Inputs for the API call must include the start date and end date. These are REQUIRED arguments. The API will not restrict the allowed range of days. Leaving this open allows us to find performance issues to optimize in the future.

Input may include OPTIONAL `user_id` argument to facilitate admin/superuser functionality. This should behave like our other APIs. Normal users will not supply this value and already get filtered by presense of session. Superusers will supply this value to impersonate normal users.

Output data is effectively aggregated by cloud account. For each cloud account, output includes:

- Number of distinct images used for _any_ instance seen running during the period.
- Number of distinct instances seen running during the period.
- Number of distinct instances with a RHEL-tagged image seen running during the period.
- Number of distinct instances with an OpenShift-tagged image seen running during the period.

Note: It does not matter if an instance starts and stop multiple times during the period. The instance only contributes to the counts exactly once if ever seen.

Output should look something like this:

```json
{
    "cloud_account_overviews": [
        {
            "id": 13,
            "user_id": 4,
            "type": "aws",
            "arn": "arn:aws:iam::1234567890:role/rolename",
            "creation_date": "2018-01-15T12:34:56Z",
            "name": "my great account",
            "images": 10,
            "instances": 50,
            "rhel_instances": 30,
            "openshift_instances": 30
        },
        {
            "id": 14,
            "user_id": 4,
            "type": "aws",
            "arn": "arn:aws:iam::1234567891:role/rolename",
            "creation_date": "2018-02-07T12:34:56Z",
            "name": "my other account",
            "images": 10,
            "instances": 50,
            "rhel_instances": 30,
            "openshift_instances": 30
        },
    ]
}
```

If we have not yet built the ability for a user to define a custom display name for their cloud accounts, we should still include a `name` attribute but leave it `None`/`null` for now.

The API should live at: `/api/v1/report/accounts/`

## Acceptance Criteria

- [x] Verify that "images" represents the total number of unique images for instances that were powered on during the reporting period.
- [x] Verify that an instance that is backed by an image tagged with neither RHEL nor OpenShift that is powered on during the reporting period contributes exactly and only once to the "instances" count but zero to "rhel_instances" and "openshift_instances" counts.
- [x] Verify that an instance backed by an image tagged with RHEL that is powered on during the reporting period contributes exactly and only once to the "instances" and "rhel_instances" counts.
- [x] Verify that an instance backed by an image tagged with OpenShift that is powered on during the reporting period contributes exactly and only once to the "instances" and "openshift_instances" counts.
- [x] Verify that an instance that is backed by an image tagged with both RHEL and OpenShift that is powered on during the reporting period contributes exactly and only once to the "instances", "rhel_instances", and "openshift_instances" counts.
- [x] Verify that if no images or instances are found running during the period, the appropriate attributes have the value `0`.

## Assumptions and Questions

- For now, all time is recorded, aggregated, and reported using Zulu/GMT+0.
- The start and end date inputs should be timestamps! e.g. "2018-01-01T00:00:00Z".
- The `end_date` input should exclusive!
    - Inclusive start and exclusive end:
        - "2018-01-01T00:00:00Z to 2018-02-01T00:00:00Z"
- Should the results always show all accounts? Yes. If an account was registered after the end date, should it be included with 0s or excluded from the results? It should be included with `None`/`null` values to indicate that the data is unknown.
    - If the end date is `<=` the cloud account creation date, then logically we cannot give meaningful data. So, we return `None`/`null` for all counter fields.
    - If there is *any* point in the period in which the account exists, we imply that we do know authoritatively the data, even though realistically we only know part of it.

**Comment by kdelee** [comment]
Question: the `"total_rhel_images": 5, "total_rhel_instances": 30` numbers reflect "Cloud Access and custom AMIs of RHEL" and excludes OpenShift (if it is on a RHEL image)?

**Comment by ironfroggy** [comment]
- Will an account appear if no instances were detected in the date range? If so, what does that entry look like?
- What if an account was only created _after_ the date range? Will it behave the same or differently from above?
- What are the valid values for the status field?

**Comment by abaiken** [comment]
Demo: [https://drive.google.com/file/d/1bgG1I8HaLKNYGQvwy6xCEWfue2otzOD-/view?usp=sharing](https://drive.google.com/file/d/1bgG1I8HaLKNYGQvwy6xCEWfue2otzOD-/view?usp=sharing)

**Comment by ilyavw** [comment]
Verified, thanks!
