### ISSUE TITLE
persist_inspection_cluster_results Celery beat requires CELERY_TASK_ROUTES entry to run

### ISSUE THREAD

**Issue by kholdaway** [cloudigrade/cloudigrade#358]
## Summary

As configured today, the persist_inspection_cluster_results celery beat will not run.  Even though persist_inspection_cluster_results uses a traditional messaging queue, the beat requires a route in the CELERY_TASK_ROUTES dict.

## Steps to Reproduce

1. Start Cloudigrade and notice the beat does not run.

## Expected Result
Beat should run.

## Actual Result
Beat doesn't run.

Fixing this bug will require a change to both cloudigrade and shiftigrade (2 PRs)

**Comment by abaiken** [comment]
I started cloudigrade and celery and verified that the beat ran 🙌
