### ISSUE TITLE
Update houndigrade-cluster-setup.md to cover availability zones

### ISSUE THREAD

**Issue by kholdaway** [cloudigrade/cloudigrade#367]
## Summary
We discovered that AWS will give your cluster more than one availability zone.  Houndigrade requires the `HOUNDIGRADE_AWS_AVAILABILITY_ZONE` env to match the active zone.  A user can limit the cluster to a single availability zone.  Update the doc to describe this process.

See:
https://github.com/cloudigrade/cloudigrade/blob/master/docs/dev-houndigrade-cluster-setup.md

**Comment by ilyavw** [comment]
Doc changes look good, verified.

PR: https://github.com/cloudigrade/cloudigrade/pull/368
