### ISSUE TITLE
As a consumer of the API, I want the `/api/v1/image/` endpoint to be documented

### ISSUE THREAD

**Issue by kdelee** [cloudigrade/cloudigrade#373]
## Summary

As a consumer of the API, I want to be able to read about what information I will get from the `/api/v1/image/` endpoint.

## Acceptance Criteria
I can answer the following questions by reading the documentation:
- [ ] What fields are in an individual objects in the results of a GET to the endpoint?
- [ ] If two users with distinct cloud accounts both have instances from the same AMI, what does the super user see when they do a GET to the endpoint? Is there one image? or two? If there is two, is there a field indicating what user/cloud account the image came from?
- [ ] How are identified products indicated on an image? Are there various fields with boolean values? Or is it a list of tags?
- [ ] How are CloudAccess, Marketplace "golden", and custom images of RHEL differentiated?
- [ ] How are challenged products indicated? If the image is shared/public and globally unique (answer to the above question was there is only one record per image) and has been associated with multiple user and or cloud accounts, how do I determine which user / which cloud account  challenged a "found" product? 
- [ ] If one user has distinct cloud accounts (different AWS account #'s) and share images across these accounts, if the user challenges a product identification via the detailed image drop down from one cloud account in the UI ( see https://redhat.invisionapp.com/share/UFI078IZVAW#/screens/296433285 ), does the challenge propagate over to the other cloud account? Moreover, if another different Cloudigrade user has a cloud account that uses this shared image, will the challenge propagate to THEIR view?
- [ ] Is it indicated whether the image is public, private, or a private shared image? 
- [ ] What query parameters are accepted?

## Assumptions

- We are able to deal with shared images.
- We will have some way of knowing whether or not something has OpenShift on it.

**Comment by infinitewarp** [comment]
https://github.com/cloudigrade/cloudigrade/blob/master/docs/rest-api-examples.rst should have been updated when developers added the new API endpoints.

**Comment by infinitewarp** [comment]
Also, since this is a purely internal "private" API, I would _not_ expect thorough documentation around these endpoints. We should still have _something_ though to point frontend and QE developers in the same direction.
