### ISSUE TITLE
API to set custom display name for account (duplicate)

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#379]
## Summary

As a customer, I want to be able to give my account a custom display name so that I can more easily recognize it in a list.

This includes changing the create account API to include an optional display name text field and adding support to _update_ an account via the API to set the optional display name.

## Acceptance Criteria

- [ ] Verify

## Assumptions and Questions

- Does the user enter a name upon account creation? If not, then we don't need to change the "create" API.

**Comment by ironfroggy** [comment]
- I've seen UI for creating an account, where we add a name. Is there UI or mockups for editing/updating that will use the second half of this ticket?
- Are there any restrictions on the name? Length, permitted characters, etc.
- Is both creation and editing of accounts with a custom name required for the pilot or just creating?

**Comment by kdelee** [comment]
@infinitewarp is this different from https://github.com/cloudigrade/cloudigrade/issues/267 ?
