### ISSUE TITLE
Use a real message queue (or: dump SQS in favor of Redis)

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#433]
## Summary

As a cloudigrade developer and operator, I want to use a message queue that has supporting libraries that are reliable and perform well so that I can trust that it will not cause problems in my system.

This is basically saying "dump SQS in favor of a real queue". We've had various issues with SQS and ~should consider running our own RabbitMQ somewhere like we did when we started this project~ using the app-sre provided elasticache redis db.

## Acceptance Criteria

- [x] Verify that all traces of pycurl are gone.
- [x] Verify that celery now uses redis elasticache as a backing queue instead of sqs
- [x] Verify that functionality as a whole of cloudigrade is unchanged.

## Assumptions and Questions

- Developer morale will go up greatly if we actually dump SQS in favor of a real queue.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jan 28, 2019, 09:17

marked this issue as related to #430

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jan 29, 2019, 15:31

marked this issue as related to #522

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Dec 16, 2020, 15:02

marked this issue as related to #763

**Comment by infinitewarp** [comment]
It's live! It's in prod! Things aren't exploding. So, this is done. Thanks @katherine-black ! 🎉
