### ISSUE TITLE
Revisit queue health checks

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#437]
In GitLab by @katherine-black on Jul 17, 2018, 10:03

## Summary

As a developer, I want my application to correctly clean up objects that are no longer in use so that there are no memory leaks. This is a continuation of #421 

Blocked until we do https://github.com/cloudigrade/cloudigrade/issues/433

## Acceptance Criteria

- [ ] Verify

## Assumptions and Questions

-

**Comment by infinitewarp** [comment]
Closing! This may still be a problem, but we probably don't need to monitor the health of the queue in this way, and we may soon be switching broker implementations.
