### ISSUE TITLE
Delete cloud account

### ISSUE THREAD

**Issue by ghost** [cloudigrade/cloudigrade#441]
In GitLab by @infinitewarp on Jul 20, 2018, 18:22

## Summary

As a customer, I want to delete my cloud account so that it is no longer tracked and reported.

## Acceptance Criteria

- [x] Verify that a UI element exists to delete a cloud account
- [x] Verify that clicking the element presents a typical confirmation modal before actually proceeding to delete
- [x] Verify that deleting a cloud account:
    - [x] disables the CloudTrail trail in the customer's AWS account
    - [x] removes it from the cloud account summary reporting/dashboard api
    - [x] removes its instances activity from the daily instance reporting/dashboard api
- [x] Verify that after deleting a cloud account, one can recreate the same cloud account and the Cloud Trail trail (and other supporting bits) works as expected.
- [x] Verify that regular users can only delete their own accounts, not accounts for any other users.
- [x] Verify that via the API super users can delete accounts belonging to any account.
- [x] Verify that in the UI, super users impersonating other users do not have access to the delete button.
    - This is only relevant if we have impersonation actually working in the UI.
- [x] Verify docs/strings/wordigrade have upgraded verbiage for the button and confirmation alert. 
- [x] Verify docs/ui have 'cloudtrail:StopLogging' in the aws cloudigrade policy
- [x] Verify that if the customer has already disabled our access into their AWS account (by removing or changing their Policy or Role), we can still successfully delete our data even though that means we cannot disable the customer's Cloud Trail trail. (This should produce a warning in our logs.)
- [x] Verify that when Cloud Trail processes a message and encounters an account that is not in our system, we skip processing of that message and successfully delete it from the queue.
- [ ] Verify that the change in policy is communicated out to the users
- [x] Documentation additions/changes are complete/reviewed  
    - [x] New StopLogging action for policy added to "How Cloud Meter uses the IAM policy" table https://docs.google.com/document/d/1O2vBNGkP8zRLRzdrbWb9C8RpkBDFGpmbImuipmo7HcA/edit#heading=h.5oep4fgdrh5k
    - [x] New Deleting Cloud Meter accounts section (and subsections) https://docs.google.com/document/d/1O2vBNGkP8zRLRzdrbWb9C8RpkBDFGpmbImuipmo7HcA/edit#heading=h.8bh0g15nbppa

## Assumptions and Questions

- This includes changes to both frontigrade, cloudigrade, and wordigrade.
- We do not have explicit wireframe examples for the confirmation alert. David will use his best judgment. :slight\_smile: :thisisfine:
- Do we want to truly delete the data in our database? Or do we want to just flag it as deleted/hidden in some way?
    - For now, let's just delete the things.
    - What do we delete?
        - the cloud account
        - the instances for that account
        - the events for the instances
        - any images that are no longer used by *any* instance events
- API responds with 204 No Content or 200 OK. See what DRF does for "normal" deletes and try to mimic that behavior.
- In the UI, this effectively replaces the "Archive" with "Delete" from [the mockup seen here](https://redhat.invisionapp.com/share/UFI078IZVAW#/screens/296433286)
    - We may convert this to "Archive" as some future date yet to be determined.
- https://redhatmbu.aha.io/epics/METER-E-42
- If a user adds an account, generates some data, deletes that account, and adds it again later, we have _no knowledge_ about that account's activity from when we previously tracked it. For all intents and purposes, the second time the user adds the account, we act as though it is the first time we've seen it.
- The customer aws cloudigrade policy needs to be updated to include 'cloudtrail:StopLogging'. This should include a docs change that explains this permission (Allow Cloudigrade to turn off Cloudtrail logging when user account is removed.)

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jul 20, 2018, 18:23

changed title from **Delete cloud account{-s-}** to **Delete cloud account**

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 20, 2018, 12:58

Backend wise: 

The API endpoint for this should be accessed with the `DELETE` verb to `/api/v1/account/{id}/`

On a successful DELETE, the API should respond with http code `204` and no body content

On an unsuccessful DELETE, the API should respond with http code `500`, and a JSON body describing the error message, where {reasons} will be updated with information on whatever failed (cloudtrail disabling, database error, etc.): 

```
{
    "detail": "Account deletion failed because of {reasons}"
}
```

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Sep 20, 2018, 14:03

@jlprevatt Regarding our offline discussion... 

"Recreating" an account should for all intents and purposes be treated like we are creating/adding/registering/whatever-we-call-it-ing it _for the very first time_. We do not retain enough information after deleting an account from our system to meaningfully reconstruct past events and images if the user wishes to "recreate" the account in our system at a later date. So, our text should present a clear and consistent message to that point.

**Comment by katherine-black** [comment]
In GitLab by @jlprevatt on Sep 20, 2018, 14:17

@infinitewarp Yep, thanks. There's no "re" there.

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 24, 2018, 21:28

Backend demo: https://asciinema.org/a/4Hk9iBGL9J6jJhJblo0zZCHIj

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 24, 2018, 21:34

marked the task **Verify that after deleting a cloud account, one can recreate the same cloud account and the Cloud Trail trail (and other supporting bits) works as expected.** as completed

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 24, 2018, 21:34

marked the task **Verify that regular users can only delete their own accounts, not accounts for any other users.** as completed

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 24, 2018, 21:34

marked the task **Verify that via the API super users can delete accounts belonging to any account.** as completed

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 24, 2018, 21:35

marked the task **disables the CloudTrail trail in the customer's AWS account** as completed

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 27, 2018, 14:52

Proof that analyze_log tasks for a deleted account doesn't thrown an error:
![image](https://my-gitlab-bucket.s3.amazonaws.com/118967787/2e2c9e63320bc33638bb2bd1d7412bce.png)

I achieved this by re-activating the cloudtrail of a deleted account and then checking the celery logs. The message took about 30 minutes to show up.

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 27, 2018, 16:39

closed via merge request !500

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 27, 2018, 16:41

reopened

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 27, 2018, 16:41

unassigned @werwty

**Comment by katherine-black** [comment]
In GitLab by @cdcabrera on Sep 28, 2018, 22:33

As of 20180928 UI aspect is ready for review, see MR https://gitlab.com/cloudigrade/frontigrade/merge_requests/80

**Comment by katherine-black** [comment]
In GitLab by @cdcabrera on Oct 3, 2018, 16:18

@ironfroggy @elijahd as of 20181003 UI aspect is ready for feature review, see [branch 434-delete-cloud-account](https://gitlab.com/cloudigrade/frontigrade/tree/434-delete-cloud-account)

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 8, 2018, 12:28

Found an issue related to the AC criteria:

```Verify that if the customer has already disabled our access into their AWS account (by removing or changing their Policy or Role), we can still successfully delete our data even though that means we cannot disable the customer's Cloud Trail trail. (This should produce a warning in our logs.)```

When I disabled the policy before deleting an account I got this error message:

![2018-10-08-delete-disabled-acct-1](https://my-gitlab-bucket.s3.amazonaws.com/118967787/c3f0e562e63fed2ed62520728133937f.png)

**Comment by katherine-black** [comment]
In GitLab by @jlprevatt on Oct 15, 2018, 10:42

The new "delete accounts" section has been rolled into the main doc. @werwty has reviewed the text a couple of times (can you add your approval in the comments here as the SME for this issue?). @infinitewarp  we went back and forth on the NOTE text about the trail and decided to get a second opinion; see if you think it is TMI and will confuse vs. help the average user. @cdcabrera has also glanced at some of the text, but it should have a proper UX/UI review/approval.

Changes (also in AC): 
- new delete account section: https://docs.google.com/document/d/1O2vBNGkP8zRLRzdrbWb9C8RpkBDFGpmbImuipmo7HcA/edit#heading=h.8bh0g15nbppa
- change to the policy table info:
https://docs.google.com/document/d/1O2vBNGkP8zRLRzdrbWb9C8RpkBDFGpmbImuipmo7HcA/edit#heading=h.5oep4fgdrh5

Lastly, a couple of suggested GUI changes that arose during discussions are noted in the new frontigrade#85 enhancement issue.

**Comment by katherine-black** [comment]
In GitLab by @werwty on Oct 15, 2018, 10:47

@jlprevatt The delete documentation changes looks good to me.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Oct 15, 2018, 13:51

Overall, the updated docs look good to me too!

I think the NOTE text is okay as written, but if you think it's TMI, I have no strong opinion about keeping it.

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 17, 2018, 09:22

marked the task **Verify that a UI element exists to delete a cloud account** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 17, 2018, 09:22

marked the task **Verify that clicking the element presents a typical confirmation modal before actually proceeding to delete** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 18, 2018, 11:34

marked the task **removes its instances activity from the daily instance reporting/dashboard api** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 18, 2018, 11:34

marked the task **removes it from the cloud account summary reporting/dashboard api** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 18, 2018, 11:35

marked the task **Verify that deleting a cloud account:** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 18, 2018, 11:41

marked the task **New StopLogging action for policy added to "How Cloud Meter uses the IAM policy" table https://docs.google.com/document/d/1O2vBNGkP8zRLRzdrbWb9C8RpkBDFGpmbImuipmo7HcA/edit#heading=h.5oep4fgdrh5k** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 18, 2018, 11:52

marked the task **Verify that if the customer has already disabled our access into their AWS account (by removing or changing their Policy or Role), we can still successfully delete our data even though that means we cannot disable the customer's Cloud Trail trail. (This should produce a warning in our logs.)** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 22, 2018, 13:00

marked the task **New Deleting Cloud Meter accounts section (and subsections) https://docs.google.com/document/d/1O2vBNGkP8zRLRzdrbWb9C8RpkBDFGpmbImuipmo7HcA/edit#heading=h.8bh0g15nbppa** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 22, 2018, 13:01

marked the task **Documentation additions/changes are complete/reviewed** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 22, 2018, 13:51

marked the task **Verify docs/ui have 'cloudtrail:StopLogging' in the aws cloudigrade policy** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 25, 2018, 13:12

marked the task **Verify that when Cloud Trail processes a message and encounters an account that is not in our system, we skip processing of that message and successfully delete it from the queue.** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 25, 2018, 13:30

marked the task **Verify docs/strings/wordigrade have upgraded verbiage for the button and confirmation alert.** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 25, 2018, 13:31

marked the task **Verify that in the UI, super users impersonating other users do not have access to the delete button.** as completed

**Comment by katherine-black** [comment]
In GitLab by @ironfroggy on Oct 25, 2018, 13:32

closed
