### ISSUE TITLE
Archive cloud accounts

### ISSUE THREAD

**Issue by ghost** [cloudigrade/cloudigrade#442]
In GitLab by @infinitewarp on Jul 20, 2018, 18:27

## Summary

As a customer API client, I want to archive my cloud account so that it is no longer tracked but still reported.

## Acceptance Criteria

- [ ] Verify that an API exists to archive a cloud account
- [ ] Verify that archiving a cloud account:
    - [ ] removes the CloudTrail trail in the customer's AWS account
    - [ ] records "power-off" events for any currently running instances so they appear to have stopped.
    - [ ] leaves it in the cloud account summary reporting/dashboard api but with an "archived" state
    - [ ] leaves its instances activity from the daily instance reporting/dashboard api

## Assumptions and Questions

- What happens if a user tries to register an archived account a second time?
- Do we want to allow a user to "unarchive" an archived account? If so, we will have a gap in the reported data that we may not be able to back-fill.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on May 14, 2019, 14:20

closed
