### ISSUE TITLE
Research alternatives to copying EBS snapshots for inspecting customer files

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#51]
Dan suggests that we may be able to use SmartState as a quicker way to access the contents of our customers' AMIs. Spend some time investigating this and any related options we can find in a short time, and report back with findings.

Time box: 1 day

**Comment by ilyavw** [comment]
I spent some time looking into SmartState and some of my previous methods of analyzing an AMI. SmartState needs access to a volume to do its thing, so there is no change in us having to grab ownership of the ami/snapshot and potentially copy it to whatever region we're running in. Unfortunately, at this point it doesn't look like we can simply point SmartState at the volume and have it tell us what it is. We would need a ManageIQ/CloudForms management server running in that zone with the SmartState role enabled, while doable, it seems like overkill to have to use this giant platform to figure out the linux flavor of the ami.

At this point I went back and tried to find alternative ways of finding out the flavor of the installed linux OS, for the most part the simplest route that remains is just looking at `/etc/*-release` or `/etc/*-version` files. Tools like `lsb_release` can also be used in certain situation. Finally some deeper investigation into installed packages and such can give us a clue if the previous methods failed.

At the end of the day I think our best bet will be to create a volume from the ami snapshot, attach it to our inspection container, and have that perform the checks outlined above.
