### ISSUE TITLE
Integrate with RBAC

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#659]
In GitLab by @infinitewarp on Mar 24, 2020, 17:39

## Summary

As a member of the Insights platform, I want cloudigrade to check with RBAC to ensure that the identity associated with the request can perform the requested action. Currently, we simply look for the `'is_org_admin'` header and trust that it is accurate.

This likely involves defining new permissions in [rbac-config's configs dir](https://github.com/RedHatInsights/rbac-config/tree/master/configs).

## Acceptance Criteria

- [ ] Verify a cloudigrade HTTP request from an identity that does not have permission gets a 403 Forbidden.
- [ ] Verify a cloudigrade HTTP request from an identity that does have permission gets a normal response.
- [ ] Document (for our sake) the supposed tribal knowledge around how accounts get assigned roles and permissions in RBAC.
- [ ] Document outcome of a conversation with other platform people about whether or not we should implicitly trust things coming through Kafka.
  - If the answer indicates we should verify RBAC, put these two items in a new story:
    - Verify an action triggered by Kafka logs a warning or info and returns early if the associated identity does not have permission.
    - Verify an action triggered by Kafka behaves normally if the associated identity does have permission.

## Assumptions and Questions

- Should we call RBAC upon every request? Or can we cache the permissions for some length of time?
  - If we cache, for how long? [koku reference implementation defaults to 30 seconds](https://github.com/project-koku/koku/blob/master/koku/koku/rbac.py).
    - Yes, let's try caching for 30 seconds (default) also.
  - If we cache, should we add a caching server (Redis?) to our OpenShift deployments?
    - We like the idea of having Redis, but we don't like the idea of more work in e2e-deploy while they're migrating to AppSRE.
    - Let's see how easy or difficult it is to copy someone else's implementation (see koku).
- Should we gate actions that come through Kafka? Or do we implicitly trust all internal requests?
  - For now, trust internal things, but we need to have a conversation with other platform folks about this.
- Exactly what permissions should we define with RBAC?
  - [insights](https://github.com/RedHatInsights/rbac-config/blob/master/configs/insights.json), [drift](https://github.com/RedHatInsights/rbac-config/blob/master/configs/drift.json), and [patch](https://github.com/RedHatInsights/rbac-config/blob/master/configs/patch.json) simply have one administrator role with one "everything" permission.
  - Yes, let us have just one administrator role with one permission.
- When we define permissions with RBAC, how do we assign/enable any of our users (especially `insights-qa`) the new permissions?
  - Document this process. Probably ask Chris Hambridge.
- Are there any APIs that should be exempt from RBAC? Currently, the `is_org_admin` check lives in `ThreeScaleAuthentication` which is both a default authentication class for DRF and explicitly set in all of our main API views.
  - We will preserve the same set of APIs that need authentication. Nothing more, nothing less.

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Apr 6, 2020, 11:00

re: Trust RBAC identity from kafka
>  Chris Hambridge:
 you should be able to trust the identity from sources as its coming from the 3scale header.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Apr 14, 2020, 09:49

Blocked because of https://github.com/RedHatInsights/rbac-config/pull/56

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Apr 14, 2020, 09:49

In the mean time, until the platform can resolve our requests around RBAC, we will simply continue to use the `is_org_admin` boolean.

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Apr 14, 2020, 11:18

unassigned @katherine-black

**Comment by infinitewarp** [comment]
Closing this because it hasn't come up in any discussion in recent history. We can open a new issue if RBAC ever becomes relevant for cloudigrade.
