### ISSUE TITLE
More aggressive code quality checking

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#66]
As a Doppler developer, I want even more aggressive code quality checking so that I can rest assured that I am writing clean(er?) code.

## Acceptance Criteria 

- [ ] Verify that additional quality checks are being run during CI.
- [ ] Verify that failures in the new checks also fail the pipeline.

## Tech assumptions

- Add and configure one or more of:
  - [Pylint](https://github.com/PyCQA/pylint)
  - [Prospector](https://github.com/landscapeio/prospector)
  - [Bandit](https://github.com/openstack/bandit)
- Side note: Prospector is made by the Landscape.io people, and [Landscape.io](https://landscape.io/) appears to be a dead service. Its website is usually down, but at least Prospector is open source and independently runnable.
- Included in this story is the effort required to evaluate the default rules for the chosen tools and adjust those rules to fit how we want to develop.

**Comment by ilyavw** [comment]
After much discussion, we've come to the conclusion that pylint (the best of the three noted here) will not work for us.
