### ISSUE TITLE
Internal stats API

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#660]
In GitLab by @infinitewarp on Mar 24, 2020, 17:48

## Summary

As a cloudigrade devops, I want to know more about the current state of cloudigrade and its data.

An internal stats endpoint could provide things like total counts of data in our system for eventual display in an internal Prometheus/Grafana dashboard.

## Acceptance Criteria

- [ ] Verify a stats API exists that only supports GET requests
- [ ] Verify that the stats API is not publicly accessible
- [ ] Verify if the platform has a caching solution that we are using it.
- [ ] Verify a new issue exists to track implementing caching solution if Insights platform does not provide one.
- [ ] Verify an issue exists for having this API's data reported in some dashboard.
- [ ] QE to manually verify that this API exists and provides reasonable data.

## Assumptions and Questions

- First, let's investigate Prometheus and understand how it works. Also, are there any standard/open-source libraries we can use for gathering and exposing this data?
  - Consider [InfluxDB](InfluxDB) and have a conversation with Parag because he has experience here.
  - Consider also reaching out to our Cost Management and Koku dev friends for ideas.
- What stats exactly do we want to expose?
  - total counts for each of the model objects, perhaps as a big json dict.
- Should we cache the results to prevent requests from hammering the DB?
  - Ideally, yes, we would use a caching service provided by Insights platform.
  - If Insights platform has a caching service, use it with this initial implementation.
  - If Insights platform does not have a caching service, simply return results with this initial implementation and track a new issue to implement caching later.
- How do we want to prevent outside access?
  - reuse the `internal` API path pattern that we recently added

**Comment by infinitewarp** [comment]
This has been implemented effectively by implementing [django_prometheus](https://pypi.org/project/django-prometheus/). See also:
- https://gitlab.com/cloudigrade/cloudigrade/-/issues/721
- https://gitlab.com/cloudigrade/cloudigrade/-/issues/677
- https://github.com/cloudigrade/cloudigrade/blob/master/cloudigrade/internal/urls.py#L88
