### ISSUE TITLE
Flower for Celery

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#661]
In GitLab by @infinitewarp on Mar 24, 2020, 17:52

## Summary

As a cloudigrade sysop, I would like to have better visibility into what Celery tasks are doing. [Flower](https://flower.readthedocs.io/en/latest/) is a web based tool for monitoring and administrating Celery clusters.

The overall "ask" of this is only to deploy Flower so we can see and interact with its controls. Additional features like Prometheus integration will come later.

## Acceptance Criteria

- [ ] Verify a Flower deployment exists with each of our other clowder deployments
  - [ ] Ephemeral
  - [ ] Stage
  - [ ] Prod
- [ ] Verify routes are available so that we can see the web interface.
  - [ ] Internal only, not part of the public API.
  - [ ] Stage and prod web interfaces are made available via Turnpike using the same doppler-dev group.
- [ ] Verify that the web interface shows accurate and meaningful data.

## Assumptions and Questions

- Our deployment will be like beat and worker in that it will be part of the cloudigrade app, not deployed separately like postigrade.
- QE does not need to build integration tests for this issue.
- koku did this and [may be a reference implementation](https://github.com/RedHatInsights/e2e-deploy/blob/master/templates/hccm-optional/celery-flower.yaml).

**Comment by infinitewarp** [comment]
Blocked until we do https://github.com/cloudigrade/cloudigrade/issues/433 because Flower uses [RabbitMQ Managment Plugin](https://www.rabbitmq.com/management.html) to get info about queues. ([according to the current docs](https://flower.readthedocs.io/en/latest/config.html#broker-api)).

**Comment by infinitewarp** [comment]
https://github.com/cloudigrade/cloudigrade/pull/1105 has merged, and our Celery is now using Redis instead of SQS! 🎉 

I replaced the `blocked` label with `needs-definition` here so we don't forget to discuss this important next step. Also, the RabbitMQ Management Plugin _is_ still referenced by the Flower docs, which is mildly concerning, but I think that's only relevant _if_ you're using RabbitMQ as your broker.

**Comment by abellotti** [comment]
- Chatted a bit with Chris H. yesterday, apparenly Koku no longer uses flower. It was never moved to OCP4.  Koku was only using flower on OCP3 and was using the RabbitMQ broker. They decided to drop flower in OCP4 in favor of using a couple of specific turnpike APIs and moving to Redis. They also did not want to continue managing credential issues and associated CVE updates.
- Latest posted (PyPi) flower is 1.0.0, and that does not support Celery 5.  Apparentlly 1.0.1 supports Celery 5 and that was not  published yet.  Folks have been manually configuring its install from github.com/mher/flower. While we can specify that depencency in pyproject `flower = { git = "https://github.com/mher/flower" }` for builds, we may want to wait for the official 1.0.1 release for our production.

**Comment by abellotti** [comment]
With the latest flower 1.0.1 and celery 5.2.3 we seem to have the same issue as: https://github.com/mher/flower/issues/1157

**Comment by infinitewarp** [comment]
Unfortunately, we are going in another direction since Flower does not appear to be actively maintained for modern Celery/Kombu version support.
