### ISSUE TITLE
Cache/memoize `get_sources_cloudigrade_application_type_id`

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#663]
In GitLab by @infinitewarp on Mar 24, 2020, 18:06

## Summary

As a cloudigrade sysop, I want to reduce unnecessary network calls so that cloudigrade completes work more efficiently. `get_sources_cloudigrade_application_type_id` currently runs every time `create_from_sources_kafka_message` runs and results in another call to sources-api. We do not expect the returned value to change frequently, though it is _possible_ that it could change occasionally. The low rate of changes makes this likely a good candidate for caching or memoizing.

## Acceptance Criteria

- [ ] Verify `get_sources_cloudigrade_application_type_id` only calls sources-api once every X seconds as needed.
  - one hour TTL.
- [ ] Verify the value is not cached if sources-api doesn't return a reasonable value.
  - This may require us to cleverly nest a couple of function calls to raise an exception to prevent caching.
- [ ] Verify we have a way to reset/poison this cached value.
- [ ] Discover and share with the team knowledge about possible platform cache.
  - [ ] If this exists today, have our app use it for this value.
- [ ] All new environment variables are appropriately configurable through e2e-deploy/saas-templates/app-interface yamls

## Assumptions and Questions

- How long should we keep the cached value?
  - one hour
- We could naively memoize in-memory, and that reduce the API calls to one per worker per TTL. Or should we add a caching server (Redis?) to our OpenShift deployments that would be shared among all of our instances?
  - Have a discussion with someone on the platform team about caching servers. Like they provide databases and message queues, they should also provide standard shared caching tools. If this exists, share knowledge with the team and consider using it.
  - When we recently discussed this issue, Chris D suggested that we run our own Redis instance. That's what other teams are doing because there does not appear to be a platform standard caching server.
- Consider [django-cache-memoize](https://pypi.org/project/django-cache-memoize/) or [django-memoize](https://pypi.org/project/django-memoize/).

**Comment by gtanzillo** [comment]
PRs:

[Cache value of get_sources_cloudigrade_application_type_id](https://github.com/cloudigrade/cloudigrade/pull/902)
[[WIP]e2e deploy PR exposing cache settings](https://github.com/RedHatInsights/e2e-deploy/pull/3137)

**Comment by gtanzillo** [comment]
After further discussion with the team regarding the need or value of having a permanent caching service, like Redis, we decided that the overhead of deploying such a service as part of the cloudigrade project in the various OCP environments is much larger than the benefits at this point. That may change later a bigger necessity for a caching service comes up in the future. If that happens, we can revisit this.

For now, the in-memory caching should be enough to satisfy the requirement of this issue
