### ISSUE TITLE
Use a service account for internal calls

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#664]
In GitLab by @infinitewarp on Mar 24, 2020, 18:09

## Summary

As a cloudigrade sysop, I want to use a special internal service account (not always the requesting customer's account) when I perform requests to internal service that are not directly relevant to the customer. For example, `get_sources_cloudigrade_application_type_id` should be customer-agnostic.

## Acceptance Criteria

- [ ] Verify `get_sources_cloudigrade_application_type_id` uses a configured service account
- [ ] TBD Verify other functions use the service account?

## Assumptions and Questions

- Can we even do this? Whom do we work with at the platform level to make this a thing?
- What other calls that we make would benefit from an internal service account?

**Comment by infinitewarp** [comment]
In the past year since originally raising this issue, I haven't heard of any progress being made towards service users on the Red Hat cloud platform. So, I'm closing this issue. If we ever learn of new support with implementation details, we can open a new issue to use it then.
