### ISSUE TITLE
Large data performance test (AWS layer)

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#667]
In GitLab by @infinitewarp on Mar 25, 2020, 10:34

## Summary

As a cloudigrade sysop, I want to be confident that the cloudigrade APIs and tasks will behave well even if a customer's account has many thousands or millions of records in AWS.

![](https://media.tenor.com/images/d9ad574dd082c7c2e3a79c0b97c4cb24/tenor.gif)

We should do something to generate a large number of images, instances, and events **in AWS** and test the various operations in cloudigrade that interact directly with AWS APIs. Any problems, bottlenecks, or slowdowns we find during testing should result in discussion among the team and likely new issues to refactor our code as needed.

## Acceptance Criteria

- [ ] Discover how the various tasks perform when customer accounts have many images, instance, and/or events in AWS.
- [ ] Share results and discuss with team. Document new issues for refactoring if necessary.

## Assumptions and Questions

- With this story, we intend to target perf testing around AWS interactions.
- Start with tens then hundreds of instances before going to thousands of instances. Be aware that this could become expensive.
- Some areas to remember to perf test:
  - initial describe
  - many cloudtrail events in one file
  - many cloudtrail events spread across many files with one or few in each
- What is "a large number" for our data?
  - Let's consider roughly a thousand new instances per day involving roughly ten thousand events per day. Some portion of the events should overlap the previous and next day.
- What does "performs well" actually mean?
  - Aim for low tens of milliseconds.
- Is this a one-time operation? Do we build an extra step in our GitLab CI pipelines for perf testing?
  - We believe routine perf testing belongs to the QE side of the org, not as a step in our regular development process. So, we will initially do this as a one-time help operation and document our process, but we will not bake it in to our standard unit test and build pipeline.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Apr 30, 2020, 10:06

Whoever picks this up, please reach out to Parag and review the performance test plan that he and QE have been working on.

**Comment by infinitewarp** [comment]
IQE already has some automation that works with ~100 images/instances. @paraggit would you confirm that code still runs, and have you seen any particularly interesting issues specifically related to operating at that scale?

**Comment by paraggit** [comment]
@infinitewarp We having longevity tests run daily from the stage environment . currently test is  picking   image count between 1-50 randomly and generate the data. When we started the test around 5 month ago we started with 100 images  then we found following issues..

https://github.com/cloudigrade/cloudigrade/issues/843
https://github.com/cloudigrade/cloudigrade/issues/848
https://github.com/cloudigrade/cloudigrade/issues/845

**Comment by infinitewarp** [comment]
See also: https://docs.google.com/document/d/1bwVXrVn4Okic9DEFY4F0LHSbDZnVKZdHgi0EuPewv6w/edit#

**Comment by infinitewarp** [comment]
We discussed this at backlog refinement and decided to close it because:
- we aren't responsible for stress-testing AWS
- we don't know of any problems that would arise specifically with very large AWS activity
- we already have other issues we're working on to stress-test *our* service with large synthetic data
