### ISSUE TITLE
Run Kafka locally for devs

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#671]
In GitLab by @infinitewarp on Apr 8, 2020, 10:23

## Summary

As a developer, I want to enable data management from Kafka to cloudigrade in my local development environment so that my local testing behaves more consistently.

## Acceptance Criteria

- [ ] Verify documentation exists to run and interact with Kafka locally
  - preferably using shiftigrade and our local minishift instances
- [ ] Verify commands exist (and are documented) to put a few messages on to the Kafka topics
  - [ ] ...for some generated/pre-configured messages
  - [ ] ...for manually created and provided messages
- [ ] Verify a new Django config setting exists specifically for skipping sources-api calls.
  - [ ] ...and that all current sources-api calls are conditionally wrapped by it instead of `ENABLE_DATA_MANAGEMENT_FROM_KAFKA_SOURCES`.
  - [ ] ...and the use is always also "ANDed" with the `DEBUG` setting.
  - [ ] ...and existing uses of `ENABLE_DATA_MANAGEMENT_FROM_KAFKA_SOURCES` are also always "ANDed" with the `DJANGO_DEBUG` setting.
- [ ] Verify another issue exists and is linked here for better handling sources-api in development.
- [ ] Verify that this only applies to *local* development environments, *not* CI/QA/STAGE/PROD.

## Assumptions and Questions

- Do we want to docker-compose up a Kafka instance? Do we want to bring back docker-compose *in general* for running cloudigrade locally?
  - Let's not do this for now.
- Or do we want to add a deployment config in shiftigrade for our local minishift?
  - Let's do THIS instead.
  - Maybe this is an opportunity to clean up shiftigrade? Or at least share findings with the team if you discover issues with how we are currently using shiftigrade and minishift.
- If we enable `ENABLE_DATA_MANAGEMENT_FROM_KAFKA_SOURCES` locally, cloudigrade will still fail when trying to talk to sources-api.
  - We use sources-api for:
    - getting the tree of objects (app, auth, appauth, source, endpoint)
    - setting availability status
  - Should we have a different flag to enable sources-api calls?
    - Yes, let's do this for now so we are working in small iterations.
  - Should we run sources-api locally?
  - Should we build and run a mock/fake sources-api service?
  - Should we use e2e-deploy to get sources-api (and other things) into our local cluster?
    - This is the best solution since it should have some kind of platform support, but we will implement this later, not in this issue.
  - Should we refactor/reimagine shiftigrade to work more closely with e2e-deploy?
  - Since e2e is going away, should we jump over to app-sre instead?

**Comment by abellotti** [comment]
With clowder deployments to Ephemeral as well as local minikube, we get a running copy of Kafka that we can access.  We also have a way to run Kafka separately as documented here: https://github.com/cloudigrade/cloudigrade/wiki/How-do-I-run-Sources-&-Kafka-locally-for-development
