### ISSUE TITLE
Create shared pluggable library for RBAC

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#672]
In GitLab by @infinitewarp on Apr 8, 2020, 10:38

## Summary

As a developer of cloudigrade and other Insights platform services, I want to have a common Python library for interacting with RBAC so multiple projects and teams are not reinventing this wheel.

This is a followup to https://github.com/cloudigrade/cloudigrade/issues/659.

## Acceptance Criteria

- [ ] Verify

## Assumptions and Questions

-

**Comment by infinitewarp** [comment]
Closing this because it hasn't come up in any discussion in recent history. We can open a new issue if RBAC ever becomes relevant for cloudigrade.
