### ISSUE TITLE
Don't support multiple authentications with the same ARN

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#674]
In GitLab by @infinitewarp on Apr 13, 2020, 10:14

## Summary

As a sources-api user, I want to create multiple authentications, each with the same ARN, and have cloudigrade somehow support them.

However, we as cloudigrade need to continue to enforce "one active ARN per account" due to many reasons involving how we interact with AWS. So, we should in this case behave exactly as defined in https://gitlab.com/cloudigrade/cloudigrade/-/issues/668.

## Acceptance Criteria

- [x] Verify creating a source-api authentication with an ARN that cloudigrade already has results in the same AC as https://gitlab.com/cloudigrade/cloudigrade/-/issues/668

## Assumptions and Questions

- This should be a freebie because we expect this to be fully handled by https://gitlab.com/cloudigrade/cloudigrade/-/issues/668 as it does the duplicate AWS Account ID sanity checking.
- Blocked until https://gitlab.com/cloudigrade/cloudigrade/-/issues/668 is complete.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Apr 14, 2020, 10:56

changed title from **{-S-}upport multiple authentications with the same ARN** to **{+Don't s+}upport multiple authentications with the same ARN**

**Comment by katherine-black** [comment]
In GitLab by @werwty on May 4, 2020, 22:33

Documentation of Error codes: https://gitlab.com/cloudigrade/cloudigrade/-/wikis/Error-Codes

Demo of this is included in the #668 demo: https://asciinema.org/a/EcZ3TshySAuRP5UQOA5fluKur

**Comment by werwty** [comment]
No code changes needed- this works as expected:     https://asciinema.org/a/ODrrBjiIiCvCuEyB8qZVZhceT

**Comment by infinitewarp** [comment]
Demo looks good. Thanks!
