### ISSUE TITLE
Run sources-api locally for devs

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#682]
In GitLab by @infinitewarp on Apr 30, 2020, 10:42

## Summary

As a developer, I want to enable integration with sources-api in my local cloudigrade development environment so that my local testing behaves more consistently.

This is a followup to: https://gitlab.com/cloudigrade/cloudigrade/-/issues/666

## Acceptance Criteria

- [ ] Verify a command exists and is documented for starting a local sources-api instance with its own local DB
- [ ] Verify local cloudigrade can be easily configured to use the new local sources-api instance.
- [ ] Verify local cloudigrade successfully reads and writes the local sources-api instance.
- [ ] Verify local sources-api writes to local Kafka instance by default. See: #666 

## Assumptions and Questions

- We do not expect QE to build integration tests for this because it exists strictly for local development only.
- Do we want to adapt/convert e2e deployment configs for sources-api into something that will work in our shiftigrade + minishift setup?
  - Probably not. minishift can be painful, plus rewriting their configs is a lot of work and a very very brittle solution.
- Do we want to try docker-compose?
  - Maybe.
- If we docker-compose, where does the definition live?
  - Try contributing to the sources-api project.
  - If they are not quick to accept, let's just put it in our repo too.
- Where is the documentation for running sources-api?
  - The github repo does not appear to have much.
  - Whoever picks up this issue needs to understand the various config values **and** anything special that needs to live in an AWS account.
  - Whoever picks this up, please contribute to sources-api repo docs with your findings.
  - If they are not quick to accept, let's just put docs for sources-api setup in our repo too.

**Comment by abellotti** [comment]
Wiki Reference for running Sources-Api from source with local copy of Kafka/Zookeeper which might be helpful: https://github.com/cloudigrade/cloudigrade/wiki/how-do-I-run-Sources-&-Kafka-locally-for-development

**Comment by abellotti** [comment]
With the above docs for being able to run sources locally on a dev machine as well as the current ability to deploy the whole lot: sources, kafka, rbac, etc. in an ephemeral namespace and successfully accessing sources there via a port forward or just oc rsh to the sources-api-svc, this issue can now be closed.
