### ISSUE TITLE
Azure: Investigate current sources-api/koku integration

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#707]
## Summary

What are we looking for here? We need to understand how other backing services (like koku, topo inventory, etc.) have been set up to communicate with Azure on behalf of the customer by way of sources-api. Presumably, the customer defined some authentication via sources-api, but we don't know the actual workings of that process. Based on earlier research, we anticipated needing a saml/oath flow which would require the user interacting directly.

We **do not want to take a customer's raw root login/password** for Azure. We would much prefer some access mechanism with limited controls. However, if other c.rh.c services are simply taking the root credentials, maybe we should also for our first-pass implementation.

## Details

Koku (Cost Management) already has some kind of Azure customer account integration via interaction with sources-api. We need to understand how that works and if there is anything we can leverage or reuse for cloudigrade. We also suspect Teamnado's folks (Tramaine Darby and Patrick Easters) also perform some kind of related account/subscription verification with Azure on behalf of the customer.

Of note, @infinitewarp believes that Koku directly accesses Azure through a service account defined by the customer. This likely is not sufficient for cloudigrade's needs, but understanding how sources-api and Koku handle that authentication may be useful for future conversations between cloudigrade and sources-api.

Consider scheduling a call/chat with Koku (probably Doug) and at least all of the cloudigrade devs and QEs for an hour. If we learn things async (email, slack, etc), then at least schedule a time to share notes and discuss with our team.

Desired output: shared notes and discussion including the technical details about Koku's auth integration with Azure via sources-api.

Timebox: 3 day.

**Comment by infinitewarp** [comment]
Also maybe reach out to Tramaine Darby because @infinitewarp has overheard conversations about her team making calls to Azure to perform some kind of related account/subscription verification.

**Comment by katherine-black** [comment]
I spoke with Doug who pointed me toward their public facing docs [here](https://access.redhat.com/documentation/en-us/cost_management_service/2021/html-single/getting_started_with_cost_management/index#assembly-adding-azure-sources). Following through we see that the current koku use case is very much inline with our former spikes that utilized service principals and storage accounts. 

Sources does not appear to have any special relationship with Azure (SAML or otherwise), and appears to simply be a credential key/value store in this case. This isn't ideal, as it does require manual setup on the customers side, but with Azure cloud shell being a thing now that is a bit easier, plus overall this is likely the least complicated implementation.

Additionally, I reached out to Tramaine to see how Teamnado may use it, but it seems their use case is limited to a specialized internal api, and they do not directly interface with customer accounts in any way.

**Comment by infinitewarp** [comment]
Thanks for the notes! lgtm
