### ISSUE TITLE
Use Kafka instead of HTTP to update sources-api status

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#718]
In GitLab by @infinitewarp on Jul 16, 2020, 14:44

## Summary

As a sysop, I want to reduce synchronous waiting operations in cloudigrade. sources-api recently introduced the ability to read from a Kafka topic (we write; they read) for updating an application availability status. We should use this Kafka topic instead of the HTTP API, and we should trust that once we've written to the topic, our end of the update contract has been fulfilled.

See also:

- https://projects.engineering.redhat.com/browse/TPINVTRY-970
- https://github.com/RedHatInsights/sources-api/pull/239

## Acceptance Criteria

- [ ] Verify through code review that cloudigrade no longer uses the sources-api HTTP API to set the availability  status on applications.
- [ ] Verify that creating a cloud account (through sources-api) with valid AWS setup results in sources-api being updated with "available" status. This is the happy path regression test!
- [ ] Verify that creating a cloud account (through sources-api) with invalid AWS setup results it results in sources-api being updated with "unavailable" status. This is the unhappy path regression test!
  - Here are some ideas for making an invalid AWS setup at the time of sources-api object creation:
    - a well-formed ARN that has bogus values (e.g. `arn:aws:iam::000000000000:role/potato-role`)
    - a ARN for a Role that does not actually have a trusted relationship with our AWS account
    - a ARN for a Role that has a policy which is missing some of our required permissions that we verify during setup (e.g. `ec2:CopyImage` is missing)
  - Most if not all of those examples are already included in QE's automated regression test suite.
- [ ] Verify that the above criteria are correct via QE automation.

## Assumptions and Questions

- Implementation should be using an asynchronous celery task that retries using our typical exponential backoff. This should help us confidently deliver the messages even if Kafka is misbehaving and not accepting out messages.
- We do not current do "chaos testing" where we break Kafka. So, code review and unit testing should be sufficient for verifying the retry behavior of the aforementioned celery task.

**Comment by abellotti** [comment]
Pull requests:
- [ ] https://github.com/cloudigrade/cloudigrade/pull/890
- [ ] https://github.com/RedHatInsights/e2e-deploy/pull/3051

**Comment by abellotti** [comment]
was closed by the pr merge, re-opening until things are built/deployed/verified.

**Comment by abellotti** [comment]
@infinitewarp well, seems to be processing them in CI and all happy paths, no KafkaException or BufferError.

![image](https://user-images.githubusercontent.com/5797328/118705897-c88d5a00-b7e6-11eb-96ed-036cb33b4c93.png)

![image](https://user-images.githubusercontent.com/5797328/118705953-d511b280-b7e6-11eb-9d50-25639e43c3d4.png)

![image](https://user-images.githubusercontent.com/5797328/118706062-f1155400-b7e6-11eb-969d-c6372945d80a.png)

![image](https://user-images.githubusercontent.com/5797328/118706095-f7a3cb80-b7e6-11eb-9a5f-84b71b6af500.png)

**Comment by infinitewarp** [comment]
I also just tested manually in CI myself by creating the relevant sources-api objects, waiting a minute, and checking the relevant application availability status, and it correctly updated to `"available"` which indicates that the updated code still works. Thanks! 🙂
