### ISSUE TITLE
Spike: Investigate better configuration of celery tasks and schedules.

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#730]
In GitLab by @katherine-black on Sep 3, 2020, 11:18

## Summary

As a cloudigrade developer, I want know if there is a better way to define celery tasks and schedules.

## Output:
- [ ] Python Notebook or notes documenting a good pattern.

## Assumptions and Questions
- [ ] How do we do different schedules in different environments?
- [ ] What happens to tasks in flight?
- [ ] Is there a supported mechanism or process to reliably and completely rename tasks?

**Comment by infinitewarp** [comment]
See also: [723 Define recurring tasks in migrations, not configs](https://github.com/cloudigrade/cloudigrade/issues/723)
