### ISSUE TITLE
Expand image builder script options

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#742]
In GitLab by @infinitewarp on Oct 1, 2020, 14:42

## Summary

As a cloudigrade QE, I want more image building options so that I can have a comprehensive test suite.

This is a placeholder followup to https://gitlab.com/cloudigrade/cloudigrade/-/issues/735 for expanding the available options for desired image contents. This issue needs to be updated to define features not included in the original implementation.

## Acceptance Criteria

- [ ] Verify

## Assumptions and Questions

- Here are some options to choose from:
  - different archs? x86_64, i386, arm64?
  - different partition types? GUID/GPT, none, LVM?
  - different operating systems? RHEL8, CentOS, other?
  - different os release files?
  - different installed signed packages?
  - different enabled yum/dnf repos?
  - different syspurpose contents?
  - multiple partitions with different contents?

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jan 14, 2021, 11:06

@mpierce is this still relevant if you have already build a script that builds AMIs?

Her answer is: "yes it is" because the current image builder is relatively bare-bones.

**Comment by infinitewarp** [comment]
I'm closing this issue since QE-specific issues will be tracked elsewhere.

@mbpierce FYI in case you cant to copy this over to anything in JIRA.
