### ISSUE TITLE
Be more proactive about alerting on AWS environment changes

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#752]
In GitLab by @infinitewarp on Oct 29, 2020, 11:20

## Summary

As user X, I want Y to happen so that Z.

Intent: continue the conversation about versions, tags, etc. to stop deployments or alert in special ways if the AWS environment is not what we expect when we deploy.

This is a followup to https://github.com/cloudigrade/cloudigrade/issues/738

## Acceptance Criteria

- [ ] Verify

## Assumptions and Questions

- notes from other issue
  - How can we not repair if we're running Ansible scripts that should be idempotent?
    - Idea A: check if the account appears empty before running Ansible scripts. If empty, run as usual. If not empty, run with dry-run/verify flag and report error if there are changes to make.
    - Idea B: set some object's tags in the AWS account with date/version/something that we can bump and check as we do releases. Maybe we can assign these tags to the IAM User we are using to log in to do these operations.
      - date would simply be "when did the ansible script write changes"
- How do we alert on failures? Is Sentry even possible? How do we normally see errors and failures related to deployments?
- Should we have some sanity checks during setup that warn us of emptiness (no schema/tables)?

**Comment by infinitewarp** [comment]
We're closing this issue because it's not exactly relevant following the implementation for https://github.com/cloudigrade/cloudigrade/issues/738
