### ISSUE TITLE
Implement OpenTracing for platform Jaeger tracing server

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#759]
In GitLab by @infinitewarp on Nov 17, 2020, 09:17
https://gitlab.com/cloudigrade/cloudigrade/-/issues/753

## Summary

As a cloudigrade sysop, I want better visibility into the performance and timing of our functionality so that I can understand scaling and performance problems. The Red Hat cloud platform is now running a Jaeger server in at least some of the environments, and leadership has encouraged integrating with it.

See cloud.redhat.com Tech Talk from 2020-11-17.

- https://www.jaegertracing.io/docs/1.7/getting-started/
- https://github.com/jaegertracing/jaeger-client-python/
- https://github.com/opentracing-contrib/python-django/
- https://ci.internal.cloud.redhat.com/app/jaeger/search
- https://www.nginx.com/blog/opentracing-nginx-plus/

## Acceptance Criteria

- [ ] Verify you can see cloudigrade's tracing data in the various internal Jaeger servers

## Assumptions and Questions

- Let's also take a look at Sentry's latest options. Can Sentry filter/limit based on URLs? Previously we enabled Sentry's tracing but had to disable it because it was overwhelmed by requests for our internal service availability check.
- Likely no new test cases for IQE because this is basically a platform dependency.

**Comment by infinitewarp** [comment]
We're not going to do this! We have recently implemented improved support for the Sentry Performance interface. See https://sentry.io/organizations/cloudigrade/performance/
