### ISSUE TITLE
Clean up unused Kafka configs

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#765]
In GitLab by @infinitewarp on Nov 30, 2020, 11:26

## Summary

As a cloudigrade developer, I only want config options exposed that I can actually use. Since trading `python-kafka` with `conflunt-kafka`, we dropped some of the optional configs. We should remove any related unused configs from cloudigrade, e2e-deploy, shiftigrade, and friends.

## Acceptance Criteria

- [x] Verify via code review that the old `python-kafka` configs are no more

## Assumptions and Questions

- No new tests.

**Comment by infinitewarp** [comment]
Looks good to me. Thanks!
