### ISSUE TITLE
Spike: More load testing

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#766]
In GitLab by @infinitewarp on Dec 3, 2020, 10:29

## Summary

As tally service, I want to pound the concurrent API with ~900k accounts and get reasonable responses. The first run on 2020-12-02 for ~21k accounts took ~2.3 hours. There are 24 threads from tally right now, each making requests.

Most of the requests we receive from tally so far have no data in our system. This means we should just do a quick lookup and return. We have another issue to investigate and handle that (see #750). *Let's hold this spike until that work is done.*

We should try to put load on cloudigrade's concurrent API to simulate conditions like what tally will be doing. We should use this exercise to identify possible flaws or bottlenecks in our architecture.

We may need to create many accounts with users with org-admin. Consider talking with Sayan Paul (`Sayan Paul` in slack, MB and Parag know who this is, a teamnado QE) about creating these accounts; he may have useful experience to share.

## Acceptance Criteria

- [x] documented process (even if manual) for executing a large number of requests to the concurrent API similar to tally
- [x] documented results from testing large number of requests
- [x] documented suggestions for performance improvement
- [x] have a conversation with the team to discuss results and define issues to address concerns

Estimated size: Large

## Assumptions and Questions

- Some of the slowness we experienced was likely due to our process that looks up and automatically creates users. We have effectively stopped creating users during the concurrent API request, and that should improve performance at least marginally.
- We are talking about adding an internal API for the Tally service to get a list of valid users/accounts *before* requesting concurrent usage. If we implement that, it would not necessarily improve the performance of concurrent API, but it would reduce the number of requests to that API, thereby reducing the severity of this problem.
  - This API now exists on our side, but we do not know when Tally will start using it. Let's continue the testing path with the assumption that they are *not yet* using this preceding API call.
- @infinitewarp strongly suspects that some of our slowness is caused by the sync writes in Watchtower. We also have future work planned to replace Watchtower (https://github.com/cloudigrade/cloudigrade/issues/786), but we should continue the testing path with the assumption that we are *not yet* implementing that change in the near future.
- @infinitewarp recently had a conversation with an outside team member (TBD update this with contact info) who has access and credentials to a common "perf" environment and AWS account(s). We should consider working with this person, environment, and accounts when exercising these tests.
  - I'm not necessarily advocating for us building out a full and proper perf environment deployment. Only suggesting that we should consider leveraging this if it makes sense.
  - See also https://github.com/cloudigrade/cloudigrade/issues/788. Take a quick look at Pradeep's framework, and if it's an "easy win" for this particular issue, consider using it. Otherwise, let's continue requirements gather discussion for framework support on https://github.com/cloudigrade/cloudigrade/issues/788.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Dec 3, 2020, 11:03

changed title from **More load testing** to **{+Spike: +}More load testing**

**Comment by infinitewarp** [comment]
I'm looking at this issue because SRE onboarding (https://github.com/cloudigrade/cloudigrade/issues/905) requires a documented process for load/performance testing in prod-like environments. The end result may differ from what was originally defined above, but the spirit of the investigation and work is the same.

**Comment by infinitewarp** [comment]
I documented my recent manual/ad-hoc load test exercise in app-interface [here](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/37342). Testing for the concurrent API included many requests serially, parallelism from 1 to 20 simultaneous requests, some with authentication for a valid user with data, and many more for an unknown user.

The general results matched my expectations:
- Using Watchtower with `use_queues=False` to send logs to AWS CloudTrail contributes to ~11% of individual response times when the user is not know to cloudigrade and ~14% when the user is known and has data.
- Lack of HPA is a definite bottleneck for parallelism. Throughput increased quickly before plateauing as the pods are maxed out.

My recommendations:
- Find some kind of asynchronous logging alternative to Watchtower.
- Continue to put pressure on the platform to implement working HPAs.

**Comment by katherine-black** [comment]
Looks good, closing. Thank you!
