### ISSUE TITLE
ConcurrentUsage should not predict the future

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#767]
In GitLab by @werwty on Dec 10, 2020, 10:03

## Summary

As a cloudmeter customer I want cloudmeter to behave in a easily predicable way when I make concurrent usage calls.

Currently for ConcurrentUsage if the user gives a start/end date in the future, we stub out the empty values. We should instead consider returning a 400 with a relevant error message since we cannot predict the future. 

## Acceptance Criteria

- [x] Verify that a start/end date in the future returns 400 and includes a message like "dates cannot be in the future" (wordsmithing TBD)
- [x] Verify past dates and "today" continue working unchanged
- [x] Verify new test cases in IQE to include various dates with past/today/tomorrow/future.

## Assumptions and Questions

- When we say "in the future", we mean:
  - "after tomorrow" for the end date is not allowed because the end date is exclusive and we allow "tomorrow" to mean "get me the data through today".
  - "any future date" for the start date because asking for data "tomorrow" or later makes no sense.

**Comment by infinitewarp** [comment]
Verified using old dates still works but using future dates fails with expected 400 response.

```
➜  ~ http --auth insights-qa --proxy="https:http://squid.corp.redhat.com:3128" \
 https://cloud.stage.redhat.com/api/cloudigrade/v2/concurrent/ start_date=="$(gdate --iso-8601=date --date='-2 days')" end_date=="$(gdate --iso-8601=date --date='-2 days')"
HTTP/1.1 200 OK
...

{
    "data": [],
    "links": {
        "first": "/api/cloudigrade/api/cloudigrade/v2/concurrent/?end_date=2021-02-27&limit=10&offset=0&start_date=2021-02-27",
        "last": "/api/cloudigrade/api/cloudigrade/v2/concurrent/?end_date=2021-02-27&limit=10&offset=0&start_date=2021-02-27",
        "next": null,
        "previous": null
    },
    "meta": {
        "count": 0
    }
}
```
```
➜  ~ http --auth insights-qa --proxy="https:http://squid.corp.redhat.com:3128" \
 https://cloud.stage.redhat.com/api/cloudigrade/v2/concurrent/ start_date=="$(gdate --iso-8601=date --date='+2 days')"
HTTP/1.1 400 Bad Request
...

{
    "start_date": [
        "start_date cannot be in the future."
    ]
}
```
```
➜  ~ http --auth insights-qa --proxy="https:http://squid.corp.redhat.com:3128" \
 https://cloud.stage.redhat.com/api/cloudigrade/v2/concurrent/ end_date=="$(gdate --iso-8601=date --date='+2 days')"
HTTP/1.1 400 Bad Request
...

{
    "end_date": [
        "end_date cannot be in the future."
    ]
```
```
➜  ~ http --auth insights-qa --proxy="https:http://squid.corp.redhat.com:3128" \
 https://cloud.stage.redhat.com/api/cloudigrade/v2/concurrent/ start_date=="$(gdate --iso-8601=date --date='+2 days')" end_date=="$(gdate --iso-8601=date --date='+2 days')"
HTTP/1.1 400 Bad Request
...

{
    "end_date": [
        "end_date cannot be in the future."
    ],
    "start_date": [
        "start_date cannot be in the future."
    ]
}
```

**Comment by infinitewarp** [comment]
@paraggit and @mbpierce would you confirm if this is done or being tracked in gitlab.cee.redhat.com?
> Verify new test cases in IQE to include various dates with past/today/tomorrow/future.

**Comment by infinitewarp** [comment]
IQE testing being tracked here: https://projects.engineering.redhat.com/browse/SMQE-294
