### ISSUE TITLE
Check for AWS marketplace product codes

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#770]
In GitLab by @infinitewarp on Dec 16, 2020, 17:25

## Summary

As a cloudigrade user, I want my use of AWS Marketplace images to be quickly identified without having to attempt and fail the image copying process.

AWS Marketplace images often (but **not always**) have product codes set on them that are visible when describing the image. We should look for these values when initially describing images so that we can more efficiently short-circuit the inspection process. Here's an example of a product code on a RHEL and an Ubuntu image:

```
aws ec2 describe-images --image-ids ami-054a9dc6c144331a0 ami-05a863ed7a892f67c | jq ".Images[] | {ImageId, Name, ProductCodes}"
{
  "ImageId": "ami-054a9dc6c144331a0",
  "Name": "SAP-7.6_E4S_HA_US_HVM-20190221-x86_64-2-Hourly2-GP2-5cca0aac-b678-4e46-80e2-344cfed26a62-ami-0e49c67162a6956e9.4",
  "ProductCodes": [
    {
      "ProductCodeId": "5hrdl17aakjait06bf0mq7bz6",
      "ProductCodeType": "marketplace"
    }
  ]
}
{
  "ImageId": "ami-05a863ed7a892f67c",
  "Name": "f677d7db-f192-40b4-beb8-e014501ebadc.aced0818-eef1-427a-9e04-8ba38bada306.DC0001",
  "ProductCodes": [
    {
      "ProductCodeId": "a8jyynf4hjutohctm41o2z18m",
      "ProductCodeType": "marketplace"
    }
  ]
}
```

## Acceptance Criteria

- [ ] Verify that when an AWS image from the AWS Marketplace having relevant product codes is used, cloudigrade promptly saves its model with `aws_marketplace_image` set to `True` and the `status` set to `INSPECTED`.
- [ ] Verify a new attribute `product_codes` exists on the `AwsMachineImage` model and is visible from both the public `/images/` API and the internal `/awsmachineimages/` API.
- [ ] Verify QE automation checks for this new value on at least one test.

## Assumptions and Questions

- Should we add to `AwsMachineImage` a new nullable `JSONField` (or other type?) with the contents of the product codes?
  - Yes, let's do this!
  - This could be immediately useful for QE to cross-reference known values from the AWS image that originated in AWS Marketplace.

**Comment by infinitewarp** [comment]
demo: https://asciinema.org/a/5B4ce8MFcwx5CxPrKuaRuwS4o

**Comment by infinitewarp** [comment]
demo: https://asciinema.org/a/439027

**Comment by katherine-black** [comment]
Demo looks good, thank you, closing.
