### ISSUE TITLE
Support certificate auth for internal Turnpike requests

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#778]
In GitLab by @infinitewarp on Jan 19, 2021, 10:12

## Summary

As a cloudigrade developer and sysop, I want to access the internal APIs through Turnpike using a trusted x.509 certificate and mTLS (mutual authentication) so that I don't have to manually fetch and manipulate cookies.

See also:
- [Turnpike docs: X-RH-Identity](https://github.com/RedHatInsights/turnpike/blob/master/docs/_index.md#x-rh-identity)
- [Turnpike: configure stage rhsm endpoints for QE client cert](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/9639/diffs)

## Acceptance Criteria

- [x] Verify our internal APIs handle requests authenticated using only a certificate and no cookies
  - For anything internal that does not *require* the account number.
- [x] Verify documentation exists for creating your certificate and using it.
  - Consider updating the "how do I reach these APIs" wiki page
- [x] Verify with an automated test in IQE that at least one internal API can be reached using a certificate, and the certificate file itself lives in Vault.
  - Consider simply HTTP GETing `/internal/api/cloudigrade/v1/`
  - We might need to think about if that is an appropriate API to use for testing this type of auth. When you are implementing this test, please reach out to a dev to discuss and sanity-check.

## Assumptions and Questions

- @pakamble found the links above and may be able to provide or find more information through his QE contacts.
- How can I create a valid certificate for local use?
  - Probably use https://ca.corp.redhat.com/ca/ee/ca/
- How precisely do I use a local certificate file to authenticate my requests from command-line programs like `curl` or `http`?
  - See the `MAN` pages. :slight_smile: 
- Is this actually completely supported fully by the platform? This message in the docs suggests not. See https://github.com/RedHatInsights/turnpike/blame/master/docs/_index.md#L82
- If we discover after starting this issue that the platform does not fully support this method of authentication, we accept that we may stop work and eject this from the current sprint.

**Comment by werwty** [comment]
Docs on how to create the cert: https://github.com/cloudigrade/cloudigrade/wiki/Turnpike-Cert-Creation
Updated 'How do I Reach These APIs': https://github.com/cloudigrade/cloudigrade/wiki/How-do-I-reach-these-APIs#internal-apis

Demo request:
```
[bz@localhost cert-keys]$ curl --proxy "http://squid.corp.redhat.com:3128" --cert cloudigrade-turnpike.crt --key cloudigrade-turnpike.key https://mtls.internal.cloud.stage.redhat.com/api/cloudigrade/internal/api/cloudigrade/v1/ | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2224  100  2224    0     0   3223      0 --:--:-- --:--:-- --:--:--  3223
{
  "accounts": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/accounts/",
  "users": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/users/",
  "usertasklocks": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/usertasklocks/",
  "cloudaccounts": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/cloudaccounts/",
  "instances": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/instances/",
  "instanceevents": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/instanceevents/",
  "machineimages": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/machineimages/",
  "runs": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/runs/",
  "machineimageinspectionstarts": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/machineimageinspectionstarts/",
  "concurrentusages": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/concurrentusages/",
  "concurrentusagecalculationtasks": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/concurrentusagecalculationtasks/",
  "instancedefinitions": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/instancedefinitions/",
  "awscloudaccounts": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/awscloudaccounts/",
  "awsinstances": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/awsinstances/",
  "awsmachineimages": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/awsmachineimages/",
  "awsmachineimagecopies": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/awsmachineimagecopies/",
  "awsinstanceevents": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/awsinstanceevents/",
  "azurecloudaccounts": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/azurecloudaccounts/",
  "azureinstances": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/azureinstances/",
  "azuremachineimages": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/azuremachineimages/",
  "azureinstanceevents": "https://internal.cloud.stage.redhat.com/internal/api/cloudigrade/v1/azureinstanceevents/"
}
```

Note that the mtls url is not yet available for prod, see: https://issues.redhat.com/browse/RHCLOUD-12091

mtls is not (and there are no plans on it being) rolled out for CI.

As always, turnpike is not available in QA, environmental differences is documented in https://github.com/cloudigrade/cloudigrade/wiki/How-do-I-reach-these-APIs#internal-apis

**Comment by infinitewarp** [comment]
Docs look good, and I verified I'm able to reach the mtls.internal.cloud.stage.redhat.com internal API paths using cert and key files.

@paraggit and @mbpierce would you confirm that you have the following covered? I know there were conversations last week about the Vault storage, but I wasn't sure if it was 100% resolved and complete.
> an automated test in IQE that at least one internal API can be reached using a certificate, and the certificate file itself lives in Vault

**Comment by paraggit** [comment]
@brad yes we have an automation tests which is calling internal api "/cloudigrade/v1/".  We kept certificate and key  text in vault and  we are generating  file at runtime from that text and providing it to the api call. Find the below code of automation test.

https://gitlab.cee.redhat.com/insights-qe/iqe-cloudmeter-plugin/-/blob/master/iqe_cloudmeter/tests/test_api_access_using_turnpike.py
