### ISSUE TITLE
Clowderize part 1: bonfire + ephemeral environments for devs

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#779]
## Summary

As a customer of the platform, I want to have an ephemeral environment because it is what is recommended and because CI/QA is being shut down. We also want to support it for downstream teams like tally. Also there's a push for using the clowderized configs for stage and prod deployments.

As a *first step* towards the clowderized promised land, we need to update cloudigrade and our day-to-day development practices to work with bonfire and the new ephemeral environment cluster. This issue specifically addresses those challenges.

This likey includes:

- [Setting up your ephemeral credentials](https://internal.cloud.redhat.com/docs/devprod/ephemeral/01-onboarding/#onboarding-steps)
  - [Example MR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/14080/diffs)
- [Installing bonfire](https://internal.cloud.redhat.com/docs/devprod/ephemeral/01-onboarding/)
- [Reserving an environment](https://internal.cloud.redhat.com/docs/devprod/ephemeral/01-onboarding/#reservingreleasing-namespaces)
- [Deploying the environment](https://internal.cloud.redhat.com/docs/devprod/ephemeral/02-deploying/#deploying-with-bonfire)
- [Configuring 3scale](https://internal.cloud.redhat.com/docs/devprod/ephemeral/03-frontend/#an-ephemeral-deployment-of-the-3scale-gateway)

How do we deal with secrets? An idea to deal with secrets: for each "ephemeral" reservation slot we create a separate persisted set of credentials, and we simply reference them by number whenever we need to use an "ephemeral" reservation. This would be mean not having to create, rotate, and persist keys during the deployment process. 

How do we deal with the problem of different "ephemeral" environments possibly sharing the same backend AWS account? @katherine-black may be able to dig up the work she started months ago for applying IAM policies to each of the created users/roles. Why would we want this? Restricting permissions to the actors being used for each ephemeral environments protects the overall account from a misbehaving deployment. We don't want one bad deployment destroying the others' objects in AWS. We don't have a hard technical requirement of implementing this kind of restriction, but if we can do it right we should.

## Acceptance Criteria

- [x] cloudigrade can be deployed to the ephemeral environment cluster using standard bonfire commands
- [x] our wiki explains the required commands to set up, deploy, and manage cloudigrade in the ephemeral environment cluster via bonfire
- [x] All team members (devs and qes) have demonstrated ability to set up, use, and tear down cloudigrade in the ephemeral environment cluster via bonfire
  - [x] @abellotti 
  - [x] @katherine-black 
  - [x] @infinitewarp 
  - [x] @paraggit 
  - [x] @gtanzillo 
- [ ] IQE is updated to be able to use ephemeral environments based on configuration.

## Assumptions and Questions

- As of 2021-08-16 following several discussions over the last few weeks, we are cutting the original defined scope of this issue to include only deploying via bonfire to ephemeral environments for local development. The remaining scope to make stage and prod work have been moved to https://github.com/cloudigrade/cloudigrade/issues/780.
- The rebuild of our templates and variables should allow us to reuse a single AWS account for multiple cloudigrade environments. For example, we can use base names such as "ephemeral01" and "ephemeral02" and the various configs will be templated out accordingly.
  - Yes! Our new Ansible playbook mid-hook and updated Django configs should be sufficiently name-driven. If you set the appropriate env var, it'll all switch names accordingly for the various AWS entities, etc.
- Do we have access to a secrets vault?
- This assumes we have simple access to a postgresql instance and connecting to it is trivial.
  - This assumes simple and predictable hostname/username/password for that instance *or* that there already exists a pattern for getting them *or* that the RDS instance is declared in YAML like stage/prod. We may expect environment variables coming in somewhere if it's YAML-driven.
  - This assumes the configuration will follow the same general pattern as in stage/prod, including the option for TLS since TLS will soon be required in stage/prod.
- Double check that sources-api has clowderized and is ready for us to pull in as a dependency. Ditto for Kafka, RDS, and CloudWatch.
- If we find gaps in platform documentation, we must urge that their owners update and correct them.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Jan 22, 2021, 11:30

removed the relation with iqe-cloudmeter-plugin#12

**Comment by abellotti** [comment]
Looks like all the internal docs for clowder/bonfire/ephemeral are in the new place [Clouddot Platform Documentation](https://clouddot.pages.redhat.com/docs/dev/index.html)
with the relevant docs for this issue here:
- [Backend](https://clouddot.pages.redhat.com/docs/dev/getting-started/local/backend.html)
- [Ephemeral Environments](https://clouddot.pages.redhat.com/docs/dev/getting-started/ephemeral/index.html)
- [Migrating an App to Clowder](https://clouddot.pages.redhat.com/docs/dev/getting-started/migration/index.html)

**Comment by abellotti** [comment]
Living document as the baby steps are done: [Setting Ephemeral Environment](https://docs.google.com/document/d/1x2lgyH0lxEivrClbWvbvm5CLrZMUMD_lcmuUTSXmWLA/edit)

**Comment by abellotti** [comment]
Baby Steps (Ephemeral/Clowder/Bonfire Deployment):
- [ ] Get Ephemeral Credentials
- [ ] Create the cloudigrade/deploy/clowdapp.yaml
- [ ] Update cloudigrade to use [Python Library to Clowder](https://github.com/RedHatInsights/app-common-python) to access details about the deployment
- [ ] Test above with Bonfire/Ephemeral

Growing Up Steps (App-SRE Deployment):
- [ ] Copy cloudigrade/deploy/clowdapp.yaml to service/app-interface/data/services/insights/cloudigrade/deploy-clowder.yml
- [ ] cloudigrade/build_deploy.sh and cloudigrade/pr_check.sh for the App-SRE CI/CD Pipeline
- [ ] service/app-interface/data/services/insights/cloudigrade/build.yml  - This tells App-SRE how to build

After this last step is done, App-SRE builds via Jenkins and pushes to Quay.

**Comment by abellotti** [comment]
Issues found that we'll need fixing for proceeding:
- [ ] https://issues.redhat.com/browse/RHCLOUD-15015

**Comment by abellotti** [comment]
Formal documentation here: [Deploying Cloudigrade to the Ephemeral Cluster](https://github.com/cloudigrade/cloudigrade/wiki/Deploying-Cloudigrade-to-the-Ephemeral-Cluster)

**Comment by infinitewarp** [comment]
IQE update will come later according to @paraggit on 2021-08-23.

**Comment by infinitewarp** [comment]
Since everyone has successfully used the new code and process to deploy to the ephemeral environment, it's time to close this one. Thanks everybody!
