### ISSUE TITLE
Clowderize part 2: complete with stage and prod deployments

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#780]
## Summary

As a customer of the platform, I want to have clowderized deployments because the platform requires them.

As a *second step* towards the clowderized promised land, we need to update cloudigrade's stage and prod deployments to use the new clowder-based flow completely. This extends the work for local development to use ephemeral environments in https://github.com/cloudigrade/cloudigrade/issues/779.

This likely includes:

- copy `cloudigrade/deployment/clowdapp.yaml` to `service/app-interface/data/services/insights/cloudigrade/deploy-clowder.yml`
  - Why exactly? Is this a copy or a move? Should two disparate versions exist?
  - TODO Find and link to relevant docs here.
- `pr_check.sh` exists and is used by AppSRE automation
  - See also [App-Interface Developer Guide](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-interface/developer.md)
  - This also means we're probably abandoning some of our GitHub actions.
  - This also means we're probably abandoning release tags.
  - This also means we're probably abandoning semantic versions.
- an "ephemeral deploy target" exists in app-interface
  - See also [Deploying using app-interface configs (used by pr_check.sh)](https://clouddot.pages.redhat.com/docs/dev/getting-started/ephemeral/deploying.html#_deploying_using_app_interface_configs_used_by_pr_check_sh)
- `service/app-interface/data/services/insights/cloudigrade/build.yml` exists to tell App-SRE how to build
  - After this last step is done, App-SRE builds via Jenkins and pushes to Quay.
- since we're changing all our configs anyway, let's also enable RDS SSL/TLS connection. This is being handled in https://github.com/cloudigrade/cloudigrade/issues/994

## Acceptance Criteria

- [x] stage deployment is powered by new clowerized configs instead of e2e-deploy and saas-templates
- [x] prod deployment is powered by new clowerized configs instead of e2e-deploy and saas-templates
- [x] old ci/qa deployments from e2e are disabled
- [x] our wiki docs are updated as needed

## Assumptions and Questions

- Do we need to update something with 3scale since clowder demands port 8000?
- Completing this work may conveniently check a few required items for onboarding.
  - for reference: [Cloud meter Acceptance Criteria Checklist](https://docs.google.com/spreadsheets/d/1mgiQA2dG4bnijCTlaBmKC5Ns7-AjMiPVhStQQokWtz0/edit#gid=0)

**Comment by katherine-black** [comment]
Blocked until IQE tests are stabilized.

**Comment by infinitewarp** [comment]
The ACs look good. 🎉  Thank you so much @katherine-black for shepherding all our config changes and scripts through the various new-to-us processes!
