### ISSUE TITLE
Fetch the ARN from sources via username field instead of password field

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#781]
In GitLab by @katherine-black on Jan 26, 2021, 12:02

## Summary

As a cloudigrade sysop, I want cloudigrade to continue operating with sources-api following their change to ARN storage. This means we must start reading the username property **instead of** the password property when setting up the cloud account.

## Acceptance Criteria

- [x] Verify in CI environment that sources-api interaction for creating sources for cloud accounts still works
- [x] Verify in CI environment that sources-api interaction for updating a source's ARN still works
- [x] Verify we have a clear and concise schedule for release.
  - Why? It sounds like we have to release at the same time sources-api releases or else things will break.

## Assumptions and Questions

- The first notice we received about this breaking change is the email attached below.
  - @infinitewarp to reach out to folks and try to learn why we were not notified or consulted sooner.
- See internal issue for sources here: https://issues.redhat.com/browse/RHCLOUD-11834
- @pakamble looked briefly at the latest sources-api in CI environment, and they appear to have an updated openapi definition for v3.1.
  - We should check to see if/how this affects the version we are using.
- Based on our understanding of the sources-api implementation, it is **not** backwards-compatible because the migration only once copies the "password" to the "username", and this means those instances will have stale data going forward. We cannot conditionally check one property then the next. There does not appear to be a major version update.
  - @infinitewarp to reach out to folks and make sure we understand the blocking nature of this change. Also gather schedule information so we can minimize the amount of time the API is broken.
- If we are going to test/verify in CI or QA, this effectively blocks our in-progress migration to github wherein we are effectively abandoning the old CI and QA environments (because we are abandoning e2e-deploy).
- This implies changes to IQE since some of the API calls have changed.

```
Subject: [Important] Sources service - Upcoming change to ARN authentication
To: <smqe@redhat.com>
Cc: Richard Vsiansky <rvsiansk@redhat.com>, Drew Bomhof <dbomhof@redhat.com>


Hi all,

As the ARN is not considered to be a secret, it was decided that when creating authentication for a source, the ARN value should be stored in the "Authentication username" attribute instead of the "Authentication password" attribute. 

This change will affect both sources UI and API and you can already test and integrate with it in the CI environment. The UI now shows the ARN when editing the source (it was hidden as password before the change). 

We plan to promote this to QA and STAGE after both Subwatch and Cost-management teams finish their modifications (if needed) and agree to go ahead.

Please keep us updated if you have any questions or made the changes so we can go ahead and promote it to QA/STAGE.

Thanks!
Zvika.
```

**Comment by werwty** [comment]
Demo: https://asciinema.org/a/g48fGAk6Ii50gzx23cwgNNLI9

Changes are in stage. 

As far as release into prod goes: we're good to release to prod- we default to getting the arn from the `username` field, but if it isn't there we also check the `password` field. We are not dependant on a sources release to keep working.

**Comment by katherine-black** [comment]
All demos check out, thank you! Closing.
