### ISSUE TITLE
Deadlock detected while running IQE test suit.

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#782]
In GitLab by @pakamble on Jan 28, 2021, 09:23

## Summary

Deadlock detected while running IQE test suite. Same issue has occurred in the past few times. 
Following error is reported by Sentry application and from preliminary investigation its seems issue around "accounts" API. 

[OperationalError](https://sentry.io/organizations/cloudigrade/issues/2183975274/?referrer=slack) 

```Deadlock detected
DETAIL:  Process 4884 waits for ShareLock on transaction 9371702; blocked by process 4880.
Process 4880 waits for ShareLock on transaction 9371705; blocked by process 4884.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (0,51) in relation "api_cloudaccount"
environment
stage
release
stage
```
  

## Steps to Reproduce
This issue has seen during the run of IQE test suit and in this suite there are multiple consecutive events of sources creation and deletion operation. This may leads to the this deadlock situation. To reproduce this issue we can run IQE regression suite. 

## Expected Result

- IQE tests run should pass all the assertion criteria and it  should not report any Failures and Exception in the context of cloudmeter application.

## Actual Result

- Deadlock is detected while running IQE tests runs and its seems in the context of cloudmeter application. 

## Additional context

- This issue has seen in the past on stage environment.
- This [Deadlock](https://sentry.io/organizations/cloudigrade/issues/2094962059/?referrer=slack) issue also seen in the QA/CI environment in the past.
- Sometimes when this happens, the source-api's application remains in an "unknown" state. This would imply that our cloud account setup failed and cloudigragrade may not have compeleted processing to notify sources-api.
- Side effect of this issue is ARN is not get cleared from cloudigrade end even though associated source is deleted.
```shell
% http --verify=no --auth rhswatchqe:redhat https://cloud.stage.redhat.com/api/cloudigrade/v2/accounts/
``` 
```json
{
    "data": [
        {
            "account_id": 482,
            "cloud_type": "aws",
            "content_object": {
                "account_arn": "arn:aws:iam::448555927204:role/cm-stage-role",
                "aws_account_id": "448555927204",
                "aws_cloud_account_id": 483,
                "created_at": "2021-01-28T09:01:29.278987Z",
                "updated_at": "2021-01-28T09:01:32.198094Z"
            },
            "created_at": "2021-01-28T09:01:29.286156Z",
            "is_enabled": true,
            "name": "aws-account-448555927204",
            "platform_application_id": 7262,
            "platform_authentication_id": 3936,
            "platform_source_id": 8499,
            "updated_at": "2021-01-28T09:01:29.286179Z",
            "user_id": 447
        }
    ],
    "links": {
        "first": "/api/cloudigrade/api/cloudigrade/v2/accounts/?limit=10&offset=0",
        "last": "/api/cloudigrade/api/cloudigrade/v2/accounts/?limit=10&offset=0",
        "next": null,
        "previous": null
    },
    "meta": {
        "count": 1
    }
}

``` 
Looking for associated sources for this account.

```shell
%http --verify=no --auth rhswatchqe:redhat https://cloud.stage.redhat.com/api/sources/v3.0/sources/8499/
```
```json
{
    "errors": [
        {
            "detail": "Record not found",
            "status": "404"
        }
    ]
}
```

**Comment by werwty** [comment]
LGTM, we'll keep an eye out for future deadlock problems and open new issues as needed
