### ISSUE TITLE
Stop handling source delete messages from sources-api

### ISSUE THREAD

**Issue by werwty** [cloudigrade/cloudigrade#799]
## Summary

As cloudigrade developer I want to interact with sources as little as possible.

Currently we listen to both the Source destroy and application authentication destroy messages because of a sources bug [0]
This was fixed (yay!) but no one closed the sources issue (boo). This means we do not need to track sources/application/authentication ids anymore, since we were only using those to know when to delete our clount, but it makes life easier for many players to just keep a copy of the IDs for now.

So, let's specifically stop handling the Source destroy but keep handling the Application Authentication destroy.

[0] https://github.com/RedHatInsights/sources-api/issues/179

## Acceptance Criteria

- [x] Verify by code review that we only handle one of the two sources-api delete messages
- [x] Verify that we still have all the relevant sources-api IDs in the models and APIs
- [x] Verify normal sources flow work (regression check)

## Assumptions and Questions

- The QE side of the house likely has no new integration tests.

**Comment by werwty** [comment]
Demo:     https://asciinema.org/a/9o7p5x8XXNNaKUbqQiMtODwQR

**Comment by infinitewarp** [comment]
Based on the demo recording, I've verified the ACs. Thanks!
