### ISSUE TITLE
Setup webhook to auto-trigger plugin tests with stage release

### ISSUE THREAD

**Issue by mbpierce** [cloudigrade/cloudigrade#817]
**NOTE** This is blocked due to limitations in how app-interface/AppSRE manage the deployment process. If we do not have good news and a clear solution by 2021-07-01, let's just close this since we may never be able to implement it as desired.

## Summary

As a cloudmeter dev, I want to trigger the iqe-cloudmeter-plugin test suite to run when changes are released in the stage environment so that I can know if changes cause unforeseen problems.

* Note: Use the following URL to trigger build remotely: https://jenkins-insights-qe-ci.apps.ocp4.prod.psi.redhat.com/job/cm-stage-integration-tests/build?token=<TOKEN_IN_SLACK_DM>
https://jenkins-insights-qe-ci.apps.ocp4.prod.psi.redhat.com/job/cm-stage-integration-tests/configure

## Acceptance Criteria

- [ ] Verify that when cloudmeter changes are successfully built in the stage environment, a webhook triggers the test suite to run.

## Assumptions and Questions

- Since our stage deployments currently require a manual process anyway (manually look up hash, commit and push, create MR, get team member to "lgtm" it, etc.), there's a very small ROI to automating this as opposed to keeping it as another step in that manual process. So, I'm putting the `blocked` label on here until we learn more about if/how we can actually automate stage deployments.

**Comment by katherine-black** [comment]
jfyi, the token was shared in a slack dm with me, if someone else ends up picking this up.

**Comment by infinitewarp** [comment]
This would require visibility into whatever job actually does the deployment and can trigger upon completion of the deployment itself. We don't currently have access to such a thing, which we think has recently migrated to another process using Tekton. So, regrettably, we are closing this issue.
