### ISSUE TITLE
concurrent calculation is mismatch with actual instance count on AWS.

### ISSUE THREAD

**Issue by paraggit** [cloudigrade/cloudigrade#821]
## Summary
Recent concurrent calculation tests has failed due to mismatch count reported with the actual  count.
There were 10 instances created on AWS and  i was expecting "GET /concurrent" API call should report the same but its showing 42 instances count. 

## Steps to Reproduce

Following pastebin doc has the all steps recorded as well as as all possible public API output.
- http://pastebin.test.redhat.com/943533

## Expected Result

- Expected  "GET /concurrent"  API  count is 10.

## Actual Result

- Reported "GET /concurrent"  API  count is 42.

## Additional context
- I had registered only one sources to the stage CRC account (rhswatchqe/redhat) which is belongs to the AWS account ID: 439727791560 (arn:aws:iam::439727791560:role/cm-stage-role).
- GET /accounts API shows list of accounts even if those are not registered with stage CRC account.
```shell
 % http --verify=no --auth rhswatchqe:redhat  "https://cloud.stage.redhat.com/api/cloudigrade/v2/accounts/" | jq ".data[].content_object.account_arn"
"arn:aws:iam::448555927204:role/cm-stage-role"
"arn:aws:iam::439727791560:role/cm-stage-role" << only this account belongs to the right CRC stage account.
"arn:aws:iam::027933477046:role/cloudmeter_automation_role"
"arn:aws:iam::746157280291:role/cloudmeter_automation_role"
``` 

- GET /instances API output is showing all the instances even if those are not associated with the right stage CRC account (rhswatchqe/redhat).
```shell
 % http --verify=no --auth rhswatchqe:redhat  "https://cloud.stage.redhat.com/api/cloudigrade/v2/instances/?limit=1000" | jq '.data[].cloud_account_id' | uniq
641
645
641
649
```

**Comment by infinitewarp** [comment]
The results of the APIs like `/accounts/` and `/instances/` (and others) include data for all cloud accounts that were created by the currently authenticated user (i.e. the Red Hat customer account or tenant). All four of the accounts listed here were created by the same user; so, these APIs appear to be working correctly as intended when making requests as that same user.

I verified by using the internal APIs to look up the cloud accounts in question and found that they share the same user.

the specific AWS cloud accounts:
```
http \
    --proxy="https:http://squid.corp.redhat.com:3128" \
    --cert=cloudigrade-turnpike-stage-2.crt --cert-key=cloudigrade-turnpike-stage-2.key \
    https://mtls.internal.cloud.stage.redhat.com/api/cloudigrade/internal/api/cloudigrade/v1/awscloudaccounts/ limit==100 | \
    jq '[.data | map(select(.account_arn | contains(":448555927204:") or contains(":439727791560:") or contains(":027933477046:") or contains(":746157280291:"))) | .[] | {id, created_at, account_arn} ]'
[
  {
    "id": 642,
    "created_at": "2021-02-17T12:59:43.168081Z",
    "account_arn": "arn:aws:iam::448555927204:role/cm-stage-role"
  },
  {
    "id": 646,
    "created_at": "2021-02-23T12:06:40.078879Z",
    "account_arn": "arn:aws:iam::027933477046:role/cloudmeter_automation_role"
  },
  {
    "id": 650,
    "created_at": "2021-02-25T04:44:03.200194Z",
    "account_arn": "arn:aws:iam::746157280291:role/cloudmeter_automation_role"
  },
  {
    "id": 653,
    "created_at": "2021-03-02T05:48:18.133348Z",
    "account_arn": "arn:aws:iam::439727791560:role/cm-stage-role"
  }
]
```

their related cloud accounts:
```
http \
    --proxy="https:http://squid.corp.redhat.com:3128" \
    --cert=cloudigrade-turnpike-stage-2.crt --cert-key=cloudigrade-turnpike-stage-2.key \
    https://mtls.internal.cloud.stage.redhat.com/api/cloudigrade/internal/api/cloudigrade/v1/cloudaccounts/ limit==100 \
    | jq '[.data | map(select(.object_id | inside(642, 646, 650, 653))) | .[] | {id, object_id, name, created_at, user, platform_source_id}] '
[
  {
    "id": 641,
    "object_id": 642,
    "name": "aws-account-448555927204",
    "created_at": "2021-02-17T12:59:43.171221Z",
    "user": 600,
    "platform_source_id": 13527
  },
  {
    "id": 652,
    "object_id": 653,
    "name": "aws-account-439727791560",
    "created_at": "2021-03-02T05:48:18.136308Z",
    "user": 600,
    "platform_source_id": 15119
  },
  {
    "id": 645,
    "object_id": 646,
    "name": "aws-account-27933477046",
    "created_at": "2021-02-23T12:06:40.081562Z",
    "user": 600,
    "platform_source_id": 14306
  },
  {
    "id": 649,
    "object_id": 650,
    "name": "aws-account-746157280291",
    "created_at": "2021-02-25T04:44:03.202846Z",
    "user": 600,
    "platform_source_id": 14551
  }
]
```

Note that these cloud accounts all have the same user id `600`. This means they were all originally created by the same Red Hat customer account, presumably by interacting with the sources-api while authenticated as the same user. Though we don't store all of the original message's identity information, we do retain the account ID as the "username" in our user model. In this case of this user:

```
http \
    --proxy="https:http://squid.corp.redhat.com:3128" \
    --cert=cloudigrade-turnpike-stage-2.crt --cert-key=cloudigrade-turnpike-stage-2.key \
    https://mtls.internal.cloud.stage.redhat.com/api/cloudigrade/internal/api/cloudigrade/v1/users/600/ | jq
{
  "date_joined": "2021-02-17T12:45:57.703587Z",
  "id": 600,
  "username": "6349152"
}
```

The Red Hat customer account number that was used to create all of these sources/AWS cloud accounts was `6349152` which does appear to match in stage with the given `rhswatchqe` credentials.
