### ISSUE TITLE
Reaper is not reaping

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#822]
As discussed at standup today, Parag noticed that the reaper job was not running. We found that it stopped within the last few weeks when a requirement changed for the cryptography dependency and the builds failed without Rust. Since we are not actively building any changes in the reaper, we decided to stop rebuilding and simply use the latest image. Parag also said they have other processes that will manage their QE accounts and we should stop using the reaper on them.

**Comment by infinitewarp** [comment]
@katherine-black fixed the broken CI job in https://gitlab.com/cloudigrade/images/reaper/-/merge_requests/13

**Comment by infinitewarp** [comment]
@infinitewarp stopped reaping the QE accounts in https://gitlab.com/cloudigrade/images/reaper/-/merge_requests/14

**Comment by werwty** [comment]
LGTM, looks like reaper is reaping just tine again. Thanks!
