### ISSUE TITLE
Prod env continuously throwing error message as "Could not find any type for Instance". 

### ISSUE THREAD

**Issue by paraggit** [cloudigrade/cloudigrade#825]
## Summary

Since 2021-02-24T02:57:28 prod env is continuously  throwing error message periodically . 
All these messages are belongs to same account ID: ` cloud_account_id=58.` and for same machine image ID `machine_image_id:119`.

```
Could not find any type for Instance(id=3398, cloud_account_id=58, machine_image_id=119, created_at=parse('2021-02-22T06:25:33.140705+00:00'), updated_at=parse('2021-03-04T12:06:06.566991+00:00')) by 2021-02-24T02:57:28.000000Z
```
some of the occurrences are listed here.
- [message1](https://sentry.io/organizations/cloudigrade/issues/2186583208/?project=1270362&referrer=slack)
- [message2 ](https://sentry.io/organizations/cloudigrade/issues/2186583208/?project=1270362&referrer=slack)

KIBANA LOGS
- [log1](https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover/context/43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d/36012571726267696771113199009053239377889849126064422912?_a=(columns:!(_source),filters:!(),predecessorCount:6,sort:!('@timestamp',desc),successorCount:5)&_g=(filters:!()))

## Steps to Reproduce

There are no reproduction steps for this issue these messages are occurring frequently with specific interval of time. 

## Expected Result

-  There should not be any error message thrown by the application.

## Actual Result

- Error messages are appearing periodically.

**Comment by infinitewarp** [comment]
https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-04T13:00:00.000Z',to:'2021-03-04T13:07:00.000Z'))&_a=(columns:!(_source),filters:!(),index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',interval:auto,query:(language:kuery,query:'@log_stream:%22cloudigrade-prod%22%20AND%20@message:%22requestid:52a55320-db5d-4fb2-8474-f115f5c4706b%22'),sort:!())

**Comment by paraggit** [comment]
After fixes merge in to the production we have not observed these error messages again. Hence  marking this story as verified and close.
