### ISSUE TITLE
spike: Azure: access customer data (2021 edition)

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#838]
## Summary

As cloudigrade, I want to perform API calls in a customer's Azure account/tenant so that I can gather data for tracking their RHEL usage.

What is the best solution for accessing data in a customer's Azure account/tenant? How can we execute API requests in their Azure account/tenant? Have other service teams within c.rh.c solved this problem? What are their solutions, and can we use them?

Previous research [originally documented here with screenshots](https://gitlab.com/cloudigrade/cloudigrade/-/issues/514#note_127215591) and later streamlined [here](https://gitlab.com/cloudigrade/cloudigrade/-/issues/573#note_175343016) and [here](https://gitlab.com/cloudigrade/cloudigrade/-/issues/650#note_309862798) indicated that the necessary parts of Azure setup were still in "Preview" and some steps did not yet appear to have CLI/API support. Has this process improved or changed at all? Is "user_impersonation" still in "Preview"? Is there any better fine-grain control over permissions granted through this process? Does registering/setting up the multitenant app still require using the Azure web UI?

What does Sources currently do or plan to do for any other services using Azure? How are Cost Management and Topological Inventory working with Azure via Sources? What are our limitations versus options when it comes to establishing trust via Sources and its UI? One concern we have is that the more complicated multi-tenant application process may not be feasible with the current Sources flows. What about the "super key" magic? If there support for "super key" with Azure, or is that planned?

If we have questions or suggestions for Azure to make, please be proactive about discussing with the team and reach out to Gregg, Todd, and Dan Lah and try to coordinate a conversation.

Q: What's the main motivation here? What do we want to achieve by getting access into the customer's account/tenant?
- A: We want to get a list of their currently-running VMs/instances so we can "start the clock" on initial setup.
- A: We want to get a list of tags/labels associated with any of their VMs/instances and images so we can "crawl" for the crawl-walk-run of knowing which things have RHEL.

**In the interest of getting a basic solution working, perhaps we should abandon the "advanced" multi-tenant app approach and simply accept direct admin/root credentials for the customer's account/tenant.**

Relevant previous issues:

- https://gitlab.com/cloudigrade/cloudigrade/-/issues/650#note_309862798
- https://gitlab.com/cloudigrade/cloudigrade/-/issues/573#note_175343016
- https://gitlab.com/cloudigrade/cloudigrade/-/issues/514#note_127215591
- https://gitlab.com/cloudigrade/cloudigrade/-/issues/480

Expected output: documented process and code (script, jupyter notebook) for getting into someone else's Azure account and successfully performing some read operations of their data.

Timebox: 1 week for starters, but we understand that once we get conversations started it may take longer.

**Comment by katherine-black** [comment]
For this spike I'm going to build on how we currently access Azure in production, via our ServiceProvider.

Getting access to a customers subscription is fairly straightforward utilizing [ARM Templates](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/overview) to establish a Lighthouse connection. We, in the cloudigrade account, [create an ARM Template offer](https://portal.azure.com/#blade/Microsoft_Azure_CustomerHub/CreateArmTemplate.ReactView), define the "offer", where really we just specify which permissions we want, in our case just a blanket read permission for dev sake -- 

<img width="660" alt="image" src="https://user-images.githubusercontent.com/34514071/131906397-118fbadb-6cf9-4a64-b823-5577fe40f112.png">


Now we just `View Template` and download our `template.json`. We can at this point distribute this template to our customers (served from our api deployment, or maybe [this gist](https://gist.githubusercontent.com/katherine-black/4040fbc1e25d739782f320f67ef89721/raw/a6dc460fd8408b3387647829796aeb1eabefbd0e/cloudigrade-dev.json) in this case)  via easy to consume means such as this button --> [![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fgist.githubusercontent.com%2Fkatherine-black%2F4040fbc1e25d739782f320f67ef89721%2Fraw%2Fa6dc460fd8408b3387647829796aeb1eabefbd0e%2Fcloudigrade-dev.json). At which point the customer is presented with the following screen --

<img width="660" alt="image" src="https://user-images.githubusercontent.com/34514071/131908699-71b2034f-85ee-4ea7-a50d-986eb85f7adb.png">

One review + create later and we're done. The cloudigrade SP defined in our template now has read access to all resources under the customer subscription. We can further restrict that only to components when we implement this.

**Comment by infinitewarp** [comment]
Thanks for the research and for including screen shots of the setup steps!
