### ISSUE TITLE
spike: Azure: get VM/instance activity (2021 edition)

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#839]
As cloudigrade, I want to know when an Azure customer's VMs/instances start and stop so that I can track and measure RHEL usage over time.

How can we know when VMs/instances have started and stopped in a customer's Azure account/tenant?

Previous research [originally documented here](https://gitlab.com/cloudigrade/cloudigrade/-/issues/485#note_101280150) with followup notes [here](https://gitlab.com/cloudigrade/cloudigrade/-/issues/651#note_312207076) indicated that our best solution would be to regularly scrape an activity log, but this is a poor solution because we don't receive any active notification of updates and we would have to poll the log "forever" until we get enough results to overlap with our previous fetch process. Has this improved? Is there a different mechanism for monitoring or alerting on VM/instance activity?

Important note: if we can clearly identify specific problems and feature/behavior requests around this functionality that we would like changed or improved by Azure developers, we may have the opportunity to present that request and influence their roadmap. Their development cycle is six months. So, whatever we can get them "now" might have an impact later this year.

Also, this issue makes no requirement of *how* we get into the customer's account to get this data. We assume that an ideal solution will be found and implemented [elsewhere](https://github.com/cloudigrade/cloudigrade/issues/838); we just want to get activity data somehow.

If we have questions or suggestions for Azure to make, please be proactive about discussing with the team and reach out to Gregg, Todd, and Dan Lah and try to coordinate a conversation.

Relevant previous issues:

- https://gitlab.com/cloudigrade/cloudigrade/-/issues/651#note_312207076
- https://gitlab.com/cloudigrade/cloudigrade/-/issues/485#note_101280150

See also Azure docs that may be relevant:
- https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log

Expected output: documented process and code (script, jupyter notebook) for successfully retrieving historic information about when customer VM/instances start and stop.

Timebox: 3 days. Should take less time if nothing noteworthy has changed, but may take more if we learn about improvements or other options.

**Comment by katherine-black** [comment]
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview

**Comment by katherine-black** [comment]
https://docs.microsoft.com/en-us/azure/lighthouse/overview

**Comment by katherine-black** [comment]
https://docs.microsoft.com/en-us/azure/governance/resource-graph/overview

**Comment by katherine-black** [comment]
Happy to report that we finally have a new take on how to get activity data.

Notebook: https://gist.github.com/katherine-black/a234bee4729e30d0648725cb1287c495

Two different mechanisms are in play here. I use *Azure Resource Graph* to fetch all VM resources across all Subscriptions cloudigrade has access too. This list _should_ contain all resources that have _existed_ in the last 14 days.

The second step, is using the `resourceChangeDetails` API to fetch finer details about what changes happened. Here is a slightly redacted example of what that output looks like:
```
{
       "changes": [
              {
                     "afterSnapshot": {
                            "snapshotId": "a3f93dd9-6eb2-4d3b-ab5d-cc6d2c101275",
                            "timestamp": "2021-09-01T18:50:04.245Z"
                     },
                     "beforeSnapshot": {
                            "snapshotId": "f4ca2bfa-c4d1-404c-b9ef-5eaa790c61c1",
                            "timestamp": "2021-09-01T18:28:40.463Z"
                     },
                     "changeId": "{\"beforeId\":\"f4ca2bfa-c4d1-404c-b9ef-5eaa790c61c1\",\"beforeTime\":\"2021-09-01T18:28:40.463Z\",\"afterId\":\"a3f93dd9-6eb2-4d3b-ab5d-cc6d2c101275\",\"afterTime\":\"2021-09-01T18:50:04.245Z\"}",
                     "changeType": "Update",
                     "propertyChanges": [
                            {
                                   "afterValue": "VM deallocated",
                                   "beforeValue": "VM running",
                                   "changeCategory": "User",
                                   "propertyChangeType": "Update",
                                   "propertyName": "properties.extended.instanceView.powerState.displayStatus"
                            },
                            {
                                   "afterValue": "PowerState/deallocated",
                                   "beforeValue": "PowerState/running",
                                   "changeCategory": "User",
                                   "propertyChangeType": "Update",
                                   "propertyName": "properties.extended.instanceView.powerState.code"
                            }
                     ]
              }
       ]
}   
```
The particular thing of note here is we can keep track of the {before,after}Snapshot timestamps, and only ever query future data for resources we're monitoring. This should cut down significantly on the thrash of the original plan of drink from the firehose that is the ActivityLog.

**Comment by infinitewarp** [comment]
Thanks for the research and example commands in the notebook! This looks much more promising than the Activity Log.
