### ISSUE TITLE
Azure: get customer VM/instance and boot image metadata (2021 edition)

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#840]
As cloudigrade, I want to get a list of all currently running VMs/instances in a customer's Azure account/tenant so that I can start tracking activity as soon as I learn about the customer.

What API calls are necessary to list all VMs/instances? What API calls are necessary to describe them with sufficient detail so we can reference them in our data model? We need at least their IDs, hardware size (CPU, memory, etc.), and information about what base image was used to boot them.

Previous research [originally documented here](https://gitlab.com/cloudigrade/cloudigrade/-/issues/481#note_100101458) with followup notes [here](https://gitlab.com/cloudigrade/cloudigrade/-/issues/575#note_175884579) and [here](https://gitlab.com/cloudigrade/cloudigrade/-/issues/652#note_361185776) included examples, workarounds, and questions about getting VM and image information.

Relevant previous issues:

- https://gitlab.com/cloudigrade/cloudigrade/-/issues/652#note_361185776
- https://gitlab.com/cloudigrade/cloudigrade/-/issues/575#note_175884579
- https://gitlab.com/cloudigrade/cloudigrade/-/issues/481#note_100101458

Expected output: documented process for successfully retrieving list of currently running VMs, enough metadata to know their hardware definitions, and enough information to identify the images they booted. Note that this process may differ if the VM was booted from an image versus a cloned disk and if the image has been deleted.

Consider reaching out to Dan Lah and/or Jared Blashka to try to find technical contacts within Microsoft Azure to advise.

Ask Gregg Tanzillo if he recalls anything interesting from Cloudforms.

Timebox: 3 days

**Comment by katherine-black** [comment]
Here is a notebook demonstrating use of the azure sdk to get this info -- https://gist.github.com/katherine-black/879a4c1dae0cd3667b317c966202c754

**Comment by infinitewarp** [comment]
Sorry that verifying this slipped by for so long. Thanks for the notebook!
