### ISSUE TITLE
Azure: copy image from customer account (2021 edition)

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#841]
Update 2022-01-12: This work is on hold until @gtanzillo has a conversation with our Microsoft friends about the Linux agent. Can we use that? If so, the definition here is completely different. If not, we need to talk about the hacky solutions.

----

As cloudigrade, I want to copy my Azure customer's boot image/disk into my Azure tenant so that I can inspect it.

The primary motivation here is the same as why we copy the image with our AWS integration. We want to minimize our footprint within the customer's Azure tenant and we do not want to incur them additional costs when doing our job. If we cannot copy the image, we would need to run inspection in their tenant, and that's not something the customer should have to pay for.

Previous research [originally documented here](https://gitlab.com/cloudigrade/cloudigrade/-/issues/483#note_102029981) with followup notes [here](https://gitlab.com/cloudigrade/cloudigrade/-/issues/575#note_175884579) and [here](https://gitlab.com/cloudigrade/cloudigrade/-/issues/586#note_373574469) described a process of creating a blob and copying that across different storage accounts.

Is that still the best solution? [This comment](https://gitlab.com/cloudigrade/cloudigrade/-/issues/483#note_102029981) described trying to create a snapshot, but it failed; does that still fail today? What should we expect if the customer deletes an image after the VM starts? How do images and cloned disks differ, and do they require different processes?

Note that we do *not* want to capture a live copy of a running disk. We specifically want the base image.

Relevant previous issues:

- https://gitlab.com/cloudigrade/cloudigrade/-/issues/483#note_102029981
- https://gitlab.com/cloudigrade/cloudigrade/-/issues/575#note_175884579
- https://gitlab.com/cloudigrade/cloudigrade/-/issues/586#note_373574469

Expected output: documented process for successfully copying a base image from the customer's tenant to ours

**Comment by katherine-black** [comment]
I have controversial thoughts as to why we may not need this, we should definitely talk about this at next refinement.

**Comment by infinitewarp** [comment]
Closing this issue since we are evaluating new solutions.
