### ISSUE TITLE
Cloudmeter sources remain in 'Unknown' status.

### ISSUE THREAD

**Issue by paraggit** [cloudigrade/cloudigrade#845]
## Summary

After adding sources for cloudmeter in stage-stable env.   its remain in 'unknown '  status. I was tried to create with both method 'manual-configuration' and 'superkey' both gives same results.  I trace the API call of sources and it has create all the required objects 'sources','application' and 'application-authentications' but it has not added entry in cloudmeter end. 
And since this morning all the cloudmeter vortex automated  test cases are failing in sources creation path.

I have raised same issue in sources slack channel and waiting for their reply. I have open this issue to track/debug from the cloudmeter side. 
 
## Steps to Reproduce

- Open stage sources creation UI . 
- Follow the instructions to create sources for cloudmeter.
- Observe the sources status. 

## Expected Result

- After adding sources for cloudmeter it should be shown as 'Active' status.

## Actual Result

- Sources remains in 'Unknown status.'

## Additional context

- GET /sources
```shelll
%  http  --proxy=$PROXY  --verify=no --auth $AUTH  "$URL/api/sources/v3.1/sources/"
{
    "data": [
        {
            "app_creation_workflow": "manual_configuration",
            "created_at": "2021-03-30T11:15:17Z",
            "id": "20892",
            "name": "cmources",
            "source_type_id": "1",
            "tenant": "6349152",
            "uid": "07b8a01a-7d10-44f5-8bdc-43af10770325",
            "updated_at": "2021-03-30T11:15:20Z"
        }
    ],
    "links": {
        "first": "/api/sources/v3.1/sources/?offset=0",
        "last": "/api/sources/v3.1/sources/?offset=0"
    },
    "meta": {
        "count": 1,
        "limit": 100,
        "offset": 0
    }
}
```

- GET /applications
```shell
%  http  --proxy=$PROXY  --verify=no --auth $AUTH  "$URL/api/sources/v3.1/applications/"
{
    "data": [
        {
            "application_type_id": "3",
            "created_at": "2021-03-30T11:15:17Z",
            "extra": {},
            "id": "15535",
            "last_checked_at": "2021-03-30T12:15:30Z",
            "source_id": "20892",
            "tenant": "6349152",
            "updated_at": "2021-03-30T12:15:30Z"
        }
    ],
    "links": {
        "first": "/api/sources/v3.1/applications/?offset=0",
        "last": "/api/sources/v3.1/applications/?offset=0"
    },
    "meta": {
        "count": 1,
        "limit": 100,
        "offset": 0
    }
}
```

- GET /application_authentications/
```shell
 http  --proxy=$PROXY  --verify=no --auth $AUTH  "$URL/api/sources/v3.1/application_authentications/
{
    "data": [
        {
            "application_id": "15535",
            "authentication_id": "9571",
            "created_at": "2021-03-30T11:15:17Z",
            "id": "4959",
            "tenant": "6349152",
            "updated_at": "2021-03-30T11:15:17Z"
        }
    ],
    "links": {
        "first": "/api/sources/v3.1/application_authentications/?offset=0",
        "last": "/api/sources/v3.1/application_authentications/?offset=0"
    },
    "meta": {
        "count": 1,
        "limit": 100,
        "offset": 0
    }
}
```

- GET /accounts
```shell
http  --proxy=$PROXY  --verify=no --auth $AUTH  "$URL/api/cloudigrade/v2/accounts/


{
    "detail": "Incorrect authentication credentials."
}
```

**Comment by infinitewarp** [comment]
As discussed in Slack, the root cause is that the sources stage deployment was broken for several hours today and remains unavailable to use (as of this update) due to deployment config changes for their hostname and port. Their changes will require us to make deployment config changes, but we're waiting for their new environment variables to be available first.

**Comment by infinitewarp** [comment]
This should now be resolved since sources-api is stable in stage and we updated our configs to point to the new sources-api. See also https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17106

**Comment by paraggit** [comment]
Now I am able to create sources for cloudmeter in stage environment. Hence moving this issue to close state.
<img width="1777" alt="sources" src="https://user-images.githubusercontent.com/14196504/113242415-8d82a600-92ce-11eb-9c12-3a7e9d3d13ce.png">
