### ISSUE TITLE
Longevity tests account shows unexpected count of instances in concurrent calculation.

### ISSUE THREAD

**Issue by paraggit** [cloudigrade/cloudigrade#848]
## Summary

   Longevity test is mean to validate application stability and serviceability features over a longer period. We have prepared one account to have a cloudmeter data for longer period of time and It has  300 instances running in with various arch(x86, i386, arch64) and syspurpose data ("role", "usages", "SLA").

   This account has prepared  On the date "2021-03-23" and it still registered. we are  observing daily logs  and concurrent count and validating it with actual count with the instances running on AWS.

Here an issue is we have added 300 instances and concurrent calculation is reporting 305 instances count and that is unexpected. This bug we have opened to investigate and fix  the root cause of this issue.

## Steps to Reproduce

- Add sources for cloudmeter
- Create 300 instances 100 x86 + 100 i386 + 100 arch64
- Observe logs daily and concurrent API counts.

## Expected Result

-  GET /concurrent API count should get match with the actual instances running on AWS account.

## Actual Result

- GET /concurrent API reporting 300 instances and actual instances running on aws is 300.

## Additional context

- All the API data we can find here.
  
[concurrent.log](https://github.com/cloudigrade/cloudigrade/files/6234748/concurrent.log)
[images.log](https://github.com/cloudigrade/cloudigrade/files/6234751/images.log)
[instances.log](https://github.com/cloudigrade/cloudigrade/files/6234752/instances.log)

- Following instances are seen in get /instances API but its not present on AWS.
 
[missing_instances.log](https://github.com/cloudigrade/cloudigrade/files/6234765/missing_instances.log)

-  Tally also reporting 305 instance count.
<img width="1501" alt="tally_sync" src="https://user-images.githubusercontent.com/14196504/113110164-6374a980-9224-11eb-8dba-0b10ac0dc32f.png">

**Comment by paraggit** [comment]
Here is the snippet of discussion has happend on slack channel about this issue.
`brad:abongoblob:  16 hours ago
I checked the first one ("instance_id": 6666) and found that it does appear to have power_on and power_off events in the correct order, which would mean it should be excluded from any concurrent usage totals after 2021-03-25. I'll check the others in that list next to try to find any outliers.

brad:abongoblob:  16 hours ago
I verified that all the instances in that list have power_off as their most recent event. I'll keep looking for other clues.

brad:abongoblob:  16 hours ago
I might have an explanation.

brad:abongoblob:  16 hours ago
I found some instances with 2 vcpus. The EC2 type t4g.micro has 2. So, they may make the CPU socket usage numbers greater than the actual instance numbers.

parag  16 hours ago
is it expected? i was in impression that we are just counting instances not as per their CPU socket. (edited) 

brad:abongoblob:  16 hours ago
hmm… that's a good point. I was misremembering when we used to include all the vcpu and memory counts. I'll look closer.




brad:abongoblob:  16 hours ago
Unfortunately I think I've reached as far as I can in stage without writing more code or submitting some SQL query requests through app-interface. I'll come back to this and update later when I have more information.
:+1:
1


brad:abongoblob:  16 hours ago
I really really wish I could just interface with a pod or the DB, but alas…

brad:abongoblob:  14 hours ago
I've put in this app-interface request for further data. Now we wait. https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17105`

**Comment by infinitewarp** [comment]
Attached is the output from https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17105

[2021-03-30-cloudigrade-stage-1-jdv4h.txt](https://github.com/cloudigrade/cloudigrade/files/6238453/2021-03-30-cloudigrade-stage-1-jdv4h.txt)

**Comment by infinitewarp** [comment]
I've gathered enough information through our APIs to confirm that cloudigrade in stage is correctly calculating 305 running RHEL instances in recent days based on the event data it has. The extra five are in the set described by the `missing_instances.log` file that Parag attached above.

I have a local jupyter notebook where I've been hitting our APIs to collect and sort through the data. Some relevant notes about those unexpected five instances:

```
[{'instance_id': 6673,
  'ec2_instance_id': 'i-01dacffe52820de47',
  'region': 'us-east-1',
  'image_id': 2798,
  'ec2_ami_id': 'ami-06cf00214d186f165',
  'image_name': 'i386-image',
  'rhel': True,
  'is_cloud_access': False},
 {'instance_id': 6675,
  'ec2_instance_id': 'i-034b6be91c4b684f2',
  'region': 'us-east-1',
  'image_id': 2798,
  'ec2_ami_id': 'ami-06cf00214d186f165',
  'image_name': 'i386-image',
  'rhel': True,
  'is_cloud_access': False},
 {'instance_id': 6677,
  'ec2_instance_id': 'i-032497a66b7121c6e',
  'region': 'us-east-1',
  'image_id': 2798,
  'ec2_ami_id': 'ami-06cf00214d186f165',
  'image_name': 'i386-image',
  'rhel': True,
  'is_cloud_access': False},
 {'instance_id': 6680,
  'ec2_instance_id': 'i-01d8ccb3d2deafcf1',
  'region': 'us-east-1',
  'image_id': 2798,
  'ec2_ami_id': 'ami-06cf00214d186f165',
  'image_name': 'i386-image',
  'rhel': True,
  'is_cloud_access': False},
 {'instance_id': 6681,
  'ec2_instance_id': 'i-0d5712469abb4d232',
  'region': 'us-east-1',
  'image_id': 2798,
  'ec2_ami_id': 'ami-06cf00214d186f165',
  'image_name': 'i386-image',
  'rhel': True,
  'is_cloud_access': False}]
```

and some info about their unending runs:
```
[{'id': 11184,
  'created_at': '2021-03-25T03:47:12.056541Z',
  'updated_at': '2021-03-25T03:47:12.056565Z',
  'start_time': '2021-03-25T03:37:36Z',
  'end_time': None,
  'instance_type': 't1.micro',
  'memory': 627.0,
  'vcpu': 1,
  'machineimage': 2798,
  'instance': 6673},
 {'id': 11187,
  'created_at': '2021-03-25T03:55:09.003252Z',
  'updated_at': '2021-03-25T03:55:09.003273Z',
  'start_time': '2021-03-25T03:40:10Z',
  'end_time': None,
  'instance_type': 't1.micro',
  'memory': 627.0,
  'vcpu': 1,
  'machineimage': 2798,
  'instance': 6675},
 {'id': 11190,
  'created_at': '2021-03-25T03:57:12.267124Z',
  'updated_at': '2021-03-25T03:57:12.267150Z',
  'start_time': '2021-03-25T03:46:34Z',
  'end_time': None,
  'instance_type': 't1.micro',
  'memory': 627.0,
  'vcpu': 1,
  'machineimage': 2798,
  'instance': 6677},
 {'id': 11195,
  'created_at': '2021-03-25T04:03:12.894896Z',
  'updated_at': '2021-03-25T04:03:12.894914Z',
  'start_time': '2021-03-25T03:50:19Z',
  'end_time': None,
  'instance_type': 't1.micro',
  'memory': 627.0,
  'vcpu': 1,
  'machineimage': 2798,
  'instance': 6680},
 {'id': 11196,
  'created_at': '2021-03-25T04:07:11.237671Z',
  'updated_at': '2021-03-25T04:07:11.237692Z',
  'start_time': '2021-03-25T03:56:16Z',
  'end_time': None,
  'instance_type': 't1.micro',
  'memory': 627.0,
  'vcpu': 1,
  'machineimage': 2798,
  'instance': 6681}]
```

Assuming they were stopped on the same day as they were started (2021-03-25), we should have seen stop or terminate events via CloudTrail. Indeed, there were 514 messages from this AWS account on that day:

```
AWS_PROFILE=cloudmeter_stage aws s3 ls stage-cloudigrade-trails/AWSLogs/402708541762/CloudTrail/us-east-1/2021/03/25/ | wc -l
     514
```

I could download all of these and write some code to dig through them, and I could try to dig through our logs to see if there was some error processing them, but there are so many and they occurred so long ago that I think my efforts may be better spent elsewhere to fix the problem going forward.

So, I'm starting some changes to our `initial_aws_describe_instances` function to teach it to discover if instances were stopped unexpectedly (meaning: we didn't receive/process the stop event correctly).

**Comment by paraggit** [comment]
I had stopped 200 instances out of 300 running instances on AWS then i was expecting cloudmeter should report 100 concurrent count on next day API call but its showing 106 instance count.

Image count on CRC.
<img width="1480" alt="longevity" src="https://user-images.githubusercontent.com/14196504/116253466-256c9600-a78e-11eb-8f20-4009719f9fa3.png">

Actual running instances on AWS.
<img width="1066" alt="AWS" src="https://user-images.githubusercontent.com/14196504/116253619-403f0a80-a78e-11eb-933f-e4265f3b448d.png">

**Comment by mbpierce** [comment]
I realize that this behavior may change with changes to be pushed soon but want to document this anyway in case it's useful later.

I've been digging into this and have gathered the following:
As of yesterday (18 May 2021), there were no instances running in the AWS account in question.


A call to 

```http  --proxy="https:http://squid.corp.redhat.com:3128"  --verify=no --auth cloudmeter_longevity:redhat123  "https://cloud.stage.redhat.com/api/cloudigrade/v2/concurrent/" start_date==2021-05-16 end_date==2021-05-17```

still returns a count of 5 instances, though there should be none.

Files included:
[May 18 request for May 17 data](https://github.com/cloudigrade/cloudigrade/files/6511366/17MayConc_18MayRequest.txt) -  On may 18 I requested concurrent counts from the day before (17 May 2021). This is the data returned that day.

[May 19 request for May 17 data](https://github.com/cloudigrade/cloudigrade/files/6511455/gather_data.txt) - On May 19 I requested concurrent counts from 17 May 2021 and got the `Results are currently unavailable, try again later` response suggesting that cloudigrade hadn't done the calculations yet even though I saw them yesterday.

[Subsequent May 19 request for May 17 data](https://github.com/cloudigrade/cloudigrade/files/6511464/long_concurrent.txt) - A few minutes later, I made the same request to the concurrent API and got data back.
The data in the above file shows that there are 5 instances being reported for that day. I confirmed in our AWS account that there were no instances running that day.

Here is a file with the reported images for this account:
[Account Images](https://github.com/cloudigrade/cloudigrade/files/6511481/long_images.txt)
 
And here is a file with the reported instances for that account/date:
[First 10, paginated](https://github.com/cloudigrade/cloudigrade/files/6511498/long_instances.txt)
[All 752, not paginated](https://github.com/cloudigrade/cloudigrade/files/6511499/long_instances_full.txt)

And here is the [account](https://github.com/cloudigrade/cloudigrade/files/6511542/long_account.txt)

**Comment by paraggit** [comment]
With recent changes I have tests concurrent API output and  its correctly getting counted.
```shell
%
http  --proxy="https:http://squid.corp.redhat.com:3128"  --verify=no --auth cloudmeter_longevity:redhat123  "https://cloud.stage.redhat.com/api/cloudigrade/v2/concurrent/"
HTTP/1.1 200 OK
Allow: GET, HEAD, OPTIONS
Cache-Control: private
Connection: keep-alive
Content-Length: 228
Content-Type: application/json
Date: Fri, 09 Jul 2021 02:02:44 GMT
Server: openresty/1.13.6.1
Set-Cookie: 8f585a7d113e400d14faa100d81cbdaf=027e1901ae22e1727dc559fee71a76c6; path=/; HttpOnly; Secure; SameSite=None
Vary: Accept
referrer-policy: same-origin
x-cloudigrade-request-id: 35725291-6642-49c5-bfcc-b2529b8662b0
x-content-type-options: nosniff
x-frame-options: DENY
x-rh-insights-request-id: 140456987f6746758836bd5f591ba46b
{
    "data": [
        {
            "date": "2021-07-08",
            "maximum_counts": []
        }
    ],
    "links": {
        "first": "/api/cloudigrade/v2/concurrent/?limit=10&offset=0",
        "last": "/api/cloudigrade/v2/concurrent/?limit=10&offset=0",
        "next": null,
        "previous": null
    },
    "meta": {
        "count": 1
    }
}
```

**Comment by paraggit** [comment]
I have observed 3 days data with changing  instance count on AWS end, All the cases are validated as expected including tally sync operations.  On this  observation basis I am closing this issue.
<img width="1499" alt="rhel_usages" src="https://user-images.githubusercontent.com/14196504/125463938-4ecf44c9-2eaa-4194-a86a-7f0a55b9fb6f.png">
