### ISSUE TITLE
Pagination links malformed

### ISSUE THREAD

**Issue by mbpierce** [cloudigrade/cloudigrade#851]
## Summary

When Cloudmeter returns data with more than 10 items, the links to page through the data are formed improperly like so:

`/api/cloudigrade/api/cloudigrade/v2/instances/?limit=10&offset=20` 

rather than: 

`/api/cloudigrade/v2/instances/?limit=10&offset=20`

resulting in `404` status_code and no data returned when I try to get data from the next page.

## Steps to Reproduce

```
proxy = {"https": "http://squid.corp.redhat.com:3128"}
api_url = ("https://cloud.stage.redhat.com/api/cloudigrade/v2/")
auth = ('my_cool_user','super s3cre7 pa55wrd')
response = requests.get(f'{api_url}{data_type}/', auth=auth, proxies=proxy).json()
full_response = []
data = response['data']
for item in data:
    full_response.append(item)

if response['links']['next'] is not None:
    url = 'https://cloud.stage.redhat.com'
    link = response['links']['next']
    url = (f'{url}{link}')
    paginated_response = requests.get(url, auth=auth, proxies=proxy)
```
(lmk if you need an actual user here)
## Actual Result

At this juncture, 

`response['links']['next']` returns `'/api/cloudigrade/api/cloudigrade/v2/instances/?limit=10&offset=20'` 

and  
`paginated_response.status_code` is `404` where I would have expected a `200` and the next set of data.

A patch that is working currently for test purposes is

```
link = re.sub('/api/cloudigrade/api/cloudigrade', '/api/cloudigrade', link)
```

## Expected Result

- I expected the link URL to be `'/api/cloudigrade/v2/instances/?limit=10&offset=10'`

**Comment by infinitewarp** [comment]
@abellotti you might need to look at https://gitlab.com/cloudigrade/libraries/drf-insights-pagination

We actually built pagination as middleware and released it as separate project in the hopes that other Python projects in the c.rh.c platform would/could use it. I'm not sure if anyone else actually does, but we still do!
