### ISSUE TITLE
Be aware of windows instances/amis and act accordingly

### ISSUE THREAD

**Issue by ilyavw** [cloudigrade/cloudigrade#87]
As a Cloudigrade Administrator, I don't want cloudigrade wasting cycles trying to inspect windows instances/amis so that time could be used instead to inspect linux instances.

## Acceptance Criteria 

- [x] Verify that Windows instance AMIs are automatically stored in an inspected state and marked as a Windows image when they are discovered.

## Tech assumptions

- For AWS we can query the instance platform to find out if the instance is windows or not. Windows will be marked as `windows`, and everything else will be `None`.
```
$ aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId,Platform,Status]' --output text
i-07ebccb011511a47c	None	None
i-0586c3c56cca7d93e	windows	None
i-0bee3c1c7c65b518c	None	None
```
- Further research will have to be done later to determine how to do this in other clouds.

**Comment by infinitewarp** [comment]
Was this already covered by the Windows checking in https://github.com/cloudigrade/cloudigrade/issues/88, @adberglund ?

**Comment by adberglund** [comment]
I check for the `Windows` value of the `Platform` attribute, but currently we're just marking it as being windows, not having been inspected. This could be a very quick story to make sure it's in the state we want. That said, currently a Windows machine image won't get passed on to be inspected, so it really depends on how we want to define what has been inspected.

**Comment by infinitewarp** [comment]
It looks like we were already _trying_ to do the right thing here, but we had a couple of bugs getting in the way. I've addressed those bugs in #260 for #259, and here's a demo of the corrected behavior after those changes: https://asciinema.org/a/179810

**Comment by infinitewarp** [comment]
Whoops… it looks like we've still missed one thing here!

When we first discover an image, we call `generate_aws_ami_messages` and the output of that call spawns a bunch of async tasks to go down the image inspection route. That function appears to have the same incorrect "Windows" case bug when filtering out instances by the Platform value. I'll fix that now…

**Comment by noahl** [comment]
@infinitewarp darn it! Thanks for catching that.

**Comment by infinitewarp** [comment]
Demo: https://asciinema.org/a/180632

**Comment by ilyavw** [comment]
Verified.
