### ISSUE TITLE
make availability_status fast

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#891]
## Summary

As the sources-api, I want the availability_status API to respond quickly so that I can proceed to next steps in a reasonable time. As cloudigrade sysop, I want the availability_status API to respond quickly so that the gunicorn worker doesn't time out.

@infinitewarp noticed in production some brief periods when *all* of our APIs were unresponsive, and requests would consistently return `502 Bad Gateway` or `504 Gateway Timeout`. Logs indicate this is caused by gunicorn workers being killed due to timing out.

For example, in the nginx logs:

```
2021/05/04 15:22:53 [error] 20#0: *59629 connect() to unix:/var/run/cloudigrade/gunicorn.sock failed (11: Resource temporarily unavailable) while connecting to upstream
```

and in the cloudigrade/gunicorn logs:

```
[2021-05-04 15:22:50 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:137135)
[2021-05-04 15:22:51 +0000] [138193] [INFO] Booting worker with pid: 138193
```

Following backwards in the cloudigrade/gunicorn logs, those timeouts tend to coincide closely with requests being processed by the availability_status API. We synchronously run all the code for `CloudAccount.enable` which may include many AWS API calls (see `api.clouds.aws.util.verify_permissions`), and the cumulative time for those calls may exceed a reasonable timeout.

We may need to consider removing the synchronous `CloudAccount.enable` call and instead simply return "OK" while triggering an asynchronous task to perform the check.

## Acceptance Criteria

- [ ] Verify the `availability_status` API always returns a response reasonably fast
- [ ] Verify that we make an async call to perform the verification process as a result of the `availability_status` API request
- [ ] Verify that *if* we have to change the CloudAccount "enabled" state as a result of the async process, that action updates sources-api with the appropriate status. (This should already be present. We just want to verify that it still works.)

## Assumptions and Questions

- Or maybe we just *don't* call  `CloudAccount.enable` from this API? We already have a periodic task `verify_account_permissions`. Maybe we should just rely on that. We could add some code to ensure it always exists and runs. See also `AwsCloudAccount._enable_verify_task`. We have these currently set to run once daily. Maybe we should reduce the interval to once every few hours?
  - sources makes its check once every 60 minutes for applications that are currently available.
  - sources makes its check once every 30 minutes for applications that are currently unavailable.
  - Our periodic task probably pre-date the sources check.
  - Let's keep the async task at 24 hours, but let's also kick off a new task when the request comes in.
- QE may already have test cases to cover the changing of state and updating of application availability. Ask a QE friend to run tests when this change is made to verify no regression.

**Comment by gtanzillo** [comment]
@infinitewarp 

As we had discussed, the timeouts could be related to pods getting throttled by OCP when they hit the configured cpu limit. As far as I know, there isn't a straightforward way to determining whether a pod has had its cpu throttled. However, you can see stats related to throttling by looking at the file  `/sys/fs/cgroup/cpu/cpu.stat`

Here is an example of the contents of that file:

```

...
1-web-service-b7fc6b49d-hzzlj
nr_periods 64982
nr_throttled 39119
throttled_time 3279094310213
...
postgresql-6df9cfdf9-gm6tv
nr_periods 69106
nr_throttled 65921
throttled_time 32349163960820
...
```
Both of these examples indicate that cpu throttling has happened. The telltale sign is that the values of `nr_periods` and `nr_throttled` are in the same order of magnitude. In a normal, steady-state, the value of `nr_throttled` would be a number that is much lower than the value of `nr_periods`. Kubernetes samples each pod and each sample/period is checked for whether it’s currently throttled. If the throttled samples is more than 10% of total samples, you might start to see degradation. When it’s 25% or more, it’s silently getting slowed down.

Here's a handy one-liner to grab the throttling output from all the pods in a project -
`for I in `oc get pods -o wide | grep -v NAME | awk '{ print $1 }'`; do echo $I >> /tmp/throttletime ; oc exec -t $I  cat /sys/fs/cgroup/cpu/cpu.stat >> /tmp/throttletime; done`

I realize that some pods (at least the `cloudigrade-api` pod) have multiple containers and I think this would have to be tweaked a bit to get it to work. 

Unfortunately, I don't have permission to exec a command on any of the pods on stage (no surprise there) so we'll have to get Benny to do it for us if we want to check it on stage.

**Comment by katherine-black** [comment]
Here are logs from stage highlighting the new flow:

```
May 14, 2021 @ 12:00:16.2062021-05-14 19:00:16,206 | INFO | 9 | views.py:availability_check:52 | requestid:b7ef4899-0dcd-444f-8291-8ab82c2e8611 | Availability check for source ID 19073 triggering task to enable cloud account CloudAccount(id=1205, name='aws-account-402708541762', is_enabled='True', enabled_at=parse('2021-03-23T06:56:31.438596+00:00'), user_id=910, platform_authentication_id=8281, platform_application_id=13918, platform_source_id=19073, created_at=parse('2021-03-23T06:56:31.438460+00:00'), updated_at=parse('2021-03-23T06:56:31.438490+00:00'))

May 14, 2021 @ 12:00:39.1372021-05-14 19:00:39,137 | INFO | 29 | models.py:enable:119 | requestid:b7ef4899-0dcd-444f-8291-8ab82c2e8611 | 'is_enabled' is True before enabling CloudAccount(id=1205, name='aws-account-402708541762', is_enabled='True', enabled_at=parse('2021-03-23T06:56:31.438596+00:00'), user_id=910, platform_authentication_id=8281, platform_application_id=13918, platform_source_id=19073, created_at=parse('2021-03-23T06:56:31.438460+00:00'), updated_at=parse('2021-03-23T06:56:31.438490+00:00'))

May 14, 2021 @ 12:00:40.9222021-05-14 19:00:40,922 | INFO | 29 | sources.py:notify_application_availability:233 | requestid:b7ef4899-0dcd-444f-8291-8ab82c2e8611 | Setting the availability status for application 13918 as available

May 14, 2021 @ 12:00:41.2832021-05-14 19:00:41,283 | INFO | 29 | trace.py:info:125 | requestid:b7ef4899-0dcd-444f-8291-8ab82c2e8611 | Task api.tasks.enable_account[326866b3-179d-4f92-8f25-eb35778394fe] succeeded in 2.1600679549737833s: None


```

**Comment by katherine-black** [comment]
Here is another example of an instance that was in a disabled state, that gets re-enabled by the availability check.

```
May 17, 2021 @ 05:31:09.3252021-05-17 12:31:09,325 | INFO | 8 | views.py:availability_check:52 | requestid:32cb4d68-588b-4fcb-aab8-458752602dc6 | Availability check for source ID 29696 triggering task to enable cloud account CloudAccount(id=3686, name='aws-account-439727791560', is_enabled='False', enabled_at=parse('2021-05-17T12:30:10.469603+00:00'), user_id=2745, platform_authentication_id=19039, platform_application_id=23780, platform_source_id=29696, created_at=parse('2021-05-17T12:30:10.469556+00:00'), updated_at=parse('2021-05-17T12:30:52.719192+00:00'))

May 17, 2021 @ 05:31:09.6402021-05-17 12:31:09,640 | INFO | 30 | models.py:enable:119 | requestid:32cb4d68-588b-4fcb-aab8-458752602dc6 | 'is_enabled' is False before enabling CloudAccount(id=3686, name='aws-account-439727791560', is_enabled='False', enabled_at=parse('2021-05-17T12:30:10.469603+00:00'), user_id=2745, platform_authentication_id=19039, platform_application_id=23780, platform_source_id=29696, created_at=parse('2021-05-17T12:30:10.469556+00:00'), updated_at=parse('2021-05-17T12:30:52.719192+00:00'))

May 17, 2021 @ 05:31:11.9242021-05-17 12:31:11,924 | INFO | 30 | sources.py:notify_application_availability:233 | requestid:32cb4d68-588b-4fcb-aab8-458752602dc6 | Setting the availability status for application 23780 as available

May 17, 2021 @ 05:31:12.2472021-05-17 12:31:12,247 | INFO | 30 | trace.py:info:125 | requestid:32cb4d68-588b-4fcb-aab8-458752602dc6 | Task api.tasks.enable_account[194f316e-2b0b-49f1-b331-c66a7d480ec2] succeeded in 2.6410096150357276s: None
```

**Comment by infinitewarp** [comment]
Thanks for digging up the logs to share, @katherine-black ! Looks to go me. 👍
