### ISSUE TITLE
make "yesterday" default for concurrent API

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#894]
## Summary

As the tally service, I want to request concurrent usage totals for a user only once per day and be confident that the calculated data is stable. Currently, the default behavior for the concurrent API is to return totals for "today", but since totals could change between the time of that call and 23:59:59.999, the new totals for that day may never be seen by tally.

Instead, we should return "yesterday" as the default when no argument are given, and any request that specifies "today" or later should be considered invalid. Currently, we allow "today" and only treat _future_ dates as invalid. By returning "yesterday" data, we have much higher confidence that our calculated totals will will have the complete activity for that date.

On 2021-05-06, @infinitewarp asked @kahowell in the Subscription Watch sync-up meeting if changing cloudigrade's default behavior to return "yesterday" would make sense, and the consensus was that *yes we should proceed with this change.* The tally service is aware of the optional date parameters for our concurrent API, but their client currently only uses `null` for each of them.

## Acceptance Criteria

- [ ] Verify concurrent API request with no arguments returns data for "yesterday"
  - For example, a request made at `2021-05-06 15:12:54` would return totals for the date `2021-05-05`.
- [ ] Verify concurrent API request with `start_date` set to "today" or later returns a 400 error response with an explanation.
  - We currently return an error message like "start_date cannot be in the future" for future dates. This message should update to indicate that the current date is also not allowed.
- [ ] Verify we have an internal API that generally behaves the same as the public "concurrent" API, but the internal version has no date restrictions.
  - This should enable QE to keep testing with "today" data.
- [ ] Verify that any related docs (such as REST API examples, openapi.json) are updated.

## Assumptions and Questions

- Kevin said that tally's current schedule is to ask for concurrent usage data at 01:00 UTC. This should generally allow sufficient time for slow AWS CloudTrail messages to be received and processed by cloudigrade, but there's also the possibility that at the end of the day we get a "power_on" event for an instance with a brand new image we've never seen and need to inspect, but the inspection process for that new instance+image could take an hour or longer. In this edge case, we still might be updating yesterday's totals _after_ tally has retrieved them. We should start thinking about how to address this problem in the future. Maybe tally should ask for the last two days and update their records? Maybe we should always return yesterday *and* the previous day?
- QE would greatly benefit to have an API that allows them to get "today" data even though generally we may not want to expose it. Maybe we could add some kind of "force" flag to allow today? Maybe we could add an internal API to force calculation? Maybe we can use the existing internal read-only concurrent API? Maybe an unrestricted version of this API that's internal only?
  - Let's try adding an unrestricted version of this API that's internal only. Same behavior as public API, just without the date restriction.

**Comment by paraggit** [comment]
I have verified changes in stage environment and concurrent API is correctly giving data of yesterday's date.

```shell
 % date
Wed May 26 20:45:07 IST 2021
```
```shell

%http  --proxy="$PROXY"  --verify=no --auth $AUTH "$URL/api/cloudigrade/v2/concurrent/"

HTTP/1.1 200 OK
Allow: GET, HEAD, OPTIONS
Cache-Control: private
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 280
Content-Type: application/json
Date: Wed, 26 May 2021 14:58:56 GMT
Server: openresty/1.13.6.1
Set-Cookie: 8f585a7d113e400d14faa100d81cbdaf=2ec0558d214d7784c3f2d3cf3033076d; path=/; HttpOnly; Secure; SameSite=None
Vary: Accept
Vary: Accept-Encoding
referrer-policy: same-origin
x-cloudigrade-request-id: 3fcf426c-73b3-469d-a91c-b7f9075c55bb
x-content-type-options: nosniff
x-frame-options: DENY
x-rh-insights-request-id: 7d1fe3c66a8f4721ad989e8db021d1f1

{
    "data": [
        {
            "date": "2021-05-25",
            "maximum_counts": [
                {
                    "arch": "_ANY",
                    "instances_count": 5,
                    "role": "_ANY",
                    "service_type": "_ANY",
                    "sla": "_ANY",
                    "usage": "_ANY"
                }
```

**Comment by infinitewarp** [comment]
QE gave the verbal "okay" about verifying this change at today's standup. Closing now that it's done!
