### ISSUE TITLE
Make sure cloudtrail log analyzer is ready for scale

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#895]
## Summary

As a cloudigrade engineer, I want to make sure that cloudigrade is able to process cloudtrail events fast so that there is no risk of our queue getting backed up and event messages lost.

Currently we fire `api.clouds.aws.tasks.analyze_log` every two minutes, and process a maximum of 300 (Production only, bumped from limit of 10 that exists in every other environment) messages at a time. We should be able to utilize our large number of horizontally scaling worker pods to be able to process messages more often, and in smaller batches.

## Acceptance Criteria

- [x] Verify that the `api.clouds.aws.tasks.analyze_log` runs more often
- [x] Verify that the max yield count has been reduced to a more reasonable number

## Assumptions and Questions

- How often should the task run?
  - @katherine-black thinks we should run it as often as possible, say 5 seconds
- How many messages should each worker pull before considering the task finished?
  - @katherine-black: I think we should aim for smaller numbers, if it takes on average one second to process a cloudtrail event, then maybe we should aim for not tying a worker up for more than thirty seconds. So 25 or so. With the beat firing every 5 seconds anyway, this should allow us to better spread the load among our workers, which in turn should allow our pod autoscaler to be more accurate.

**Comment by katherine-black** [comment]
See also #723

**Comment by katherine-black** [comment]
https://github.com/cloudigrade/cloudigrade/issues/723#issuecomment-845224176

**Comment by infinitewarp** [comment]
The new config values look good. Thanks!
