### ISSUE TITLE
Use persistent django database connections

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#896]
## Summary

As a cloudigrade dev, I want cloudigrade to be able to talk to its database with as few delays as possible so that our users have a great experience.

We, with postigrade, have implemented a connection pooler. That said, by default django closes its own connection to the database after the request finishes, and opens another one when a new request comes in. We can eliminate closing and opening of new connections by using [persistent connections](https://docs.djangoproject.com/en/3.2/ref/databases/#persistent-connections).

## Acceptance Criteria

- [x] Verify that django is configured to use persistent connections
- [x] Verify that database performance does not degrade

## Assumptions and Questions

- Should we set a limit on how long we keep a connection open? Or do we keep it open indefinitely, for the life of the process?
  - Let's start with 60 seconds! That should be more than enough for our api request handling, but we should keep an eye out in case Celery worker tasks that need longer continue to function as expected after 60 seconds.

**Comment by infinitewarp** [comment]
Looks good. Thanks!
