### ISSUE TITLE
Make CloudWatch/Watchtower less bad

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#906]
## Summary

As a cloudigrade sysop, I want to see logs reliably arrive in Kibana via CloudWatch without crashing my process.

Misbehaving AWS and Watchtower not handling it well are resulting in processes getting killed:

- https://sentry.io/organizations/cloudigrade/issues/2402221274/?environment=prod&project=1270349&query=is%3Aunresolved
- https://sentry.io/organizations/cloudigrade/issues/2401034514/?environment=prod&project=1270349&query=is%3Aunresolved
- https://sentry.io/organizations/cloudigrade/issues/2401033407/?environment=prod&project=1270349&query=is%3Aunresolved
- https://sentry.io/organizations/cloudigrade/issues/2401034243/?environment=prod&project=1270349&query=is%3Aunresolved
- https://sentry.io/organizations/cloudigrade/issues/2400585948/?environment=prod&project=1270349&query=is%3Aunresolved
- https://sentry.io/organizations/cloudigrade/issues/2399811559/?environment=prod&project=1270349&query=is%3Aunresolved
- https://sentry.io/organizations/cloudigrade/issues/2399813526/?environment=prod&project=1270349&query=is%3Aunresolved

I think this has been exacerbated by the recent change to reduce our gunicorn worker timeout.

Options to consider for making this better:
- Increase the gunicorn worker timeout. This is a bad solution and is only a temporary fix for some situations. This makes other things bad because a long-running worker means lower API request throughput. If a worker is busy, it can't take another request.
- Finish https://github.com/cloudigrade/cloudigrade/pull/887 and see if updating Watchtower helps.
- Experiment with the various async queue options for Watchtower especially after updating our dependencies. Maybe we can find a combination of settings that it not garbage. Remember that in the past using the defaults for async resulted in two problems: 1) a process with not much log activity meant that looking for log at `n` meant waiting around for log `n+1` to happen, and 2) sometimes logs would mysteriously never arrive in AWS CloudWatch.
- Contribute to Watchtower to make it better.

## Acceptance Criteria

- [ ] Verify logs still arrive in Kibana in a reliable and timely fashion

## Assumptions and Questions

- Even though all those issues reference the concurrent API, @infinitewarp thinks it isn't necessarily a problem with our concurrent API code. Rather, the concurrent API is the only API that's hit with any real frequency that also produces a lot of logs, and therefore it's unsurprising that it is commonly referenced in these issues.

**Comment by infinitewarp** [comment]
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs.html#CloudWatchLogs.Client.put_log_events

> There is a quota of 5 requests per second per log stream. Additional requests are throttled. This quota can't be changed.

**Comment by infinitewarp** [comment]
After much investigation and experimentation and discussion, we have the following setup regarding Watchtower:

- We updated our Watchtower dependency to the latest released version.
- All cloudigrade deployments have various queue-related options for Watchtower exposed as environment variables.
- cloudigrade-api deployments have Watchtower's `use_queues` set to true.
- All other deployments have Watchtower's `use_queues` set to false.
- Watchtower's current implementation of batching messages in threads and queues **does not** work correctly with processes that use multiprocessing like Celery with its workers. With queues enabled in a Celery deployment, any logs produced from within a Celery worker were being emitted to the local console but _were not_ correctly sending to AWS CloudWatch. This is why we _only_ have queues enabled for the cloudigrade-api deployment; the API's simpler use of Django and DRF _does not_ currently use multiprocessing in any known way.

This is certainly not ideal, but it should provide at least marginal improvement in API response times since cloudigrade-api logs should no longer be waiting on synchronous Watchtower/CloudWatch writes. Other deployments should be no better or worse.

**Comment by katherine-black** [comment]
Thank you for all the investigation and rabbit holes you followed for this story. This should hopefully mitigate some of the logging issues until platform logging is ready to take over. Closing.
