### ISSUE TITLE
Run scheduled task to record results from hound

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#92]
As a Doppler admin, I want a scheduled Celery task to check a message queue for results from the hound and write those results to my database so I know those results as soon as possible.

## Acceptance Criteria

- [x] Verify that when there are no messages from houndigrade on the queue, this process does nothing and exits cleanly.
- [x] Verify that when there are any messages from houndigrade on the queue, this process updates the database with the discovered information about the AMI(s).
  - [x] Verify the update sets the full AMI houndigrade JSON string in the database for the AMI (supporting evidence for tags)
  - [x] Verify the RHEL tag is added to database MachineImage if houndigrade JSON detects RHEL
  - [x] Verify the RHEL tag is not added to database MachineImage if houndigrade JSON does not detects RHEL
- [x] Verify that the latest houndigrade facts are applied (meaning a repeat scan removes old tags, adds new tags).  This is not expected to normally happen.

## Tech assumptions

- This requires cloudigrade to have a Celery worker.
- This will include model changes so that we can track all the AMI details.
- Until this point, there may be a nulls in some columns on the AMI/image table, implying that that inspector is off doing things. After we processed results here, there should be no more nulls around the AMI model.

**Comment by ilyavw** [comment]
@kholdaway, the demo provided in https://github.com/cloudigrade/cloudigrade/pull/326#issuecomment-394804660 doesn't do a very good job of demonstrating all of the AC's. The only AC I could verify with that is if the json was saved to the object. Are there other demos I'm missing somewhere?

**Comment by kholdaway** [comment]
@ilyavw @infinitewarp Updated demo.  Take a look -> https://drive.google.com/file/d/1ThojVnCvIF5ya_mrzcZ2yfVpEmo633_V/view?usp=sharing

**Comment by ilyavw** [comment]
Looks good, thank you for taking the time to record an updated demo @kholdaway. Closing.
