### ISSUE TITLE
Investigate possible memory spike with repopulate_azure_instance_mapping

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#952]
## Summary

On 2021-07-20 we saw our worker pods OOMing, and the timing coincided pretty closely with with the new `repopulate_azure_instance_mapping` task was scheduled and running. We should collect some rough metrics and try to determine if there is a problem here that we can address.

## Acceptance Criteria

- [ ] Verify we have some measure of memory usage performance regarding the new `repopulate_azure_instance_mapping` task
- [x] Have a discussion with the team about results and if we should make changes
- [ ] Sentry's performance page shows actual data from cloudigrade excluding the noisy health checks.
- [x] Followup issue/conversation to integrate with AppSRE's instance of Sentry

## Assumptions and Questions

- This task was introduced for https://github.com/cloudigrade/cloudigrade/issues/729.
- Consider running the function locally through some profiling functions and libraries such as:
  - https://docs.python.org/dev/library/sys.html#sys.getsizeof (see also https://code.activestate.com/recipes/577504/ and https://github.com/the-gigi/deep/blob/master/deeper.py#L80)
  - https://pypi.org/project/memory-profiler/ (https://github.com/pythonprofilers/memory_profiler)
  - https://pypi.org/project/line-profiler/ (https://github.com/pyutils/line_profiler)
  - https://pypi.org/project/guppy3/ (https://github.com/zhuyifei1999/guppy3)
  - https://pypi.org/project/filprofiler/ (https://github.com/pythonspeed/filprofiler)
  - https://pypi.org/project/psutil/ (https://github.com/giampaolo/psutil) (using `Process().memory_info()`)
- Consider updating and re-enabling the Sentry profiling/tracing support. Can we filter away irrelevant noise yet?
  - We should be able to define a "Sampling Function" where we can drop irrelevant samples, docs - https://docs.sentry.io/platforms/python/guides/django/configuration/sampling/#setting-a-sampling-function
- Consider https://github.com/cloudigrade/cloudigrade/issues/759 first. Maybe Jaeger can give us some info?
- The internal SRE folks are running their own Sentry instance. Perhaps we can use that instance instead of the public sentry.io instance and enable all the tracing/performance tools. However, we do not know if we have access to this (yet?), and we do not know if the internal SRE instance is a recent enough version that supports all the tracing we would want to use.

**Comment by abellotti** [comment]
First, an  update on the App-SRE instance of sentry https://sentry.devshift.net and https://sentry.stage.devshift.net

When initially attempting to update the app-interface with sentryProjects for cloudigrade here https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/25276 as per Kat's investigation, the build had failed because our names were longer than 30 characters.  I tested the sentry.io interface, and they allow up to 50 characters. After reaching out to the App-SRE team, apparently the App-SRE instance of sentry is an earlier version of sentry.io and they have no plans on upgrading it and the plan is to replace the App-SRE hosted sentry with https://glitchtip.com/ an open source replacement option.  It is unclear whether glitchtip would be better for us or not than sentry.  

Until we know more about the replacement, we'll keep our current sentry.io account for stage and prod, and work with oc logs or the ephemeral environments.

**Comment by abellotti** [comment]
For memory profiling the repopulate_azure_instance_mapping method I ended up using the following:
- https://pypi.org/project/memory-profiler/
- https://pypi.org/project/psutil/
- https://docs.python.org/dev/library/sys.html#sys.getsizeof

The memory-profiler was really useful in showing the line-by-line memory usage and spikes showing here the initial run.

```
Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    44    101.6 MiB    101.6 MiB           1   @profile
    45                                         def _fetch_azure_instance_type_definitions():
    46                                             """ 
    47                                             Fetch Azure instance type definitions from Azure Resource Sku API.
    48    
    49                                             Returns:
    50                                                 dict: definitions dict of dicts where the outer key is the instance
    51                                                 type name and the inner dict has keys memory, vcpu and json_definition.
    52                                                 For example: {'r5.large': {'memory': 24.0, 'vcpu': 1, 'json_definition': {...}}}
    53    
    54                                             """ 
    55    101.7 MiB      0.0 MiB           2       compute_client = ComputeManagementClient(
    56    101.7 MiB      0.0 MiB           1           azure.get_cloudigrade_credentials(), azure.get_cloudigrade_subscription_id()
    57                                             )   
    58    101.9 MiB      0.2 MiB           1       resource_skus = compute_client.resource_skus.list()
    59    101.9 MiB      0.0 MiB           1       instances = {}
    60    420.1 MiB    142.1 MiB       16937       for resource_sku in resource_skus:
    61                                                 # We can not filter by resource_type, so we just ignore anything that's not a vm
    62    420.1 MiB      0.0 MiB       16936           if resource_sku.resource_type != "virtualMachines":
    63    419.0 MiB      0.0 MiB        3212               continue
    64    
    65                                                 # Extract vcpu and memory data from the capabilities list
    66    420.1 MiB      0.0 MiB       13724           vcpu = None
    67    420.1 MiB      0.0 MiB       13724           memory = None
    68    420.1 MiB      0.0 MiB      359705           for capability in resource_sku.capabilities:
    69    420.1 MiB      0.0 MiB      345981               vcpu = capability.value if capability.name == "vCPUs" else vcpu
    70    420.1 MiB      0.0 MiB      345981               if capability.name == "MemoryGB":
    71                                                         # Azure reports memory in GB, here we convert
    72                                                         # GB values to MiB values to keep our instance
    73                                                         # definitions consistent across clouds
    74    420.1 MiB      0.0 MiB       13724                   memory = bitmath.GB(float(capability.value)).to_MiB()
    75    
    76    420.1 MiB      0.0 MiB       13724           instances[resource_sku.name] = { 
    77    420.1 MiB      0.0 MiB       13724               "memory": memory,
    78    420.1 MiB      0.0 MiB       13724               "vcpu": vcpu,
    79    420.1 MiB      1.1 MiB      787222               "json_definition": json.dumps(resource_sku, default=lambda x: x.__dict__),
    80                                                 }   
    81    
    82    245.1 MiB   -175.0 MiB           1       return instances
```

**Comment by abellotti** [comment]
The current azure python packages that include:

```
azure-cli-core                   2.28.0    Microsoft Azure Command-Line Tools Core Module
azure-cli-telemetry              1.0.6     Microsoft Azure CLI Telemetry Package
azure-common                     1.1.27    Microsoft Azure Client Library for Python (Common)
azure-core                       1.18.0    Microsoft Azure Core Library for Python
azure-identity                   1.6.1     Microsoft Azure Identity Library for Python
azure-mgmt-compute               21.0.0    Microsoft Azure Compute Management Client Library for Python
azure-mgmt-core                  1.2.2     Microsoft Azure Management Core Library for Python
azure-mgmt-resource              19.0.0    Microsoft Azure Resource Management Client Library for Python
azure-mgmt-resourcegraph         8.0.0     Microsoft Azure Resource Graph Client Library for Python
```

Have the following versioned bumped on pypi.org:

```
azure-cli-core        2.28.1
azure-mgmt-computer   23.0.0
azure-mgmt-core       1.3.0
azure-mgmt-resource   20.0.0
```

While the release notes don't cry, memory `leak` or `spike`, might be work giving them a try.

**Comment by infinitewarp** [comment]
Thanks for the investigation and thorough notes, @abellotti !

As mentioned elsewhere, I agree that our best course of action here would likely be to stay on top of updated versions and to simply increase the memory requests for our pods since there's no obvious solution to make it use less. We'll want to make those changes soon but not immediately since we're in the middle of rebuilding our deployments with Clowder.

Also, given your recent discovery about the platform's decision to drop Sentry, I also think we shouldn't invest any more time  tweaking our Sentry integration until we have a clear path forward with GlitchTip.
