### ISSUE TITLE
Azure: Serve template for customer onboarding 

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#988]
## Summary

As a cloudigrade developer, I want azure users to easily be onboarded so that we can count their RHEL usage.

## Acceptance Criteria

- [x] Verify that the ARM Template json is served publicly* by cloudigrade 
- [x] Verify that the ARM template endpoint is referenced by the sysconfig endpoint.

## Assumptions and Questions

- Public means that azure can access it without authentication.

**Comment by infinitewarp** [comment]
I may have bad news. At least in stage I am unable to access the new endpoint without the typical HTTP Basic Auth that all public requests coming through 3scale apparently need to have. So, even though cloudigrade doesn't require auth on our end, the incoming request never reaches cloudigrade because it's stopped earlier in the process.

truly anonymous:
```
❯ http --proxy="https:http://squid.corp.redhat.com:3128" https://cloud.stage.redhat.com/api/cloudigrade/v2/azure-offer-template/
HTTP/1.1 401 Unauthorized
Connection: keep-alive
Content-Length: 23
Content-Type: text/plain
Date: Mon, 13 Sep 2021 18:07:50 GMT
Server: openresty
Set-Cookie: 8f585a7d113e400d14faa100d81cbdaf=0c6291f2217436d225f17e4ef135c77b; path=/; HttpOnly; Secure; SameSite=None
X-Frame-Options: SAMEORIGIN
x-content-type-options: nosniff
x-rh-edge-cache-status: Miss from child, Miss from parent
x-rh-edge-reference-id: 0.368cd017.1631556470.528e879a
x-rh-edge-request-id: 528e879a
x-rh-insights-request-id: c4c9174e7746438aacd69bd4a5f66ea4

Missing Authentication
```

versus with HTTP Basic Auth:
```
http --auth $REDHAT_USERNAME:$REDHAT_PASSWORD --proxy="https:http://squid.corp.redhat.com:3128" https://cloud.stage.redhat.com/api/cloudigrade/v2/azure-offer-template/

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Allow: GET, HEAD, OPTIONS
Cache-Control: private
Connection: keep-alive
Content-Length: 1969
Content-Type: application/json
Date: Mon, 13 Sep 2021 18:08:18 GMT
Server: openresty
Set-Cookie: 8f585a7d113e400d14faa100d81cbdaf=0c6291f2217436d225f17e4ef135c77b; path=/; HttpOnly; Secure; SameSite=None
referrer-policy: same-origin
x-cloudigrade-request-id: 65f3877c-d489-4cd0-bba9-93d99cc3e4a1
x-content-type-options: nosniff
x-frame-options: DENY
x-rh-edge-cache-status: Miss from child, Miss from parent
x-rh-edge-reference-id: 0.368cd017.1631556498.528f5003
x-rh-edge-request-id: 528f5003
x-rh-insights-request-id: 82122e0706ed467aab9f3907ecf06161

{
    "$schema": "https://schema.management.azure.com/schemas/2019-08-01/subscriptionDeploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "outputs": {
```

We may need to get help from someone in the platform stack to make this possible.

**Comment by katherine-black** [comment]
After a conversation with @infinitewarp we have agreed that this is not an issue for the moment, as the way this json files ends up being utilized is still up in the air. With the most likely contender involving sources superkey flow in some way, this will certainly change in the future.

**Comment by infinitewarp** [comment]
And with that concern resolved, I'm happy to call this issue done. Thanks again @katherine-black !
