### ISSUE TITLE
Grafana dashboard for our SLIs/SLOs

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#995]
## Summary

As a cloudigrade sysop, I want a grafana dashboard that shows our SLIs over recent time like other platform services (see RBAC and 3scale for reference) so that onboarding can proceed. Working metrics will be required for SRE onboarding SLI/SLO definitions.

The cloudigrade grafana dashboards are missing lots of data were present previously. It is unclear if this is a problem with the dashboard definition or the underlying prometheus metrics. It is also unclear when the data went missing.

Regardless, we may remove all of the current dashboard implementation in favor of a simpler solution that shows only exactly what SRE needs for onboarding and future support.

That being said, if some values are *trivially* easy to include, we may continue to include them below the more critical values. This should really only be trivially easy items that are non-critical. If they break in the future, we should be comfortable simply removing them.

## Acceptance Criteria

- [x] Stage dashboard has data: https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&refresh=10s&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage
- [x] prod dashboard has data: https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&refresh=10s&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod
- [x] cloudigrade dashboards includes same fields as the RBAC dashboard which is here: https://grafana.app-sre.devshift.net/d/slo-dashboard/slo-dashboard?orgId=1&from=now-7d&to=now&var-datasource=crcp01ue1-prometheus&var-label=rbac

## Additional context

- see also https://github.com/cloudigrade/cloudigrade/wiki/Monitoring
  - please update this page alongside this issue to remove dead links, etc.
- cloudigrade currently includes the `django-prometheus` library to collect and expose various application-level metrics. Since the dashboard definition for other services like RBAC and 3scale do not need such detail, we can/should remove this library and any calls to it. This also means removing the `/metrics` url path from the main Django app *and* the special extra port exposed for the listener. 
- cloudigrade currently serves prometheus metrics via internal URLs, but may stop serving them after this change.
  - stage: https://internal.cloud.stage.redhat.com/api/cloudigrade/internal/metrics
  - prod: https://internal.cloud.redhat.com/api/cloudigrade/internal/metrics
- For reference, RBAC's is defined here: https://github.com/RedHatInsights/insights-rbac/blob/master/dashboards/grafana-dashboard-insights-rbac-operations.configmap.yaml

**Comment by infinitewarp** [comment]
Regarding that "2 unapplied migrations" comment in prod, I'm not sure where it's getting that number, but when I checked for migrations directly in a prod pod, everything looks fine.

```
python manage.py showmigrations --list
```

```
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
api
 [X] 0001_v2_models
 [X] 0002_rename_AwsEC2InstanceDefinition
 [X] 0003_machineimageinspectionstart
 [X] 0004_concurrentusage
 [X] 0005_awscloudaccount_aws_access_key_id
 [X] 0006_store_instances_list
 [X] 0007_delete_concurrentusage
 [X] 0008_delete_concurrentusage
 [X] 0009_concurrentusage_potentially_related_runs
 [X] 0010_auto_20200122_1644
 [X] 0011_machineimage_rhel_detected_by_tag
 [X] 0012_auto_20200219_2133
 [X] 0013_cloudaccount_is_enabled
 [X] 0014_cloudaccount_enabled_at
 [X] 0015_cloudaccount_enabled_at
 [X] 0013_cloudaccount_platform_application_id
 [X] 0016_merge_20200323_1556
 [X] 0017_cloudaccount_delete_platform_null
 [X] 0018_cloudaccount_platform_not_null
 [X] 0019_cloudaccount_alter_unique_together
 [X] 0020_verify_aws_access
 [X] 0021_delete_orphaned_periodic_tasks
 [X] 0022_reset_verify_task_schedules
 [X] 0023_machineimage_architecture
 [X] 0024_auto_20200605_1531
 [X] 0025_remove_concurrentusage_cloud_account
 [X] 0026_remove_concurrent_usage_model
 [X] 0027_concurrentusage
 [X] 0028_concurrentusage_potentially_related_runs
 [X] 0029_concurrentusagecalculationtask
 [X] 0030_auto_20200824_1532
 [X] 0031_auto_20200826_1418
 [X] 0032_auto_20200826_1442
 [X] 0033_azurecloudaccount_azureinstance_azureinstanceevent_azuremachineimage
 [X] 0034_remove_cloudaccount_platform_endpoint_id
 [X] 0035_usertasklock
 [X] 0036_auto_20210216_1906
 [X] 0037_delete_instance_definition
 [X] 0038_instancedefinition
 [X] 0039_concurrentusagecalculationtask_pending
 [X] 0040_auto_20210429_1854
 [X] 0041_auto_20210701_2050
 [X] 0042_delete_concurrentusagecalculationtask
 [X] 0043_auto_20210722_1652
 [X] 0044_alter_concurrentusage_date
 [X] 0045_auto_20210722_2020
 [X] 0046_cloudaccount_platform_application_is_paused
 [X] 0047_auto_20210827_2221
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
 [X] 0012_alter_user_first_name_max_length
authtoken
 [X] 0001_initial
 [X] 0002_auto_20160226_1747
 [X] 0003_tokenproxy
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
db
 [X] 0001_initial (1 squashed migrations)
django_celery_beat
 [X] 0001_initial
 [X] 0002_auto_20161118_0346
 [X] 0003_auto_20161209_0049
 [X] 0004_auto_20170221_0000
 [X] 0005_add_solarschedule_events_choices
 [X] 0006_auto_20180322_0932
 [X] 0007_auto_20180521_0826
 [X] 0008_auto_20180914_1922
 [X] 0006_auto_20180210_1226
 [X] 0006_periodictask_priority
 [X] 0009_periodictask_headers
 [X] 0010_auto_20190429_0326
 [X] 0011_auto_20190508_0153
 [X] 0012_periodictask_expire_seconds
 [X] 0013_auto_20200609_0727
 [X] 0014_remove_clockedschedule_enabled
 [X] 0015_edit_solarschedule_events_choices
sessions
 [X] 0001_initial
util
 (no migrations)
```

**Comment by abellotti** [comment]
Grafana Locations:

Cloudigrade:
- SLO Dashboard: https://grafana.app-sre.devshift.net/d/slo-dashboard/slo-dashboard?orgId=1&from=now-7d&to=now&var-datasource=crcp01ue1-prometheus&var-label=cloudigrade
- Stage Dashboard: https://grafana.stage.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&refresh=10s&var-datasource=crcs02ue1-prometheus&var-namespace=cloudigrade-stage
- Prod Dashboard: https://grafana.app-sre.devshift.net/d/O6v4rMpizda/cloudigrade?orgId=1&refresh=10s&var-datasource=crcp01ue1-prometheus&var-namespace=cloudigrade-prod

RBAC:
- SLO Dashboard: https://grafana.app-sre.devshift.net/d/slo-dashboard/slo-dashboard?orgId=1&from=now-7d&to=now&var-datasource=crcp01ue1-prometheus&var-label=rbac

**Comment by abellotti** [comment]
Updated Cloudigrade Dashboard that only uses the API 3scale gateway and kubernetes metrics:
![grafana_v10](https://user-images.githubusercontent.com/5797328/134434036-a4e62fa3-59b0-41e0-97b3-b5024c09dab2.png)

**Comment by infinitewarp** [comment]
Thanks for the rewrite! It's looking good. 👍

**Comment by abellotti** [comment]
Thanks @infinitewarp for also adding the SLO dashboard links here: https://github.com/cloudigrade/cloudigrade/wiki/Monitoring  was gonna do that next :)
